### ISSUE TITLE
一键继续下载功能

### ISSUE THREAD

**Issue by maxcmonster** [Pixeval/Pixeval#109]
稍有些贪心不足的小问题：
下载时候，有些大拿的作品数量又多，文件又大，难免一些文件中途卡住了。
现在都需要一个，一个文件的点击重新下载，
不知道是否可以加一个“全部重新下载”的功能？这样卡住的文件可以一键就全部重新继续下载了。

有时候遇到几百个文件卡住，一个个重新下载还真是蛮头疼的 T T

**Comment by Poker-sang** [comment]
在下一个版本中修复了
