### ISSUE TITLE
程序经常在启动时就停止工作

### ISSUE THREAD

**Issue by wyk2125** [Pixeval/Pixeval#126]
每次双击启动或者用管理员启动，都会在 登入时 出现程序停止工作

![360截图20201222010746048](https://user-images.githubusercontent.com/76446296/102802907-5a3c9b00-43f2-11eb-8bae-f0786b21f079.jpg)

这要怎么解决？

**Comment by dylech30th** [comment]
更新到最新版本，然后还是出错的话打开事件查看器看看什么问题
#134
