### ISSUE TITLE
建议反馈

### ISSUE THREAD

**Issue by Root-1404** [Pixeval/Pixeval#130]
在浏览界面图片或者查看用户时候，有时候会单击无响应。需要重新退出程序浏览。
（不排除可能网络机子性能等原因）
**建议：**
在作品榜单顶部UI添加可操作滚动模块， 想看r18的内容的时候发现不可操作。需要点击词条来刷新下一个。

增加一个翻页功能

搜索词条栏添加回车可搜索

**Comment by dylech30th** [comment]
这些会在重写UI之后的项目里体现的，现在在重写UI

**Comment by Root-1404** [comment]
> 这些会在重写UI之后的项目里体现的，现在在重组UI

![捕获](https://user-images.githubusercontent.com/77722478/105349598-eaa21180-5c24-11eb-9775-914202a67868.PNG)
补：昨天评论，由于文字部分表达欠缺。奉上截图（下载东西过多，大概20张下载出现页面卡死。键盘鼠标无法退出）

**Comment by LasmGratel** [comment]
新版已优化界面逻辑
