### ISSUE TITLE
P站鉴权接口改动，正在跟进修复，在此之前Pixeval将会不可用

### ISSUE THREAD

**Issue by dylech30th** [Pixeval/Pixeval#134]

**Comment by Sharp-lxr** [comment]
登陆显示账号密码错误和这个有关吗

**Comment by SasamiyaNatsuki** [comment]
> 登陆显示账号密码错误和这个有关吗

我也是。。。。我昨天今天都用着好好地，然后不小心手贱按了个退出登录，现在也登不上了。。。。一直显示账号密码错误，希望给退出登录加个二次确认，或者塞到设置里

**Comment by henryEX** [comment]
鉴权接口就是登录的时候的，如果不退出登录就可以正常使用

**Comment by SasamiyaNatsuki** [comment]
好的，辛苦大佬了，请加油




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dylech30th/Pixeval"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 中午1:51
收件人:&nbsp;"dylech30th/Pixeval"<Pixeval@noreply.github.com&gt;;
抄送:&nbsp;"superman酷"<764740116@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [dylech30th/Pixeval] P站鉴权接口改动，正在跟进修复，在此之前Pixeval将会不可用 (#134)





 
鉴权接口就是登录的时候的，如果不退出登录就可以正常使用

**Comment by Sharp-lxr** [comment]
> 鉴权接口就是登录的时候的，如果不退出登录就可以正常使用

谢谢，家长翻电脑，就退出来了结果登不上去了

**Comment by Sharp-lxr** [comment]
> > 登陆显示账号密码错误和这个有关吗
> 
> 我也是。。。。我昨天今天都用着好好地，然后不小心手贱按了个退出登录，现在也登不上了。。。。一直显示账号密码错误，希望给退出登录加个二次确认，或者塞到设置里
嗯，对对对

**Comment by dylech30th** [comment]
其实主要是春节这段时间比较摸....我是有现成的解决方案的

**Comment by 15910650618** [comment]
什么时候能维修好啊

**Comment by dylech30th** [comment]
emmmm，你得等我过完元宵节啊....好不容易有了休息的时间我得摸摸鱼(

**Comment by 15910650618** [comment]
> emmmm，你得等我过完元宵节啊....好不容易有了休息的时间我得摸摸鱼(

元宵快乐，加油修

**Comment by Icarus2333** [comment]
两周没这个用 我要死了

**Comment by 15910650618** [comment]
什么时候修好啊哇啊

**Comment by dylech30th** [comment]
大概再过个两三天吧

**Comment by vvvvvvvalong** [comment]
坐等大佬修复，刚来

**Comment by nyaxs** [comment]
嘤嘤嘤大佬冲冲冲

**Comment by dylech30th** [comment]
晦气，我tm想了半天不使用代理使用WebView2自带的请求拦截去处理web端的直连
结果HttpClient没法处理302 redirect，就算关了`AllowAutoRedirect`这个URL也偏偏不行
搞了半天还是回去自己写代理简单

**Comment by dylech30th** [comment]
已修复，请使用自动更新器/下载新发布的[3.1.0 release](https://github.com/dylech30th/Pixeval/releases/tag/3.1.0)/前往[项目主页](https//sora.ink/Pixeval)以更新到最新版本。
fixed, use auto-updater/the newest [release(3.1.0)]((https://github.com/dylech30th/Pixeval/releases/tag/3.1.0))/go to the [project website](https//sora.ink/Pixeval) to update Pixeval to the latest version.
see dylech30th@c74875ef0b4ea3b26fe0613e5e6bae2c127e3127

**Comment by dylech30th** [comment]
注，新版本需要使用WebView2与一个自签证书作为登录手段，第一次使用过程中会弹窗，请按照弹窗操作
防杠：尽管我自己都忘了私钥是什么，但肯定还是会有人说我签的证书不安全，因此我以后会添加一个允许用户使用自签证书的接口，在那之前实在是信不过我可以选择暂时不用

**Comment by BoomBoom000** [comment]
> 注，新版本需要使用WebView2与一个自签证书作为登录手段，第一次使用过程中会弹窗，请按照弹窗操作
> 防杠：虽然我自己都忘了私钥是什么，但肯定还是会有人说我签的证书不安全，因此我以后会添加一个允许用户使用自签证书的接口，在那之前实在是信不过我可以选择暂时不用

现在下载的图片名称会变成最终路径文件夹的名称，并且会下到前一个路径里面

**Comment by KomiyaTaichi** [comment]
始終提示要更新這個東西，怎麼更新都沒有用

**Comment by Poker-sang** [comment]
我也不清楚，要是能临时创建一个ca证书给用户用就方便了，但好像找不到的样子

**Comment by Akarinnnnn** [comment]
这样吗，那现在的证书能提取出来吗，我研究下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月12日(周三) 下午4:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Pixeval/Pixeval] P站鉴权接口改动，正在跟进修复，在此之前Pixeval将会不可用 (#134)




 
我也不清楚，要是能临时创建一个ca证书给用户用就方便了，但好像找不到的样子
