### ISSUE TITLE
添加用户自签证书作为登录API代理证书的支持

### ISSUE THREAD

**Issue by dylech30th** [Pixeval/Pixeval#138]
https://github.com/dylech30th/Pixeval/issues/134#issuecomment-794426147

**Comment by tychedy** [comment]
能说一下证书名么，我自己路由器挂了代理的，添加了证书 无法登陆了

**Comment by dylech30th** [comment]
安装的证书可以在受信任的根证书颁发机构里找到，名字是Dylech30th Do Not Trust Certificate Authority

**Comment by dylech30th** [comment]
但是我猜测你无法登陆的原因可能和证书无关

**Comment by AnotiaWang** [comment]
这个证书的作用是保证直连登录正常对吗？
![image](https://user-images.githubusercontent.com/62269186/123764522-710aff80-d8f7-11eb-839a-2497664fe7f5.png)
如果不需要用到直连登录的话，能不能选择不安装证书呢

（顺带提一嘴是登**录**不是登陆）

**Comment by zhiye6178** [comment]
但其实，安装了证书之后，程序也不是默认开启【直连】的，还需要自己打开开关，所以这一步可以集成到开关那里吗？不安装证书就没办法运行程序。
