### ISSUE TITLE
感觉3.1.1的保存路径宏对电脑废有点不友好

### ISSUE THREAD

**Issue by SpicesL** [Pixeval/Pixeval#141]
请问下大佬，如何设置路径宏才能恢复以前的保存模式
例如：多图时，在指定目录下，新建编号文件夹，图片为作者+编号+页数
           单图时，在指定目录下，图片为作者+编号

我实在是搞不太懂如何编辑路径宏，谢谢

**Comment by Icarus2333** [comment]
确实 不会用了

**Comment by Icarus2333** [comment]
但其实就是把提示的分号连接在一起  然后在原路径的基础上多个/   这个/是出发大引号们的条件指令

**Comment by dylech30th** [comment]
注意我的tooltip中提到的
![E0N9BX1JJSA7ZLC6Q{(D ZN](https://user-images.githubusercontent.com/31894334/110680144-3465ac00-8213-11eb-8c0e-c5bb689ac856.png)
如果图片是多图的，则`{manga.title}`返回作品标题，如果是单图则返回空字符串
同时如果图片是多图的，也就是`{manga.title}`不为空，那么`{illust.title}`的值会被忽略
也就是`{manga.title}`和`{illust.title}`的值二选一
同时空的子目录会被移除掉，比如`aa\{manga.title}\bb`，如果图片是单图，那么`{manga.title}`的值是空的，则该路径求值结果并非`aa\\bb`而是`aa\bb`
因此，假如你想要在指定目录，比如`D:\Pictures`下实现你的需求，可以这么填写路径:
`D:\Pictures\{manga.title}\[{user.name}]{illust.id}_{manga.index}.{illust.ext}`
假设有一副作品，ID是12345678，作品名是"EFG"，用户名是"ABC"，类型是JPG
1. 单图时路径求值为:`D:\Pictures\[ABC]12345678_0.jpg`
2. 多图时假设这一张在多图列表里是第三张，那么路径求值为:`D:\Pictures\EFG\[ABC]12345678_2.jpg`
这样就可以做到你的需求了，我会在下个版本中加入对于`{manga.id}`的支持以完全实现的你的需求

**Comment by Icarus2333** [comment]
gif和png我不会设置  会全部归为jpg

**Comment by SpicesL** [comment]
谢谢大佬！这下我明白了，其实昨天您的tips我研究了好久，因为是电脑语言废所以完全没看懂。
还想请问下，您打算在后续版本加入的{manga.id}，如果我没理解错，是不是到时只要替换掉上面的{manga.title}就能做到多图时
新建的文件夹名为数字编号了，谢谢

**Comment by dylech30th** [comment]
是的

**Comment by dylech30th** [comment]
> gif和png我不会设置 会全部归为jpg
只需要用{illust.ext}就可以了，下载时会把{illust.ext}替换为对应的后缀名

**Comment by SpicesL** [comment]
啊不好意思，还有个小问题，每次下载文件时pixeval好像会给路径第一个里面自动建两个文件夹“保存的图片”和“本机照片”，删除后下次下载还会继续建，请问有什么方法关闭这个吗

**Comment by dylech30th** [comment]
emmm what?我没有遇到过这情况，我也没有写创建类似文件夹的代码，你确定是pixeval创建的？

**Comment by SpicesL** [comment]
是的，昨天就发现有这个小情况，我删除了几次，发现每次下载新图片它都会在我指定的文件夹里新建这两个文件夹
![QQ截图20210311114351](https://user-images.githubusercontent.com/80334966/110732466-2e95b800-825f-11eb-88ab-c513a93d2612.png)

**Comment by SpicesL** [comment]
啊实在不好意思，我想起来昨天好像不小心把C盘“icloud照片”文件夹复制进去了，可能是那个东西里面的，应该跟pixeval没关系，谢谢！

**Comment by dylech30th** [comment]
3.1.2更新，对宏做出了一些修改
现在可以使用类似`{if:manga:xxxx}`来作为条件宏了
比如对于条件宏{if:manga:{illust.id}}，如果是多图作品则会返回作品id，如果是只有一张图的作品则返回空字符串
更详细的举个例子: 
有一个作品ID是12345678，作品名"ABC"，作者ID是4321，作者名是"EFG"，文件类型是jpg
对于路径宏`D:\Pictures\{if:spot:{spot.title}}\{if:manga:{illust.title}}\{illust.id}{if:manga:_p{manga.index}}.{illust.ext}`
1. 如果该作品是你看特辑的时候打开的，特辑名是"SPOT"，路径会变成:`D:\Pictures\SPOT\12345678.jpg`
2. 如果该作品是多图，并且当前是图片列表的第3张，路径会变成`D:\Pictures\EFG\12345678_p2.jpg`
3. 如果以上两点都不是，则该作品是普通的只有一张图的作品，路径会变成`D:\Pictures\12345678.jpg`
注意上面几条中使用到了提示的"空的子目录会被忽略"这一点，也就是当图片不是多图时，`{if:manga:{illust.title}}`求值为空，因此这个子目录会被直接忽略，当图片不属于特辑时，`{if:spot:{spot.title}}`求值也是空的，因此相对的子目录也会被直接忽略，条件宏都遵循这种语法:`{if:<type>:<stmt>}`和`{ifn:<type>:<stmt>}`，其中`if`前缀的代表“如果作品是<type>类型的，那么就返回<stmt>的内容，否则返回空字符串”，而`ifn`前缀的代表"如果作品不是<type>类型的就返回<stmt>的内容，否则返回空字符串"，注意到条件宏的<stmt>部分也可以用其他宏(比如上述的`{if:manga:{illust.id}}`和`{if:manga:_p{manga.index}}`的<stmt>部分就包含了其他的宏，这一点在注意事项里也有提到)

如果你实在是不明白这套宏是怎么用的的话，可以直接清空下载路径栏的内容，就会给你使用预设的默认路径了，这个默认路径已经可以处理绝大部分情况

**Comment by SpicesL** [comment]
谢谢大佬！！

**Comment by SpicesL** [comment]
跟大佬反馈下我这边在3.1.2版本遇到的小问题，.{illust.ext}这个分辨文件类型的结尾宏命令，好像无法分辨gif文件，会将gif直接保存成jpg文件，我也清空自己的保存路径用默认路径对gif文件进行了下载测试，结果一样，不知道是什么地方出了问题，望大佬解惑，谢谢~

**Comment by dylech30th** [comment]
好的，我看看，尽快修复

**Comment by Poker-sang** [comment]
在下一个版本中修复了
