### ISSUE TITLE
当前目标

### ISSUE THREAD

**Issue by dylech30th** [Pixeval/Pixeval#143]
计划目标:
- [ ] 自签证书支持 #138 
- [x] 大图 #97 #86
- [x] 图片浏览器的缓存和自动翻页 #86 
- [ ] ~~作品点赞 #135~~
- [x] 下载路径宏的自动补全支持
- [x] 修复用户浏览界面的StackPanel无限高度导致的虚拟化失败与内存泄漏问题 #98
- [x] 通过收藏标签查找作品 #97
- [x] 修复GIF保存路径无法识别的问题 #141

弹性目标:
- [ ] Fanbox支持 #22 
- [x] 代理支持 #77

**Comment by Summpot** [comment]
艹，不是要重写

**Comment by dylech30th** [comment]
首先你得等WinUI3 stable了，否则还是得先写老的

**Comment by Summpot** [comment]
别，都得等，maui的win实现那就是winui，maui也在等，到时候两开花

**Comment by dylech30th** [comment]
maui还早着呢，winui这个月就正式版了啊

**Comment by Summpot** [comment]
maui那边速度快的像是在赛跑，应该等不了太久（）
