### ISSUE TITLE
小图预览窗口可否改为 原图长宽比

### ISSUE THREAD

**Issue by rockwallll** [Pixeval/Pixeval#145]
我注意到目前的小图预览有两种，一种是常见的宽屏小图，还有一种用户动态那边的正方形小图。
宽屏小图预览竖屏图就非常尴尬，正方形预览什么图都有点尴尬。

小图预览窗口能不能改成支持原图长宽比，然后类似拼图一样，拼在一起，并且左侧菜单栏可以折叠起来。这样一来，一个屏幕能显示的预览小图大大增加了，并且预览小图还原度也更高。

**Comment by rockwallll** [comment]
还有预览的小图能不能给个更高的画质。或者给个画质选项

**Comment by dylech30th** [comment]
关于画质调节是可以的，但是说用支持原图长宽比那种，那样的话就不能够按照收藏数排序了，某个作品的位置只能按照长宽决定
以前自己考虑过这个想法，但是就是因为这个原因所以最终决定没有那么做

**Comment by Poker-sang** [comment]
最新版本已实现
