### ISSUE TITLE
搜索后下载多图问题

### ISSUE THREAD

**Issue by xioec** [Pixeval/Pixeval#146]
在主页进行指定图片搜索后，若结果是多图，点击下载后下方虽然显示已加入下载列表，但实际情况并没有进行下载动作。只能在搜索后进入作者主页再点击那张多图，在此页面点击下载，提示加入下载列表后才能成功下载。其他例如每日推荐、用户新作之类点击多图下载则无此问题。若是个人的问题请告知下解决方法，若是软件问题，烦请修复，谢谢！

**Comment by Poker-sang** [comment]
在下一个版本中修复了
