### ISSUE TITLE
查看R-18榜图片闪退及无法下载所有榜区图片

### ISSUE THREAD

**Issue by TTZSGAME** [Pixeval/Pixeval#151]
亲爱的dylech30th大佬：
     你好！在最新版本的Pixeval中，当我观看R-18和R-18G时，出现图片无法查看详细和下载的情况。之后，我转到其它榜单上去下载图片，发现所下载的图片都是以我在设置中命名默认下载文件夹的名称。并且由于只能下载到我所设置盘符下的根目录，所以当我下载一张图片后，由于同一目录下不能有重复名称的同类型的文件存在，所以下载好一张图片后就必须要把图片更名或移动到其它文件夹下去，而那些图集只能的进入到详情面后手动的一张张下载，并且每下载完一张后都要更名和移动，实属不便。希望能尽快修复这个bug。（详情可见附件1）

      另外，在我使用的过程中，我觉的有两个小地方可以改进一下：
           1.设置中的直连可以默认打开。因为在登录P站账号时没打开直连进入的速度非常慢，并且还有可能出现登录不上的情况；
           2.希望能够把界面的缩小、关闭和全屏的设置重新弄上来，总觉的没了这些选项感觉怪怪的。（详情可见附件2）
      希望我的建议能被采纳！同时，也谢谢dylech30th大佬对这个项目的投入和坚持，谢谢了!
![附件1](https://user-images.githubusercontent.com/61264022/113529897-4c083880-95f7-11eb-9b25-24ac589d720c.png)
![附件2](https://user-images.githubusercontent.com/61264022/113529900-4d396580-95f7-11eb-88c5-e245006cfb11.png)

**Comment by DJmp3** [comment]
同样碰见图片跟下载文件夹重名  你重新登录一下  能暂时变回到原来那样    或者下载目录后面＋   \{if:spot:{spot.title}}\{if:manga:{illust.title}}\{illust.id}{if:manga:_p{manga.index}}.{illust.ext}

**Comment by DJmp3** [comment]
同样碰见图片跟下载文件夹重名  你重新登录一下  能暂时变回到原来那样    或者目录后面加（图下）
![QQ截图20210424185428](https://user-images.githubusercontent.com/53807258/115956297-a168a300-a52e-11eb-8022-97da038cb2fe.png)

**Comment by dylech30th** [comment]
我会着手修复这个问题，但是最近不行，我在忙着考试
高中生，理解万岁(
