### ISSUE TITLE
图片搜索不全

### ISSUE THREAD

**Issue by wuluki** [Pixeval/Pixeval#153]
有些图片还在，可是搜索不到

**Comment by wuluki** [comment]
<img width="1080" alt="2021-04-05 (2)" src="https://user-images.githubusercontent.com/81970738/113578995-40982a00-9656-11eb-82b2-b9f48eb67a6a.png">
<img width="1080" alt="1" src="https://user-images.githubusercontent.com/81970738/113579018-4726a180-9656-11eb-8b1f-f7983cac6b6e.png">
<img width="1080" alt="2" src="https://user-images.githubusercontent.com/81970738/113579025-4988fb80-9656-11eb-9dba-52265939a3d4.png">
搜索两个关键词也找不到

**Comment by gmstar2021** [comment]
鼠标图片几下，一套图都叠起来的，没有图片张数显示
