### ISSUE TITLE
{illust.title}和{illust.id}的解释是不是反了？

### ISSUE THREAD

**Issue by netazero** [Pixeval/Pixeval#156]
作品下载位置的解释
2.{illust.id}作品名
3.{illust.title}作品id
实际试了下是反过来的。

**Comment by netazero** [comment]
还有，大佬可以尝试下支持鼠标侧键吗 |･ω･｀)

**Comment by dylech30th** [comment]
反馈收到，下个版本会修复，最近忙

**Comment by netazero** [comment]
> 反馈收到，下个版本会修复，最近忙

大佬辛苦
