### ISSUE TITLE
图片下载路径设置有误

### ISSUE THREAD

**Issue by JEZZing** [Pixeval/Pixeval#160]
当完成设置pixeval图片下载路径时，图片并未保存到设置的文件夹，而是保存到目标文件夹的上一层文件夹，且图片名称被改为目标文件夹名称。
![2021-05-04 (3)](https://user-images.githubusercontent.com/83654657/117019097-aea04180-ad27-11eb-837b-9b79fe630929.png)
![2021-05-04 (4)](https://user-images.githubusercontent.com/83654657/117019115-b4962280-ad27-11eb-88d8-51ac658487bf.png)
![2021-05-04 (5)](https://user-images.githubusercontent.com/83654657/117019120-b52eb900-ad27-11eb-97a4-24ab2fc430d4.png)
![2021-05-04 (6)](https://user-images.githubusercontent.com/83654657/117019123-b65fe600-ad27-11eb-9029-796a811d2303.png)
若再次以相同路径下载另外的图片，上一次下载的图片还会被覆盖掉。
![2021-05-04 (7)](https://user-images.githubusercontent.com/83654657/117019534-1060ab80-ad28-11eb-8fc7-ca1d15c221ce.png)

**Comment by Blacktea213** [comment]
我也是这样的

**Comment by JEZZing** [comment]
> 这个下载路径是需要包含文件名的，要加上 {illust.id}_p{manga.index}.{illust.ext} 这个才是图片对应的文件名

OK谢啦（没想到当个lsp还得学代码doge）

**Comment by haleina** [comment]
> 这个下载路径是需要包含文件名的，还要加上{illust.id}_p{manga.index}.{illust.ext}这个才是图片对应的文件名

请问那要怎么设置呢   没看懂怎么办

**Comment by dylech30th** [comment]
啊。。这个宏果然太复杂了
我最近思考一个更简单的思路好了，想用宏的可以用宏，不想用宏的可以用更简化的设置

**Comment by madance363** [comment]
> > 这个下载路径是需要包含文件名的，还要加上{illust.id}_p{manga.index}.{illust.ext}这个才是图片对应的文件名
> 
> 请问那要怎么设置呢 没看懂怎么办

直接复制这一串，就可以按照作品的id自动生成文件名了，{illust.id}就是作品id，p{manga.index}就是某个作品里的第几张图，{illust.ext}就是文件扩展名比如jpg png之类的

**Comment by dryfishs** [comment]
如果想像pixeval初期未更新时的命名的话可以试试这条[{user.name}]{illust.id}_p{manga.index}.{illust.ext}，有一说一我觉得以前的更顺眼。

**Comment by Poker-sang** [comment]
在下一个版本中修复了
