### ISSUE TITLE
3.1.2版本卡在登录应该怎么处理

### ISSUE THREAD

**Issue by 1402701217** [Pixeval/Pixeval#164]
![QQ截图20210513110117](https://user-images.githubusercontent.com/76500611/118071536-8d4fed00-b3da-11eb-943a-d8bb93db79c5.png)

**Comment by gmstar2021** [comment]
更新版本，哥哥

**Comment by 1402701217** [comment]
> 更新版本，哥哥

3.1.2不是最新版本吗？

**Comment by gmstar2021** [comment]
我的能登录啊卧槽

**Comment by 1402701217** [comment]
> 我的能登录啊卧槽

你这说了和没说有区别吗？

**Comment by gmstar2021** [comment]
你有p站账号吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 中午11:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dylech30th/Pixeval] 3.1.2版本卡在登录应该怎么处理 (#164)





  
更新版本，哥哥
  
3.1.2不是最新版本吗？

**Comment by gmstar2021** [comment]
冲作者邮箱




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 中午11:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dylech30th/Pixeval] 3.1.2版本卡在登录应该怎么处理 (#164)





  
我的能登录啊卧槽
  
你这说了和没说有区别吗？

**Comment by 1402701217** [comment]
> 你有p站账号吗
有啊，没有账号我是怎么登录的？我这都有登录位置邮件提示了，就是卡在正在登录这进不去。
你有认真看问题吗

**Comment by gmstar2021** [comment]
祝你好运

**Comment by dylech30th** [comment]
我猜你的web登录过不去，网络原因，可以在不同时间段多试几次
这种问题我没法直接解决，因为不同地区的网络环境也不同
抱歉回复晚了，忙高考
另：如果电脑上实在是无法登录的话可以尝试使用pixez_flutter，github同样可以搜到

**Comment by 1402701217** [comment]
> 我猜你的web登录过不去，网络原因，可以在不同时间段多试几次
> 这种问题我没法直接解决，因为不同地区的网络环境也不同
> 抱歉回复晚了，忙高考
> 另：如果电脑上实在是无法登录的话可以尝试使用pixez_flutter，github同样可以搜到

好的，麻烦你了，我再试一试，不行的话在练习您
