### ISSUE TITLE
打开软件窗体变得超大

### ISSUE THREAD

**Issue by lzlclzyx** [Pixeval/Pixeval#167]
几乎占据了整个屏幕，但是又不是全屏。

右上角的最小化、关闭按钮都看不到。

感觉太突兀了。

**Comment by dylech30th** [comment]
等我高考完再考虑继续写
考试要紧

**Comment by zchiMandom** [comment]
顺便再求个打开时窗口大小和位置保持上次关闭时的设置（方便上班摸鱼时使用

**Comment by dylech30th** [comment]
好的，考试结束开始肝

**Comment by AnotiaWang** [comment]
> 几乎占据了整个屏幕，但是又不是全屏。
> 
> 右上角的最小化、关闭按钮都看不到。
> 
> 感觉太突兀了。

确实。我发现可以在窗口的右边缘拉动一下，顶部就显示出来了

一开始启动的时候是这样 

![image](https://user-images.githubusercontent.com/62269186/123770742-18d6fc00-d8fd-11eb-98c4-b08b05f81a64.png)

**Comment by zhiye6178** [comment]
windows10 21h1 问题仍然存在

**Comment by Poker-sang** [comment]
在下一个版本中修复了
