### ISSUE TITLE
登入异常-无法创建数据目录

### ISSUE THREAD

**Issue by youlan2333** [Pixeval/Pixeval#169]
![QQ截图20210612075845](https://user-images.githubusercontent.com/64688148/121758710-1a5ea100-cb55-11eb-9ad0-603e46a1f4bf.png)
![QQ截图20210612080403](https://user-images.githubusercontent.com/64688148/121758711-1cc0fb00-cb55-11eb-8c66-130460de6a68.png)

**Comment by dylech30th** [comment]
管理员模式运行，或者换个目录存储
程序没有对Program Files目录的读写权限

**Comment by youlan2333** [comment]
> 管理员模式运行，或者换个目录存储
> 程序没有对Program Files目录的读写权限

感谢，管理员模式没用，换目录解决了
