### ISSUE TITLE
为什么登录界面是空白的？求助

### ISSUE THREAD

**Issue by 1SAS** [Pixeval/Pixeval#170]
![GYW6NY~0A4X@~WOC(8A`C$O](https://user-images.githubusercontent.com/85825591/121802355-694c2980-cc6e-11eb-9a46-9342f428839b.png)

**Comment by dylech30th** [comment]
之前没有什么弹窗出现过吗？你安装webview2 runtime了没有，没有安装的话是会提示的

**Comment by 1SAS** [comment]
> 之前没有什么弹窗出现过吗？你安装webview2 runtime了没有，没有安装的话是会提示的

只提示过安装证书

**Comment by dylech30th** [comment]
https://go.microsoft.com/fwlink/p/?LinkId=2124703
这个链接的内容下载安装一下再试试
如果还不行的话就是你的网络环境问题，移动运营商有时候没法成功

**Comment by 1SAS** [comment]
> https://go.microsoft.com/fwlink/p/?LinkId=2124703
> 这个链接的内容下载安装一下再试试
> 如果还不行的话就是你的网络环境问题，移动运营商有时候没法成功

![image](https://user-images.githubusercontent.com/85825591/121802903-7dddf100-cc71-11eb-88e2-1fcbaa8ac298.png)
试了2个网 和热点都没用

**Comment by dylech30th** [comment]
那应该是运营商问题，在国内的部分地域本应用这种绕过SNI的手段会失效
