### ISSUE TITLE
【求助】Object reference not set to aninstance of an object.

### ISSUE THREAD

**Issue by annkei** [Pixeval/Pixeval#172]
### Object reference not set to aninstance of an object.
![image](https://user-images.githubusercontent.com/80564420/123741349-7870df80-d8dc-11eb-9fe5-e202715a874d.png)

**Comment by annkei** [comment]
![image](https://user-images.githubusercontent.com/80564420/123741533-cdacf100-d8dc-11eb-89be-7d05f71f6c03.png)

**Comment by Poker-sang** [comment]
在下一个版本中修复了
