### ISSUE TITLE
feat: 可选预览图片画质 & 缓存持久化

### ISSUE THREAD

**Issue by AnotiaWang** [Pixeval/Pixeval#173]
建议可以设置点击图片预览时显示的图片画质

另外，貌似是关闭预览窗口以及图片离开屏幕范围就会删除缓存，如果翻回去就要重新下载，有点浪费流量

**Comment by dylech30th** [comment]
但是这样的话会导致内存压力陡增，我会加入一个用户可选项的

**Comment by AnotiaWang** [comment]
缓存在本地硬盘可行吗？好像 PixEz-Flutter 就是这么做的。设定一个缓存文件夹，然后在设置里加一个清除缓存的按钮

**Comment by AnotiaWang** [comment]
> 建议可以设置点击图片预览时显示的图片画质
>

这个呢

**Comment by dylech30th** [comment]
可以是可以，我以前就提供了两个手段，一个本地缓存一个内存缓存，之后因为感觉体验差距不大就删了(当时没想电脑上还要担心流量的问题)
我现在在直接用winui3重写整个pixeval的UI，到时候直接添加进去就好了，之后顺便把这些需求也给旧版本的pixeval里，win10+的可以用基于fluent design的新版本，win7可以用旧版本

**Comment by AnotiaWang** [comment]
好的，大佬辛苦了

**Comment by dylech30th** [comment]
很多bug早就该修的，但是因为考试不得不先放一放
暑假了就有时间了(

**Comment by Poker-sang** [comment]
在下一个版本中修复了
