### ISSUE TITLE
建议添加一键重试功能

### ISSUE THREAD

**Issue by AnotiaWang** [Pixeval/Pixeval#174]
批量下载图片的时候会出现 `Exceptional: An error occurred while sending the request` ，`The connection was closed before all data could be read` 以及状态卡在 `Downloading 0.00%` 之类的情况，建议添加一个一键重试的功能，谢谢！

**Comment by AnotiaWang** [comment]
还有……为啥会有下载完成的图片出现在“下载中”栏目下面
![image](https://user-images.githubusercontent.com/62269186/123774263-d4009480-d8ff-11eb-802e-b33a08b428ed.png)

**Comment by dylech30th** [comment]
这个我倒是没遇到过...下载完成自动就转移到下载后一栏了
至于重试的话，右边的那个按钮不就是重试嘛？

**Comment by AnotiaWang** [comment]
> 这个我倒是没遇到过...下载完成自动就转移到下载后一栏了
> 至于重试的话，右边的那个按钮不就是重试嘛？

 但是一百多张图片下载失败或者出问题，这谁点得过来😂我一个个点，点了几十张之后软件卡死了

**Comment by Poker-sang** [comment]
在下一个版本中修复了
