### ISSUE TITLE
直连开关是不是并没有用？

### ISSUE THREAD

**Issue by SuXi210** [Pixeval/Pixeval#175]
我自己测试无论是打开还是关闭直连这个选项，数据的请求都要通过一个IP为210.140.92.138的服务器,而且图片加载还很慢，只有我把梯子设置为全局模式的时候，这个IP的流量也会走我的梯子，同时也能做到秒加载图片。

**Comment by dylech30th** [comment]
因为这个IP就是P站图片服务器的IP啊

**Comment by SuXi210** [comment]
啊这，行吧我把这个加到规则里去，我还以为是你的中转服务器
