### ISSUE TITLE
ERR_CONNECTION_RESET at login screen.

### ISSUE THREAD

**Issue by MagicalDrizzle** [Pixeval/Pixeval#176]
The program displays the mentioned error message at launch even though I can access pixiv fine on my regular browser.
![Screenshot (6)](https://user-images.githubusercontent.com/49761211/125169326-dbfbe680-e1d3-11eb-984b-1eb0fec12c2a.png)

Opening the debug menu reveals this.
![Screenshot (5)](https://user-images.githubusercontent.com/49761211/125169290-aa831b00-e1d3-11eb-83ee-97f08efcbaa8.png)

**Comment by MagicalDrizzle** [comment]
Is this problem unsolvable? it's been a while with no response from you.

**Comment by Poker-sang** [comment]
Fixed
