### ISSUE TITLE
下载含多图的作品问题

### ISSUE THREAD

**Issue by AnotiaWang** [Pixeval/Pixeval#178]
软件版本：3.1.2、

复现步骤：找到一个包含多图的作品，右键下载

问题：新下载的图会覆盖前面的图，最后的效果就是文件管理器中只留下了一张图

**Comment by dryfishs** [comment]
可以在作品下载位置补上[{user.name}]{illust.id}_p{manga.index}.{illust.ext}，作品被覆盖是因为没有{manga.index}不能分p数，于是新图覆盖旧图。{manga.index}打出来的只是一个数字所以补个p，而_分开好看一点。

**Comment by AnotiaWang** [comment]
> 可以在作品下载位置补上[{user.name}]{illust.id}_p{manga.index}.{illust.ext}，作品被覆盖是因为没有{manga.index}不能分p数，于是新图覆盖旧图。{manga.index}打出来的只是一个数字所以补个p，而_分开好看一点。

谢谢
