### ISSUE TITLE
求助 这么一直在更新个人资料

### ISSUE THREAD

**Issue by maomaomi5** [Pixeval/Pixeval#179]
![LU)3F6K{0CN4ZE4B@O}KQG3](https://user-images.githubusercontent.com/71952204/126649865-d24cf4e9-66bc-483c-b263-f920e4a4962a.png)
我开了几个vpn也进不去

**Comment by maomaomi5** [comment]
前几天还登过一次

**Comment by Kulahala** [comment]
+1
