### ISSUE TITLE
打开的时候提示操作失败，怎么解？

### ISSUE THREAD

**Issue by dryfishs** [Pixeval/Pixeval#192]
打开会白屏等很久，然后提示the operation was canceled。重下也还是这样。什么问题

**Comment by dryfishs** [comment]
![image](https://user-images.githubusercontent.com/63152233/132974540-98a8c080-9db8-46dd-a9fd-41ac51aa7bbe.png)

**Comment by UmyNya** [comment]
+1

**Comment by dylech30th** [comment]
直连登录成功与否和你的网络运营商，登录时段以及登录地点都有很大关系，一次不成功可以换个时段多试几次，如果实在不行的话。就说明你的运营商，或者至少你当地的运营商限制的比较紧，就我所知移动就经常遇到这个问题，电信偶尔会遇到这个问题

**Comment by Potanzr** [comment]
我的也是这样，之前还能用来着今天突然就不行了一直白屏

**Comment by tianyun1114** [comment]
怎么样了，我从下午试到晚上都不行

**Comment by qingmozimeng** [comment]
我也是这个问题，而且挂梯子也不行

**Comment by dylech30th** [comment]
我也遇到这个问题了，等我找时间解决一下

**Comment by dylech30th** [comment]
是服务器问题，已经解决了
