### ISSUE TITLE
启动项目VS提示：该项目不知道如何运行配置文件 

### ISSUE THREAD

**Issue by luojunyuan** [Pixeval/Pixeval#193]
我使用2019 Clone了项目后，生成并还原了nuget包。Debug配置下点击运行VS弹窗提示我“该项目不知道如何运行配置文件 Pixeval”，已经将Pixeval设置为了启动项。并且已经安装了ProjectReunion和Windows App SDK (Experimental)扩展到VS2019中。

![image](https://user-images.githubusercontent.com/28323948/133245071-e80daee3-8a05-4489-86a8-321a282eaba9.png)

在尝试修改launchSetting.json 配置文件为“项目”启动后，提示外部错误，然后停止运行。

```
System.Reflection.TargetInvocationException:“Exception has been thrown by the target of an invocation.”
COMException: 没有注册类 (0x80040154 (REGDB_E_CLASSNOTREG))
```

我又尝试通过 dotnetCLI 工具(.Net6 p7) 运行项目，` dotnet run --project  .\Pixeval\Pixeval.csproj`

提示如下

```
无法应用启动配置文件“(默认值)”。
找不到可用的启动配置文件。
C:\Users\k1mlka\.nuget\packages\microsoft.projectreunion.winui\0.8.3\buildTransitive\Microsoft.Build.Msix.Packaging.targets(167,18): error MSB4086: 尝试在条件“'$(AppxUseResourceIndexerApi)' == '' AND '$(registry:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion@CurrentVersion)' < '6.3'”中对计算结果为“”而不是数字的“$(registry:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion@CurrentVersion)”进行数值比较。 [E:\k1mlka\Source\Repos\Pixeval\src\Pixeval\Pixeval.csproj]

生成失败。请修复生成错误并重新运行。
```

**Comment by dylech30th** [comment]
我忘记更新readme了，你要去vs商店下载一个叫Single-project MSIX packaging Tools for VS 2019的插件，接着在Build | ConfigurationManager里Pixeval项目勾选上Deploy，之后就可以调试了，我去更新一下readme
