### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by Kulahala** [Pixeval/Pixeval#196]
连接方主机无反应

**Comment by dylech30th** [comment]
#194

**Comment by ECHOXO1** [comment]
> #194重新下载了还是不行呀

**Comment by Kulahala** [comment]
> > #194重新下载了还是不行呀

我是没问题了

**Comment by ECHOXO1** [comment]
> > > #194重新下载了还是不行呀
> 
> 我是没问题了

我还是白屏QAQ

**Comment by ECHOXO1** [comment]
> > > #194重新下载了还是不行呀
> 

> > > #194重新下载了还是不行呀
> 
> 我是没问题了

我还是白屏QAQ

**Comment by ECHOXO1** [comment]
> > > #194重新下载了还是不行呀
> 
> 我是没问题了

怎么解决的勒

**Comment by Kulahala** [comment]
就重新下载，覆盖根目录




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月26日(星期天) 晚上10:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Pixeval/Pixeval] 出现错误 (#196)





    
#194重新下载了还是不行呀
   
我是没问题了
  
怎么解决的勒
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kulahala** [comment]
> > > > #194重新下载了还是不行呀
> > 
> > 
> > 我是没问题了
> 
> 怎么解决的勒

下载覆盖根目录
