### ISSUE TITLE
请进行reCAPTCHA认证

### ISSUE THREAD

**Issue by maki-nagisa** [Pixeval/Pixeval#204]
请进行reCAPTCHA认证
没有显示按钮 无法认证

**Comment by SettingDust** [comment]
遇到同样的问题，代理 Pixeval 无法打开登陆页面，不代理无法加载验证码

**Comment by haleina** [comment]
提示“请进行reCAPTCHA认证”
但是recaptcha的验证码弹不出来，
一直卡着不动

**Comment by Poker-sang** [comment]
如果下个版本出现可以重新打开这个议题
