### ISSUE TITLE
往下拉的时候上面就没了，拉到哪里加载到哪里，拉过的就没了要重新加载，很难受

### ISSUE THREAD

**Issue by eninra** [Pixeval/Pixeval#207]
是只有我一个是这样的么，给我一种加载贼慢的感觉

**Comment by LasmGratel** [comment]
软件是有意设计成这样的，用来节省内存。
以后会推出预加载功能等来提升流畅度，你也可以尝试改善网络环境

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: eninra ***@***.***>
Sent: Saturday, October 30, 2021 8:49:05 AM
To: Pixeval/Pixeval ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Pixeval/Pixeval] 往下拉的时候上面就没了，拉到哪里加载到哪里，拉过的就没了要重新加载，很难受 (Issue #207)


是只有我一个是这样的么，给我一种加载贼慢的感觉

―

**Comment by LIU1036** [comment]
你可以买个罗技的G502 XD

**Comment by LasmGratel** [comment]
在新版中会预加载之前的图片来解决这个问题。
