### ISSUE TITLE
无法打开软件一直提示需要安装Webview2 Runtime

### ISSUE THREAD

**Issue by EdA1574862** [Pixeval/Pixeval#210]
已经安装了Webview2 Runtime但是软件就是一直弹出需要安装，试过3.1.2、3.1.3版本都是这个问题

**Comment by banafish** [comment]
我一开始也是这样，然后放了几天又可以了哈哈哈，你可以重启电脑试一下

**Comment by dxsniyu** [comment]
我也有这个问题，请问你解决了么？

**Comment by knaxLFea** [comment]
请问您解决了吗

**Comment by dylech30th** [comment]
https://github.com/Pixeval/Pixeval/releases/tag/3.1.4
请前往Release界面下载该补丁版本，该版本修复了这个BUG
