### ISSUE TITLE
突然开始无法打开软件，毫无提示

### ISSUE THREAD

**Issue by bobolism** [Pixeval/Pixeval#211]
突然开始无法打开软件，什么提示也没有，只是在任务管理器里闪一下然后就没了

**Comment by dylech30th** [comment]
抱歉恢复完了(学生不是每天都有时间看)，请前往Release页面下载当前的最新版本

**Comment by bobolism** [comment]
那个...... 还是无法使用，即使是下载了3.1.4版本......依然是原来的状况
而且在一台新电脑上下载了软件，正常使用了几天后，居然又发生了同样的状况......

**Comment by dylech30th** [comment]
你可以尝试删除%localappdata%/pixeval试试
如果还是不行的话请前往事件查看器查找原因然后联系我

**Comment by bobolism** [comment]
辛苦了辛苦了，问题已经解决了，没想到竟然只是因为这个。非常感谢！
