### ISSUE TITLE
请问后期可否增加对Fanbox的支持？

### ISSUE THREAD

**Issue by 0o0miku0o0** [Pixeval/Pixeval#22]
大佬您好，请问后期可否增加对 Pixiv Fanbox 的支持，目前饭盒里的图片名称被进行了混淆加密，如果用批量存图工具存图，顺序会被打乱，不知道能否支持对饭盒图片的批量重命名下载，保持帖子名称及原有的图片顺序，谢谢~

**Comment by Rinacm** [comment]
这两天摸鱼摸完了就去写，我一直在打全境2(

**Comment by 0o0miku0o0** [comment]
这回复速度吓尿了

**Comment by Rinacm** [comment]
> 这回复速度吓尿了

挂的qq邮箱回复立马就能看到)

**Comment by Neubulae** [comment]
我还在好奇我咋会收到邮件，原来是Watch了
