### ISSUE TITLE
已安装.NET Core Runtime且为3.1+版本，但运行时还是提示必须安装.Net Core

### ISSUE THREAD

**Issue by KomeijiRan** [Pixeval/Pixeval#239]
![图片](https://user-images.githubusercontent.com/96311761/149452351-8a09d1c8-f58d-4a85-8657-51b9029974bc.png)
![图片](https://user-images.githubusercontent.com/96311761/149452399-1b0699b8-4b74-4bce-acde-6acf466bb347.png)

**Comment by dylech30th** [comment]
你要在官网安装Desktop Runtime，而不是普通的那个Runtime

**Comment by KomeijiRan** [comment]
> 你要在官网安装Desktop Runtime，而不是普通的那个Runtime

也安装了，但还是提示需要安装
![图片](https://user-images.githubusercontent.com/96311761/149608451-4fab8de3-63aa-49fb-b0d7-32323451123e.png)

**Comment by inory121** [comment]
你装的x86，现在电脑应该都是x64了吧

**Comment by KomeijiRan** [comment]
> 你装的x86，现在电脑应该都是x64了吧

![图片](https://user-images.githubusercontent.com/96311761/149951894-4bc26100-8d77-4612-907e-5df99cf4554d.png)
装了x64的，还是同样的提示

**Comment by dylech30th** [comment]
https://github.com/Pixeval/Pixeval/releases/tag/3.1.4
请前往Release页面下载对应你电脑架构的版本
