### ISSUE TITLE
能不能加个图片放大的功能

### ISSUE THREAD

**Issue by gushi233** [Pixeval/Pixeval#240]
在使用的时候需要预览大图，但是没有这个功能
直接看会很糊 无论2K 4K
首先要跳转到浏览器打开才行，我不想这么麻烦
谢谢

**Comment by dylech30th** [comment]
在新版本会加入，自己目前正在写
但是是学生党所以比较慢
可以在main分支查看当前开发进度

**Comment by Poker-sang** [comment]
最新版本已实现
