### ISSUE TITLE
关于搜索

### ISSUE THREAD

**Issue by mikoto10030** [Pixeval/Pixeval#241]
1.可以搜索特辑吗？
2.部分图片搜索不到，作品和原站相比有缺漏
3.搜索量太小，而且大概200页往后似乎就看不到了，对热门tag很不利

最后表达一下感激之情，让一个身无分文的学生党得以享受p站的部分会员功能。可惜我对毫无技术力只会复制黏贴(╥╯^╰╥)

抱歉，没看说明

**Comment by dylech30th** [comment]
1. 特辑可以浏览，但是暂时没法搜索(官方似乎也没有提供按照名字搜索特辑的功能？
2. 图片搜索不到是我漏写的，会在新版本写上去
3. 200页限制是官方API的限制

**Comment by dylech30th** [comment]
不管是网页端还是客户端，实际上最多能检索的图片都在5000-6000张左右，超出的部分是看不到的，你可以在P站的网页端试试，开会员可以从数据库里直接抓取排名靠前的作品，但是如果没有会员的话排序就只能在默认返回的前5000张中排序

**Comment by dylech30th** [comment]
唔，我刚刚去看了一下，P站的策略似乎改了，WebAPI不限制数量了
我会在新版本了加入AppAPI和WebAPI切换的选项的

**Comment by mikoto10030** [comment]
非常感谢回复，明白啦     
看了一下，特辑搜索是pixivision的功能，本站确实不行。期待之后的皇家版pixeval（doge）
