### ISSUE TITLE
最近pixeval启动不了

### ISSUE THREAD

**Issue by Mingyefengxu** [Pixeval/Pixeval#242]
双击pixeval打开没有反应，管理员运行也是。是新版本。

**Comment by dylech30th** [comment]
确保是下载的3.1.4版本吗(Release页面)
如果依然打不开可以去事件管理器看看是怎么回事

**Comment by catboxLL** [comment]
同样无法打开 3.1.3时用了一段时间后 就突然开不了了 更新了3.1.4后还是存在问题
刚运行时能在任务管理器里看见 但马上又关了
.NET Core SDK有安装的

**Comment by Btszy** [comment]
双击后没反应，启动动画都没有，任务管理器里出现了直接闪退了，最新版本也打不开

**Comment by iPixelOldC** [comment]
+1 我也用不了。不过我这里也是连不上，我电脑代理也是清空了（本来也没开），环境变量窗口里面也没有代理的环境变量。至于Pixiv，我是路由器上的代理，所以访问是没有问题（网络诊断也是没有任何问题）
报错是：
嗯… 无法访问此页面已重置连接。ERR_CONNECTION_RESET

想知道日志去哪里看

**Comment by konoaxiao** [comment]
解决了吗，同样打不开，双击后没反应
