### ISSUE TITLE
webview2runtime安装时闪退

### ISSUE THREAD

**Issue by knaxLFea** [Pixeval/Pixeval#243]
当进度条出现“正在安装Microsoft Webview2 Runtime”时会闪退，重启也依然闪退，请问我该怎么解决呢

**Comment by dylech30th** [comment]
这是WebView2 Runtime的问题，你可以前往[WebView2 Feedback](https://github.com/MicrosoftEdge/WebView2Feedback/issues)来反馈这个问题，这不是本项目能够解决的
