### ISSUE TITLE
图片列表上下滚动时图片才加载进来, 能不能预渲染一部分, 让滚动时直接显示加载好的图片.

### ISSUE THREAD

**Issue by Akise** [Pixeval/Pixeval#247]

**Comment by dylech30th** [comment]
这是为了节省内存做的考虑，在正在开发的WinUI3分支中已经加入了这个选项，但是还没完成开发（学生党空闲时间不多）
基于WPF的Pixeval开发优先度要比新版低，所以如果要应用到WPF上可能要等到我把WinUI 3的branch开发完

**Comment by Akise** [comment]
我也在看winui3, 试了下不能非打包(非应用商店)运行, 可能功能还没完善? @dylech30th

**Comment by dylech30th** [comment]
打包项目也可以sideload呀，因为这个codebase一开始就是使用的打包的winui3项目模板，非打包的缺太多feature，bug也更多
