### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by FengQwQ233** [Pixeval/Pixeval#249]
![image](https://user-images.githubusercontent.com/95861883/153824263-1402dd6e-0e45-4cfa-a7ef-a8cb99eb472d.png)
点击以下四个选项都没有反应
![image](https://user-images.githubusercontent.com/95861883/153824526-d3f33b61-0b16-4b37-8737-8096691c6795.png)
di点击Google后弹出第二张图已经挂梯子可以正常访问YouTube

**Comment by dylech30th** [comment]
这是个人网络环境问题，不行的话只能挂梯子，有些地方的运营商策略要比别的地方更加严格一些，我无法解决

**Comment by FengQwQ233** [comment]
在 2022年2月15日星期二，Dylech30th ***@***.***> 写道：是net套件没有更新不是网络问题

**Comment by dylech30th** [comment]
不同原因可能会造成同一种问题，像这种pixiv的登录页面都已经弹出来了，登录框却加载不出来的原因就是很单纯的网络问题了

**Comment by FengQwQ233** [comment]
还是要感谢项目组谢谢

取得 Android 版 Outlook<https://aka.ms/AAb9ysg>
________________________________
