### ISSUE TITLE
Appleid登录出现错误

### ISSUE THREAD

**Issue by xxnuo** [Pixeval/Pixeval#250]
使用Apple id认证完成后登录出现错误：421 Misdirected Request nginx

Windows [版本 10.0.22000.526]
Pixeval 3.1.4
Microsoft Edge WebView2 Runtime 98.0.1108.56
Clash 0.19.8 Global Proxy

![截图](https://user-images.githubusercontent.com/54252779/154828413-d53575df-6314-46d5-8d6d-43f744a8b553.png)

**Comment by BigTear** [comment]
Windows [版本 10.0.22000.526]
Pixeval 3.1.4
Microsoft Edge WebView2 Runtime 98.0.1108.56

**Comment by Poker-sang** [comment]
如果下个版本出现可以重新打开这个议题
