### ISSUE TITLE
搜图最多只能有200页(？)

### ISSUE THREAD

**Issue by qbs233** [Pixeval/Pixeval#254]
一次搜索100页，从第一页开始搜的全，改为从第100页开始也能搜到，从200开始，无论搜什么都搜不到了。

**Comment by dylech30th** [comment]
P站APP端API限制是这样的，最多只能搜索那么多，但是WEB API没有这个限制，我现在在写的重构之后的版本里有计划给用户自定义切换APP API和WEB API的选项
