### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by nUser0** [Pixeval/Pixeval#255]
按提示下载安装 .net core 之后，仍然提示找不到，重启电脑后依然如此，用管理员身份运行仍然如此。
另：我是win11系统。

**Comment by dylech30th** [comment]
你确定安装的是.NET Desktop Runtime嘛？

**Comment by dylech30th** [comment]
如果是.NET Core 3.1的话，要安装[Desktop Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.23-windows-x64-installer)
如果是.NET 5及以后的版本就直接普通的Runtime就可以了

**Comment by nUser0** [comment]
您好！
       我又仔细看了看弹出的网页，确实是我安错了（安了第一个，应该是第二个）。
       非常感谢您的回复！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月25日 18:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Pixeval/Pixeval] 无法启动 (Issue #255) |

你确定安装的是.NET Desktop Runtime嘛？

**Comment by nUser0** [comment]
OK!知道啦！谢谢了！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月25日 18:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Pixeval/Pixeval] 无法启动 (Issue #255) |

如果是.NET Core 3.1的话，要安装Desktop Runtime
如果是.NET 5及以后的版本就直接普通的Runtime就可以了
