### ISSUE TITLE
图片保存位置变成了图片的保存名字 后一张覆盖前一张

### ISSUE THREAD

**Issue by HierarchP** [Pixeval/Pixeval#263]

**Comment by RoxyKko** [comment]
你试试看把设置里面保存路径改成：....(你的保存路径）\{if:spot:{spot.title}}\{if:manga:{illust.title}}\{illust.title}{if:manga:_{manga.index}}.{illust.ext}
![image](https://user-images.githubusercontent.com/86786320/166141133-71ce42dc-be5f-47b4-b105-d29b1acd8281.png)

**Comment by dylech30th** [comment]
我写了一个初衷很好但是用起来很狗血的宏，所以下载路径可能会被搞出点莫名其妙的bug
等现在手头写的版本会换成一个更人性化的系统，然而因为上学所以可能会拖得比较慢: (

**Comment by n0099** [comment]
建议直接lisp
