### ISSUE TITLE
改过p站密码pixeval就再也上不去了

### ISSUE THREAD

**Issue by qingmozimeng** [Pixeval/Pixeval#266]
忘了p站密码改了一下就再也上不去了，一直在转圈圈，挂梯子也没用，把密码改回去也没用，重装pixeval也没用

**Comment by dylech30th** [comment]
可以手动删除%localappdata%/pixeval
这是老版本的一个bug，主要是因为老版本是解压即用的，没有什么重装/安装机制，删掉本地以后配置文件是没有被删的
