### ISSUE TITLE
已经安装了.NET Core 3.1 Runtime，但是没有扫描到

### ISSUE THREAD

**Issue by chuanhezi** [Pixeval/Pixeval#270]
已经安装了.NET Core 3.1 Runtime，但是没有扫描到

**Comment by CresLeaf** [comment]
.NET Core 3.1 Runtime 和 .NET Core 3.1 Desktop Runtime 是两个东西
~~SB MS~~

**Comment by chuanhezi** [comment]
![image](https://user-images.githubusercontent.com/108390112/190406198-50054c74-fe24-48b1-93c5-031bba0114e4.png)
我不懂你在叫什么，流汗黄豆

**Comment by n0099** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.29-windows-x64-installer

**Comment by chuanhezi** [comment]
这两个我都有怎么说

**Comment by n0099** [comment]
试试32位版本

**Comment by RoxyKko** [comment]
我好像有记忆，我很久以前也遇到过，要下特定的3.1.10，你可以试试看
![image](https://user-images.githubusercontent.com/86786320/203940951-0025ba5c-5645-4a66-b9bf-73c13312a040.png)

**Comment by o5-null** [comment]
为什么必须装特定的 3.1.10版本啊！

**Comment by zwx08** [comment]
.NET Core 3.1 Desktop Runtime (v3.1.32) - Windows x64 Installer 是可以的

**Comment by n0099** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-3.1.10-windows-x64-installer

**Comment by inory121** [comment]
![image](https://github.com/Pixeval/Pixeval/assets/35392664/e162f15d-cf8c-4bec-bd20-04d43aa94fa3)
https://dotnet.microsoft.com/zh-cn/download/dotnet/3.1
安装桌面运行时，32位选x86，64位选x64，版本应该只要是3.1就行，不一定要3.1.10，我装的最新的3.1.32也可以
