### ISSUE TITLE
3.1.4检测不到WebView2

### ISSUE THREAD

**Issue by kkmnsk** [Pixeval/Pixeval#276]
3.1.4检测不到WebView2

**Comment by Poker-sang** [comment]
参考一下这个方案<https://answers.microsoft.com/zh-hans/microsoftedge/forum/all/%E5%B7%B2%E5%AE%89%E8%A3%85%E4%BD%86%E6%A3%80/0f8a5284-ea9f-42eb-91fc-790a9bf57fd2>
