### ISSUE TITLE
关于选用的UI框架, 为何不使用MAUI开发新版本?

### ISSUE THREAD

**Issue by Akise** [Pixeval/Pixeval#302]
### 建议类型

新功能

### Pixeval的版本

WinUI3

### 描述

关于选用的UI框架, 为何不使用MAUI开发新版本?
MAUI跨平台优势不是更好?

**Comment by dylech30th** [comment]
因为MAUI暂时还是不是很成熟，文档不全，而且很多地方的学习成本相比起WinUI3要高
更重要的是当我最开始决定重写的时候，MAUI甚至还没preview，他preview的时候我都写一半了
