### ISSUE TITLE
可不可以在自定义宏中添加包含作品tag的功能

### ISSUE THREAD

**Issue by qbs233** [Pixeval/Pixeval#303]
### 建议类型

新功能

### Pixeval的版本

WinUI3

### 描述

可不可以在自定义宏中添加包含作品tag的功能，下载的能容太多不太方便分类了。。

**Comment by dylech30th** [comment]
可以。另：如果有能力的话可以尝试去提交这个功能的代码，有关每个宏的代码位于[src/Pixeval/Download/Macros](https://github.com/Pixeval/Pixeval/tree/main/src/Pixeval/Download/Macros)
