### ISSUE TITLE
有快捷前进后退的鼠标键没有反应

### ISSUE THREAD

**Issue by sybsub** [Pixeval/Pixeval#305]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述
没有返回前进功能
鼠标上的后退键点击没有反应，要鼠标滚动到顶部点击后退才能返回，比较影响体验。
 还有一个问题是鼠标滚动时页面滑动太慢，鼠标滚动半圈，页面才动一点，希望能优化下

**Comment by Poker-sang** [comment]
* 主页面的`NavigationView`没有返回前进键是故意如此设计的，可能是因为页面缓存比较耗内存？
* 子页面返回功能的鼠标快捷键肯定会加上的【
* 第三个问题我好像没有发现？是不同鼠标灵敏度的问题吗，如果是以后可以加个设置项【

**Comment by Poker-sang** [comment]
目前软件没有后退的操作，所以暂时关闭这个issue，如果以后加回返回功能，很容易可以实现鼠标侧键
