### ISSUE TITLE
图片无法加载问题

### ISSUE THREAD

**Issue by SALIGIA080** [Pixeval/Pixeval#313]
可运行，可登录，经排查发现无Watt Toolki（steam++）干扰，之前可正常查看图片，最近发现所有图片无法加载或进度条静止或无法点开图片，包括头像，收藏夹，特辑等，文字加载正常，重新删除下载问题保留，开启直连或者梯子问题保留，实在没辙了，求大佬解答
<img width="1181" alt="3" src="https://github.com/Pixeval/Pixeval/assets/134821204/415e58a0-b737-47fb-9182-f40bcf753eb3">
<img width="971" alt="屏幕截图 2023-05-28 103400" src="https://github.com/Pixeval/Pixeval/assets/134821204/fb1a5d62-0453-450b-938c-e077f2a3f0a3">
<img width="751" alt="屏幕截图 2023-05-28 104455" src="https://github.com/Pixeval/Pixeval/assets/134821204/e66bbae8-a68f-48c5-95c7-8e761012aa82">

**Comment by dxsniyu** [comment]
+1

**Comment by qbs233** [comment]
+1

**Comment by louvyu** [comment]
+1

**Comment by YueGAMI** [comment]
+1

**Comment by HSJoke** [comment]
同样有这个问题，无意中尝试了一下以前没删掉的1.2.0发现这个旧版的反而没这个问题

**Comment by SALIGIA080** [comment]
> 同样有这个问题，无意中尝试了一下以前没删掉的1.2.0发现这个旧版的反而没这个问题

我试试，重下的都是3.1版本往上的，都寄了，没想到1.2.0竟然还能用（摆烂）

**Comment by louvyu** [comment]
试了一下直到1.4.0都能正常使用用，1.5.0到1.9.0都无法登录。2.0.0到2.2.5都闪退，3.1以上的看不到图

**Comment by louvyu** [comment]
> 试了一次直到1.4.0都能正常使用，1.5.0到1.9.0都无法登录。2.0.0到2.2.5都闪退，3.1以上的看不到图

补充一下1.1.0也看不到图，而且好像没有关闭免代理模式选项。1.0.1关闭免代理模式科学上网可以看到图

**Comment by louvyu** [comment]
> > 试了一次直接到1.4.0都能正常使用，1.5.0到1.9.0都无法登录。2.0.0到2.2.5都闪退，3.1以上的看不到图
> 
> 补充一下1.1.0也看不到图，而且好像没有关闭免代理模式选项。1.0.1关闭免代理模式科学网上可以看到图

**Comment by Poker-sang** [comment]
已经在最新Release 3.1.5中修复【
