### ISSUE TITLE
图片加载不出来。

### ISSUE THREAD

**Issue by zeroky112** [Pixeval/Pixeval#314]
### Pixeval's version

WinUI3

### Description of the problem

老大，3.13版本在20多号的时候突然加载不出来图了，全是白的。

### Screenshot

![image](https://github.com/Pixeval/Pixeval/assets/134947791/9050c6ef-3fce-4350-9374-8f6ac5b2051a)
![image](https://github.com/Pixeval/Pixeval/assets/134947791/56d1c4e3-5a09-47a4-b398-0aea1cd3992f)

### Windows major version

Windows 10

**Comment by zheisengs** [comment]
我也有这个问题

**Comment by louvyu** [comment]
貌似现在3.1版本往上的都有这个问题，1.2版本的现在还没这个问题

**Comment by Poker-sang** [comment]
与 #313 重复
