### ISSUE TITLE
最新版本exe文件遇到的.NET Core问题

### ISSUE THREAD

**Issue by Howard-WU-Ark** [Pixeval/Pixeval#317]
### Pixeval's version

WinUI3

### Description of the problem

release中的3.15版本，解压后（在F盘）打开时报错。
已经安装了.NET 7,也从官网上下了.Net Core的7.05版本并安装，没有解决问题

### Screenshot

![1685963122](https://github.com/Pixeval/Pixeval/assets/84512616/18583833-243d-422c-8d47-c4057a8aeb8d)

### Windows major version

Windows 10

**Comment by Poker-sang** [comment]
3.1.5需要的是.net core 3.1.32，不是.net7

下一个版本会在.net7或者.net8发布
