### ISSUE TITLE
可不可以在设置里加一个恢复默认设置的功能

### ISSUE THREAD

**Issue by wld123** [Pixeval/Pixeval#321]
### 建议类型

新功能

### Pixeval的版本

WinUI3

### 描述

我改下载路径之前忘了复制后面的宏了，然后现在怎么都改不回去了，没法好好存图- -
实在不好意思- -

**Comment by wld123** [comment]
没事了，我退出账号重新登陆一下就可以了。谢谢

**Comment by Poker-sang** [comment]
下一个版本已经加入此功能
