### ISSUE TITLE
pixeval无法加载

### ISSUE THREAD

**Issue by sabibushiwo** [Pixeval/Pixeval#325]
### Pixeval's version

WinUI3

### Description of the problem

pixeval可以登入但图片加载不出来，

### Screenshot

<img width="1280" alt="image" src="https://github.com/Pixeval/Pixeval/assets/138269139/696a516e-9dc1-4caf-bc13-e6eef33e629f">

### Windows major version

Windows 11

**Comment by Poker-sang** [comment]
版本号是多少

**Comment by sabibushiwo** [comment]
> 

3.1.4,应该是这个吧

**Comment by Poker-sang** [comment]
可以试试3.1.5

**Comment by Poker-sang** [comment]
要是没有问题的话我就关闭了喔

**Comment by sabibushiwo** [comment]
> 要是没有问题的话我就关闭了喔
 
解决了，谢谢，关了吧
