### ISSUE TITLE
登出复选框+解压建议+版本号

### ISSUE THREAD

**Issue by gbwhisper** [Pixeval/Pixeval#327]
### 建议类型

新功能

### Pixeval的版本

WinUI3

### 描述

1，增加登出复选框，减少误触；
2，软件解压如图增加合并同名文件夹说明，否则搜索功能无法正常运行；
3，3.1.5版本安装后显示仍为3.1.4
4，下载与历史进度卡住时，建议增加刷新未完成下载项的功能，否则只能一张张点击了。

### 图片

![ss](https://github.com/Pixeval/Pixeval/assets/138815633/f031dcff-671c-440f-a0f6-cc1fd922a78e)

**Comment by Poker-sang** [comment]
这些问题在还未发布的下一个版本都已经修复了x谢谢反馈！
