### ISSUE TITLE
3.1.5提示需要安装webview2 runtime

### ISSUE THREAD

**Issue by reimu-Linmo** [Pixeval/Pixeval#328]
### Pixeval's version

WinUI3

### Description of the problem

实际是安装了的（版本为114.0.1823.79
3.1.4没有这个问题，但无法显示图片

### Windows major version

Windows 10

### Specific Windows version

May 2021 Update/21H1 (19043)

**Comment by Poker-sang** [comment]
参考这个方案解决一下试试看呢<https://answers.microsoft.com/zh-hans/microsoftedge/forum/all/%E5%B7%B2%E5%AE%89%E8%A3%85%E4%BD%86%E6%A3%80/0f8a5284-ea9f-42eb-91fc-790a9bf57fd2>

**Comment by reimu-Linmo** [comment]
已解决，非常感谢
