### ISSUE TITLE
图片搜索不全/作品不予显示

### ISSUE THREAD

**Issue by gbwhisper** [Pixeval/Pixeval#330]
### Pixeval的版本

WinUI3

### 问题描述

比如搜索ai作者ricotte的作品，pixeval上给出的搜索结果不全（如截图ss）。单独搜索作品，pixeval能识别出是哪个作者的，但是会出现“无法显示”的提示（如截图ss2）。试了下其他作者也存在大量这类问题。

### 屏幕截图

![ss](https://github.com/Pixeval/Pixeval/assets/138815633/456d2de4-603a-4045-b4bd-661cf3711f8f)
![ss2](https://github.com/Pixeval/Pixeval/assets/138815633/75d71a73-1347-44a0-832c-c7be3c0a201b)

### Windows主要版本

Windows 11

### 具体Windows版本

Windows 11 21H2 (22000)

**Comment by gbwhisper** [comment]
截图左侧使用的是一个叫Pixevel的网页。一字之差，不是同一个东西。
（有趣的是，这个网页也存在漏图的情况，比如搜索某作者的作品瀑布流会遗漏几张图。比如109639059这张，单搜能搜到也能显示，但是瀑布流里没有。）

**Comment by Poker-sang** [comment]
我去对比了一下旧版确实有漏图问题，不过你的网页的那个好像也有漏图

不过我用新版看了一眼没有漏图，应该解决了

![image](https://github.com/Pixeval/Pixeval/assets/62325494/c0c8793b-9e3e-46dd-bd5d-8b54a1af9a03)

![image](https://github.com/Pixeval/Pixeval/assets/62325494/e135f454-3ffa-4446-9650-0816eece38c1)

**Comment by gbwhisper** [comment]
> 

天哪，看起来超棒！期待一下，不如说我等不及要用了：）

**Comment by Poker-sang** [comment]
还有不少没写完，尽量在这两个月完成吧

**Comment by Poker-sang** [comment]
在下一个版本中修复了
