### ISSUE TITLE
Pixeval在时间线中的显示

### ISSUE THREAD

**Issue by Roy-QQB-Huang** [Pixeval/Pixeval#331]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

如何关闭Win10中Pixeval在时间线中的显示。
可以加一个开关吗？
谢谢！！！

### 图片

![image](https://github.com/Pixeval/Pixeval/assets/82002109/31433328-7200-4761-9d0c-f2e730ed828b)

**Comment by Poker-sang** [comment]
下一个版本这个功能被ms自动阉割了
