### ISSUE TITLE
R-18标签显示

### ISSUE THREAD

**Issue by Roy-QQB-Huang** [Pixeval/Pixeval#332]
### 建议类型

新功能

### Pixeval的版本

WinUI3

### 描述

可以做一个Pixiv那种，当图片有R-18标签时，左/右上角显示的功能吗。

### 图片

![IMG_20230722_100808](https://github.com/Pixeval/Pixeval/assets/82002109/a25f9456-0182-4640-9554-6dec12521a48)

**Comment by Poker-sang** [comment]
下一个版本已加入该功能

![image](https://github.com/Pixeval/Pixeval/assets/62325494/e135f454-3ffa-4446-9650-0816eece38c1)
