### ISSUE TITLE
求教作者大大

### ISSUE THREAD

**Issue by bhercules** [Pixeval/Pixeval#333]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

重装了一次电脑后下载的保存路径怎么也调不回我原来的设置，电脑小白试了半天那个宏也没搞好，想问下该怎么设置宏才能把保存路径变成我原来那样：单图保存为作者名加作品id，多图自动建一个作品名的文件夹，里面的图片名为作者名加作品id加图片序号

**Comment by bhercules** [comment]
对了，关键问题在于我可以单独做到单图的保存路径或者多图的保存路径，但是没法让这俩同时存在，单图保存设置对了多图的就错了，多图的对了单图的就错了

**Comment by Poker-sang** [comment]
3.1.5及之前的版本（WPF版本）中，默认的路径宏是`"*你的图片文件夹*\{if:spot:{spot.title}}\{if:manga:{illust.title}}\{illust.id}{if:manga:_p{manga.index}}.{illust.ext}"`，路径宏通过{if:spot:xxx}和{if:manga:xxx}来根据条件，对特辑或者多图的图片指定保存路径
