### ISSUE TITLE
改善搜索结果 / fix incomplete search result

### ISSUE THREAD

**Issue by gbwhisper** [Pixeval/Pixeval#337]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

7月时反映了用Pixeval搜图结果不全的问题。比如小野智（ID：87046707）的图，用Pixeval搜出来的结果和实际作者更新的图差异很大，不知道是卡在哪个步骤上了。
前两天看程序大大好像说最近很忙，所以新的版本发布会比大家预想中的晚很多。现在就是想建议先把搜图不全的问题解决发布一个小更新？

Trying to report the bug in English. Pixecal always misses many artwork results (i.e iD 87046707) when searching in mainland China. Not sure if it's caused by the network. A update would be great before the next major update. Thank you.

**Comment by Poker-sang** [comment]
在下一个版本中修复了
