### ISSUE TITLE
無法加載 [reCAPTCHA] 認證界面

### ISSUE THREAD

**Issue by EVOLUTION-CIAO** [Pixeval/Pixeval#338]
### Pixeval的版本

WinUI3

### 问题描述

無法加載 [reCAPTCHA] 認證界面
可能pixeval這個登錄界面強制使用了軟件自帶的直連
導致我即使能在瀏覽器正常加載 [reCAPTCHA] 認證界面，但在這裡不行

### 屏幕截图

![image](https://github.com/Pixeval/Pixeval/assets/97382367/f3a471d3-17ca-49d0-817e-d0d685017d1a)

### Windows主要版本

Windows 10

**Comment by Sky076** [comment]
+1

**Comment by Poker-sang** [comment]
下一个版本中允许通过外部浏览器登录，可以彻底解决这个问题

**Comment by youlan2333** [comment]
+1

**Comment by gfe20010** [comment]
+1

**Comment by Poker-sang** [comment]
如果下个版本出现可以重新打开这个议题

**Comment by Poker-sang** [comment]
emm那个禁用直连的togglebutton，禁用时使用系统代理，不禁用使用直连，切换的时候需要重启app，再测试试试呢？

**Comment by Poker-sang** [comment]
如果直接用浏览器没有这个问题的话，要不试试重装一下[webview](https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/?form=MA13LH)？如果你的webview是很早之前装的有可能可以这样解决。

**Comment by Poker-sang** [comment]
确实是，这个功能没改，我也发现了，你可以开一个新的issue

**Comment by youlan2333** [comment]
![image](https://github.com/Pixeval/Pixeval/assets/64688148/23e54883-e9b3-4456-8e60-b477106be35f)
![image](https://github.com/Pixeval/Pixeval/assets/64688148/7f3a9027-2e80-4bdb-b4aa-4673dde112ce)

新版本还是不行，图一不勾选禁用前域直连，图二勾选禁用前域直连

**Comment by youlan2333** [comment]
我貌似登录上了，点击软件中的登录按钮，左侧一闪而过的继续使用此账号，接着就回到了登录页面

**Comment by youlan2333** [comment]
> > 新版本还是不行，图一不勾选禁用前域直连，图二勾选禁用前域直连
> 
> 试试重装webview

我使用了webview2中的修复功能，问题还在，是否要强制删除重装？

**Comment by Poker-sang** [comment]
可以试一下，我也不确定是否能解决问题

一闪而过是登录脚本的行为，你如果在右侧不输入账号密码直接登录，他就不会自动跳转了

**Comment by Poker-sang** [comment]
它登录用的网址和网页用的不一样，所以会出现差别

**Comment by youlan2333** [comment]
怪，我用geekunins强制删除webview2之后，发现怎么装也装不回去了，一气之下更新了Win11，打开软件发现可以成功登录了

**Comment by Poker-sang** [comment]
噗这么吓人，看来以后不能让人强制卸载了

webview这个问题确实很奇怪，我身边的win10，win11电脑都没遇到这个bug，这个也肯定只是webview的bug

**Comment by youlan2333** [comment]
> 噗这么吓人，看来以后不能让人强制卸载了
> 
> webview这个问题确实很奇怪，我身边的win10，win11电脑都没遇到这个bug，这个也肯定只是webview的bug

(T_T) 另外我发现拖动窗口的时候，窗口中的内容会抖动，这算是bug吗？

**Comment by Poker-sang** [comment]
我没发现这个问题啊，可能是bug吧。如果所有窗口里面所有内容都会这样，是那应该是winui的bug我没法修

**Comment by youlan2333** [comment]
> 我没发现这个问题啊，可能是bug吧。如果所有窗口里面所有内容都会这样，是那应该是winui的bug我没法修

不是的，我发现QQ没问题，资源管理器没问题，只有pixeval会出现这种情况

**Comment by Poker-sang** [comment]
那两个用的都不是winui，你可以试试文件资源管理器有没有这个情况

**Comment by youlan2333** [comment]
> 那两个用的都不是winui，你可以试试文件资源管理器有没有这个情况

就是文件资源管理器没有问题，移动很平滑=_=

**Comment by youlan2333** [comment]
> 那两个用的都不是winui，你可以试试文件资源管理器有没有这个情况

就是类似于小掉帧的情况

**Comment by Poker-sang** [comment]
这样你先试试用两天，如果一直会有这种问题再开个issue吧

**Comment by youlan2333** [comment]
> 这样你先试试用两天，如果一直会有这种问题再开个issue吧

嗯，好的，就是这个不怎么好提issue，因为我用录屏软件录不出来那种掉帧的感觉

**Comment by ningyuannightware** [comment]
我的问题解决了，我先“禁用时使用系统代理”，有登录账号的信息但是报错闪退，之后再使用“不禁用使用直连”就可以登录上了。

**Comment by n0099** [comment]
v

**Comment by Poker-sang** [comment]
这个issue和#198没关系

**Comment by EVOLUTION-CIAO** [comment]
![圖片_2024-05-09_012902741](https://github.com/Pixeval/Pixeval/assets/97382367/dcca7c62-eac4-4da8-9563-7f768d405628)
![圖片_2024-05-09_012917296](https://github.com/Pixeval/Pixeval/assets/97382367/f0d3660e-e9a9-49d7-af33-f69f974f2f4f)
我今天新裝4.1.2 x64版本 登錄後進人機認證頁面就報錯然後被強退軟件（之前有次運氣好沒認證就能進去，這讓我能夠迴避問題持續到我新裝系統時候）

**Comment by EVOLUTION-CIAO** [comment]
![image](https://github.com/Pixeval/Pixeval/assets/97382367/b29502f1-719c-4ec6-8016-3ee56f61cfaf)
![image](https://github.com/Pixeval/Pixeval/assets/97382367/779dd161-1fb2-4831-8742-fab16192285e)
我今天新裝4.1.2 x64版本 登錄後進人機認證頁面就報錯然後被強退軟件（之前有次運氣好沒認證就能進去，這讓我能夠迴避問題持續到我新裝系統時候）

**Comment by EVOLUTION-CIAO** [comment]
![image](https://github.com/Pixeval/Pixeval/assets/97382367/1e7bbb32-ab90-4090-b3eb-ec17baefe304)
![image](https://github.com/Pixeval/Pixeval/assets/97382367/5cc8ef41-39f8-49d0-988c-95998932bca7)
我今天新裝4.1.2 x64版本 登錄後進人機認證頁面就報錯然後被強退軟件（之前有次運氣好沒認證就能進去，這讓我能夠迴避問題持續到我新裝系統時候）

**Comment by EVOLUTION-CIAO** [comment]
額，非常神秘的是這個新問題被我在加載人機驗證頁面的時候不停[右鍵]-[返回上一頁]-[右鍵]-[刷新]-[右鍵]-[返回上一頁]-[右鍵]-[刷新]...
這樣解決了....

**Comment by Poker-sang** [comment]
我看你好像禁用了前域直连，如果禁用的话就只能通过你自己的网络环境登录了

**Comment by EVOLUTION-CIAO** [comment]
> 我看你好像禁用了前域直连，如果禁用的话就只能通过你自己的网络环境登录了

是的，因為我前面試了一次發現網頁還是不加載 RECAPTCHA 小窗口，登了一次失敗我就用自己網絡了，然後就出現剛才的問題但又莫名其妙解決了

**Comment by Poker-sang** [comment]
请问你的系统是win10吗，我发现大部分出现不加载recaptcha问题的都是win10( •̥́ ˍ •̀ू )

另外下个版本可以通过外部浏览器登录，也许不会再被recaptcha卡登录了。不过现在的pixeval会自动保存refresh token，所以几乎再也不会出现要求重新登陆的问题了(*￣з￣)

**Comment by EVOLUTION-CIAO** [comment]
是的我現在使用的仍舊是win10，另外我現在在試用改下載參數的時候已經閃退幾次了，新版的過渡動效有點多，（這很win11）從觀感上我會感覺佔用會比之前老版本大，右鍵出來的選項【下載】沒有排到顯眼的地方有點頭疼，彈窗也不是秒出有個動畫，雖然我看到設置裡面有[喜歡自動下載]選項
希望之後設置裡面能出個 關閉應用內動效 的選項（還是我沒找到？）

**Comment by Poker-sang** [comment]
抱歉动效这个是框架自带的，关闭不了，但应用占用高也不是动效导致的，只是因为这个框架还不成熟，所以就算关闭也没有什么用处

以后我可以把缩略图右键的保存选项排到第一个位置。但如果是详情页，保存推荐使用上方或下方工具栏，而非右键菜单

如果遇到闪退可以看看日志文件夹内（可以在设置页找到）有没有相关记录，如果有，那大概率我们可以解决，否则就不好办了

另外当前版本好像有一个会删除下载所在文件夹的bug，所以最好保证下载文件夹为空或没有重要文件】(。•ω•。)ノ♡

**Comment by EVOLUTION-CIAO** [comment]
> 抱歉动效这个是框架自带的，关闭不了，但应用占用高也不是动效导致的，只是因为这个框架还不成熟，所以就算关闭也没有什么用处
> 
> 以后我可以把缩略图右键的保存选项排到第一个位置。但如果是详情页，保存推荐使用上方或下方工具栏，而非右键菜单
> 
> 如果遇到闪退可以看看日志文件夹内（可以在设置页找到）有没有相关记录，如果有，那大概率我们可以解决，否则就不好办了
> 
> 另外当前版本好像有一个会删除下载所在文件夹的bug，所以最好保证下载文件夹为空或没有重要文件】(。•ω•。)ノ♡

【会删除下载所在文件夹的bug】是的這個我遇到了，默認位置文件夾被移到回收站了，應該是不能使用應用內【下載記錄頁面的刪除圖片記錄】（我在觸發這個bug的時候文件夾內沒有我要刪除的圖片）

**Comment by Poker-sang** [comment]
因为下载失败了所以里面没有图片，也是因为下载失败才删除了文件夹，下一个版本会先判断文件夹是否为空，再删除

下载失败和闪退也可能是因为网络状况不太好？

**Comment by EVOLUTION-CIAO** [comment]
> 因为下载失败了所以里面没有图片，也是因为下载失败才删除了文件夹，下一个版本会先判断文件夹是否为空，再删除
> 
> 下载失败和闪退也可能是因为网络状况不太好？

我當時只是想刪除下載記錄

個人觀點，軟件只提供刪除【下載記錄】是風險最低的，想方便用戶，再進一步加個【打開下載文件夾】和【複製當前選擇的下載文件PID】就夠了，畢竟舊版都沒有我也不奢求有，除了誤觸到【下載當前目錄所有圖片】的特殊情況可能需要這功能，【刪除下載文件】這种高風險的事，還是交給用戶自己在資源管理器操作就好
（好吧，打完突然想到可能有些人不會按時間排序文件）

**Comment by yakumo2333** [comment]
reCAPTCHA是谷歌的人机验证图片，加载不出来可能是浏览器缺少相关插件有关，用浏览器登录装个Gooreplacer插件就可以了，但软件不知道要怎么搞.🤦‍

**Comment by EVOLUTION-CIAO** [comment]
> 抱歉动效这个是框架自带的，关闭不了，但应用占用高也不是动效导致的，只是因为这个框架还不成熟，所以就算关闭也没有什么用处
> 
> 以后我可以把缩略图右键的保存选项排到第一个位置。但如果是详情页，保存推荐使用上方或下方工具栏，而非右键菜单
> 
> 如果遇到闪退可以看看日志文件夹内（可以在设置页找到）有没有相关记录，如果有，那大概率我们可以解决，否则就不好办了
> 
> 另外当前版本好像有一个会删除下载所在文件夹的bug，所以最好保证下载文件夹为空或没有重要文件】(。•ω•。)ノ♡

![image](https://github.com/Pixeval/Pixeval/assets/97382367/c63db3e6-4b8b-4f13-ae48-54e558a2fbcb)
![image](https://github.com/Pixeval/Pixeval/assets/97382367/7553e60f-a13b-459b-9dc1-d72125ceb55d)

**Comment by Poker-sang** [comment]
我还第一次看到这种报错，也许我可以试试修复

**Comment by Poker-sang** [comment]
谢谢你提的建议

第一点确实从新到旧听起来更顺耳，以后可以改一下

第二点是因为现在卡片上显示的信息太多了，显示爱心有点太冗杂了

第三点有人提过，你可以右键单击上面的信息按钮，他就会一直显示了

**Comment by EVOLUTION-CIAO** [comment]
> @EVOLUTION-CIAO 谢谢你提的建议
> 
> 第一点确实从新到旧听起来更顺耳，以后可以改一下
> 
> 第二点是因为现在卡片上显示的信息太多了，显示爱心有点太冗杂了
> 
> 第三点有人提过，你可以右键单击上面的信息按钮，他就会一直显示了

第二點個人覺得還好，都是角落，舊版本預覽圖的是【寬圖】，新版本預覽圖是【長圖】，顯示數量比起舊版本也就多了個ai提示圖標

第三點我以為是右鍵後就能一直記住狀態顯示，但我只要關掉窗口再開另外一個作品又重置回無【信息】狀態了
（需要作品信息的情形一般都是 【個別】作品有需要-打開-複製所需信息-關閉 這樣循環，關閉後打開另一個不顯示就有些....）
希望能把這兩個做成【設置】內的可選選項吧

**Comment by Poker-sang** [comment]
@EVOLUTION-CIAO  第三点你可以开个新issue以方便跟踪

第二点以后也许可以在过滤器里加个`-/+like`的约束来排除已收藏的作品
