### ISSUE TITLE
Pixeval无法加载

### ISSUE THREAD

**Issue by UEFI233** [Pixeval/Pixeval#343]
### Pixeval's version

WinUI3

### Description of the problem

pixeval可以登录但页面空白，

### Screenshot

![1706438812888.png](https://www.freeimg.cn/i/2024/01/28/65b630a066fa7.png)

### Windows major version

Windows 10

**Comment by BadArgument** [comment]
刚刚我这边同样的问题，现在解决了。
如果你出现页面空白，可能有以下原因：

1.  **检查本地代理是否关闭，本地hosts是否正常（否则访问可能无法正常进行）**
2.  **检查“设置”中“启用直连”开关是否开启，如未开启则需开启后重启应用**
3.  **检查“图片镜像站代理”的链接是否可用（如无链接可尝试采用https://i.yuki.sh/，这是[yuki](https://blog.yuki.sh/posts/599ec3ed8eda/?)大佬的代理服务器）**
