### ISSUE TITLE
现在打不开了吗

### ISSUE THREAD

**Issue by qianqiusu** [Pixeval/Pixeval#344]
### Pixeval's version

WinUI3

### Description of the problem

提示要安装.net core? 去官网安装了.net 8.0之后也打不开

### Screenshot

![8026ED92D39165FC1F1ADDDAD75F6D9E](https://github.com/Pixeval/Pixeval/assets/101458881/50f02e30-074c-4fc1-b5a0-408b5017d200)

### Windows major version

Windows 11

**Comment by Poker-sang** [comment]
3.1.5版本需要.net core3.1版本其他版本.net暂时不行，.net8版本正在开发中
