### ISSUE TITLE
勾选“使用文件缓存”选项会导致软件闪退

### ISSUE THREAD

**Issue by yeezylife** [Pixeval/Pixeval#347]
### Pixeval's version

WinUI3

### Description of the problem

设置里勾选文件缓存之后，下次打开会闪退。为了重置设置只能卸载重装。
我重装完，又搞了一遍登录上了，不动任何设置，打开不会闪退。
再次打开，勾选文件缓存，闪退复现。

### Windows major version

Windows 11

### Specific Windows version

Windows 11 22H2 (22621)

**Comment by xyzWesker** [comment]
不需要重装，在加载完每日推荐图片前打开设置就不会崩溃，但是退出设置后回到每日推荐就会崩溃

**Comment by Poker-sang** [comment]
下次把全部设置都挪到登录页面好了

**Comment by Poker-sang** [comment]
这个几乎一定会闪退，所以不要开这个项了【
而且这个缓存的保存时间只有一天，并不会长时间有效

**Comment by Poker-sang** [comment]
> 主要这一条很难做到，好不容易登录成功了 然后直接就跳转到每日推荐图片了

你可以登录成功之后把网线拔了【他就不会继续加载了

**Comment by Poker-sang** [comment]
开了缓存理论上只能快速加载之前的图片，新图片不会加速的【
