### ISSUE TITLE
特辑推荐和关注动态无法使用

### ISSUE THREAD

**Issue by xyzWesker** [Pixeval/Pixeval#348]
### Pixeval's version

WinUI3

### Description of the problem

特辑推荐和关注动态是还在开发中吗？因为老版本是能用这两个功能的。如果还在开发就大大加油👍🙏🙏🙏

### Windows major version

Windows 10

**Comment by Poker-sang** [comment]
嗯，api变了，还没实现这个功能

**Comment by Poker-sang** [comment]
关注动态需要网页Cookie，现在为了更方便登录暂时放弃了动态功能

特辑我先做了个最简单的浏览功能，点击就直接跳转到外部网页了，因为app端还没有pixivision的api，我不会搞等以后dc做了
