### ISSUE TITLE
4.0版本仍然存在作者/图片搜索不全的问题

### ISSUE THREAD

**Issue by gbwhisper** [Pixeval/Pixeval#350]
### Pixeval的版本

WinUI3

### 问题描述

上一个版本的漏图问题在4.0仍然没有得到解决：
Toai_R (34736455)，在pixeval4.0里只能搜到4张图。
小野智 (87046707)，在pixeval4.0里甚至都不存在。（见附图p1，与其他网页平台的对比p2）
另外我发现，很多原来能搜索到的作者，最近也变得搜不到了，如妄想神話無限工房 (91344082)。上面提到的这些作者的图在去年都曾经在pixeval能完整浏览的。
望解决，谢谢。

### 屏幕截图

![p1](https://github.com/Pixeval/Pixeval/assets/138815633/0c3b2689-a8af-4100-a57d-0f8df2d39977)
![p2](https://github.com/Pixeval/Pixeval/assets/138815633/81f8cbea-f094-420e-b42e-3e228e26c86a)

### Windows主要版本

Windows 11

**Comment by Poker-sang** [comment]
你直接登录自己的p站号能看到这些图片吗，如果是AI或者R-18可能被你自己账号设置屏蔽了

**Comment by Poker-sang** [comment]
我搜了一下这个用户，显然是之前的账号被封或者注销了，你这里可能是镜像站，Pixeval走的是Pixiv的api，如果pixiv不存在这个用户，则这里也不会显示

![image](https://github.com/Pixeval/Pixeval/assets/62325494/1fd0b517-315d-43ff-bbe1-36874c5796df)

**Comment by Poker-sang** [comment]
另一个人的图大部分是AI图，你应该是在网页端屏蔽了AI图，所以才看不到

![image](https://github.com/Pixeval/Pixeval/assets/62325494/65d769b7-00ba-4b70-8a7f-9377d16e4a00)

**Comment by Poker-sang** [comment]
P站近期封禁了一批作者，看不到是很正常的

**Comment by gbwhisper** [comment]
> 另一个人的图大部分是AI图，你应该是在网页端屏蔽了AI图，所以才看不到
> 
感谢回答！用pixeval的主要原因是没法翻墙...所以并没法验证这个。如果是因为R-18标签，而我又没法进网站修改，那可能就是死循环了。。谢谢我想办法试试。
Pixeval是随着P站设置的吧T_T

**Comment by Poker-sang** [comment]
你可以想办法让朋友帮你或者自己上一次P站，把所有需要的设置都改好，这样以后就不需要处理了

**Comment by gbwhisper** [comment]
> 你可以想办法让朋友帮你或者自己上一次P站，把所有需要的设置都改好，这样以后就不需要处理了

还是想请你帮忙看看。我找了一般向非R-18、非AI的作品 图片id（100440006）和（103175199），但是Pixeval也是不显示。。
当然我仍然是用镜像站来检测的，我无法确认作品在直连的时候是否存在。
我发现很多没有R-18和AI标签的图我也搜索不出，这个仿佛和你说的也不是很匹配。
也不知道别的大陆网友有没有这个问题。。无论如何，辛苦了。

**Comment by Poker-sang** [comment]
都可以看到啊

![image](https://github.com/Pixeval/Pixeval/assets/62325494/b9ef366e-97ac-4fda-bfca-cea901e17f56)

**Comment by Poker-sang** [comment]
你从哪里看的

**Comment by Poker-sang** [comment]
你要查看某个id的作品或者作者时，可以把id粘贴到窗口正上方的文本框中，然后他提示最上面两条分别是打开对应作品和作者，点击后就可以进去了
