### ISSUE TITLE
使用触控笔操作会导致软件卡死闪退

### ISSUE THREAD

**Issue by YRSB** [Pixeval/Pixeval#352]
### Pixeval的版本

WinUI3

### 问题描述

我的设备是Surface Go 3，Windows 11 23H2
使用Pixeval时，如果使用触控笔进行控制，软件会直接卡死，过一段时间后就闪退了;
但是正常用手触控操作的话是没问题的。

### 屏幕截图

我录制了视频

### 错误代码

日志文件夹是空的

### Windows主要版本

Windows 11

**Comment by Poker-sang** [comment]
卡死是在滑动过程中还是点击过程中呢，还是两者都有

**Comment by YRSB** [comment]
> 卡死是在滑动过程中还是点击过程中呢，还是两者都有

笔一碰到就卡死了
https://drive.google.com/file/d/1-rfyMfcFEvmU2nOm7g_LuOg5PcZijiI6/view

**Comment by n0099** [comment]
# 你永远不知道用户怎么使用你的产品

**Comment by Poker-sang** [comment]
我没有触控笔不好测试，可以麻烦你试试有没有什么地方不会卡死吗，比如说试试笔直接点击关闭键，或者点击左边的按钮。

另外这个设备是surface吗

**Comment by Poker-sang** [comment]
> 你永远不知道用户怎么使用你的产品

触控笔也算是正常需求吧，而且winui这个框架说是一开始就支持各种触控输入的啊

**Comment by YRSB** [comment]
> 我没有触控笔不好测试，可以麻烦你试试有没有什么地方不会卡死吗，比如说试试笔直接点击关闭键，或者点击左边的按钮。
> 
> 另外这个设备是surface吗

是的，是Surface Go 3。
目前我试了下，右上角那三个关闭最小化窗口按钮是正常的，但一点击其他地方就卡死了，左上角的菜单展开按钮、或是点击插画等等都是卡死。

**Comment by Poker-sang** [comment]
这感觉不好办了，如果只是不能滑动可能是ScrollView的问题，所有都不能的话可能是winui本来的问题了

**Comment by n0099** [comment]
> 触控笔也算是正常需求吧

疑似 https://z.n0099.net/#narrow/stream/19-osu!/topic/.E9.9F.B3.E6.B8.B8.E8.A3.85.E5.A4.87/near/1 https://z.n0099.net/#narrow/near/102344

**Comment by Poker-sang** [comment]
我想把这个问题反馈给<https://github.com/microsoft/microsoft-ui-xaml>，可以借用你的视频吗

**Comment by n0099** [comment]
> 可以借用你的视频吗

与此同时 https://z.n0099.net/#narrow/near/99114 https://en.wikipedia.org/wiki/Wikipedia:Emailing_users#Reposting_emails_publicly https://en.wikipedia.org/wiki/Wikipedia:Harassment#Private_correspondence

**Comment by YRSB** [comment]
> 我想把这个问题反馈给https://github.com/microsoft/microsoft-ui-xaml，可以借用你的视频吗

可以

**Comment by Poker-sang** [comment]
> 疑似 [https://z.n0099.net/#narrow/stream/19-osu!/topic/音游装备/near/70642](https://z.n0099.net/#narrow/stream/19-osu!/topic/%E9%9F%B3%E6%B8%B8%E8%A3%85%E5%A4%87/near/70642) https://z.n0099.net/#narrow/near/102344 https://www.youtube.com/watch?v=yq5P0wuRdps https://www.youtube.com/watch?v=ZwpOc3GC_ns

没看懂你要表达什么

> 与此同时 https://z.n0099.net/#narrow/near/99114 https://en.wikipedia.org/wiki/Wikipedia:Emailing_users#Reposting_emails_publicly https://en.wikipedia.org/wiki/Wikipedia:Harassment#Private_correspondence

不相关的东西你在邮件发啊

**Comment by Poker-sang** [comment]
你好，你可以在微软商店了下载一下WinUI Gallery测试一下会不会卡死嘛，看起来这个问题别人无法复现，我想看看是不是只有Pixeval有

**Comment by YRSB** [comment]
> 你好，你可以在微软商店了下载一下WinUI3 Gallery测试一下会不会卡死嘛，看起来这个问题别人无法复现，我想看看是不是只有Pixeval有

刚刚试了下，WinUI 3 Gallery不会卡死。
我用过的其他的WinUI 3软件，例如Magpie，也不会卡死。

**Comment by Poker-sang** [comment]
emmm，你试一下scrolling里面的scrollview页面呢，然后试着滑动一下里面的图片

**Comment by Poker-sang** [comment]
collections里面的itemsview也可以试试

**Comment by YRSB** [comment]
这两个试了，都没有问题，图片正常滚动

**Comment by Poker-sang** [comment]
噗难不成真是这个软件的问题？但我也没写过关于笔的逻辑啊

**Comment by YRSB** [comment]
很神奇，最新版本没问题了

**Comment by Poker-sang** [comment]
草，我还去官方库发了issue，太丢人了
