### ISSUE TITLE
App Translation feauture

### ISSUE THREAD

**Issue by bropines** [Pixeval/Pixeval#354]
### The type of your suggestion

New feature

### Pixeval's version

WinUI3

### Description

Add the ability to translate into other languages. I am a good translator, I would like to translate into my language.

**Comment by n0099** [comment]
Русский?

**Comment by bropines** [comment]
> Русский?

Конечно

**Comment by Poker-sang** [comment]
You can find string resources in

```
src\Pixeval\Strings\zh-cn
src\Pixeval.Controls\Strings\zh-cn
```

You can copy all the *.resjson files and translate them. Thanks for your contribution!

**Comment by bropines** [comment]
> You can find string resources in
> 
> ```
> README.md or README.en.md
> src\Pixeval\Strings\zh-cn
> src\Pixeval.Controls\Strings\zh-cn
> ```
> 
> You can copy all the *.resjson files and translate them. Thanks for your contribution!

After a couple of hours of violence against addictions, and a couple of minutes of translation, this is the result. There are problems with the text sizes (I'll try to translate them to fit the field sizes). I also had to duplicate the languages ​​(provided that I was zero in C# and googled the Internet for every bug) and the paths to them in the code itself. I'll make a pull request without my edits, I hope you can figure it out for yourself.

![image](https://github.com/Pixeval/Pixeval/assets/57861007/c899bfe6-7d30-4257-a2a2-ed6ded05b195)
![image](https://github.com/Pixeval/Pixeval/assets/57861007/208e6e29-9a37-4d9a-9f7a-cfaeaf10cc89)

**Comment by Poker-sang** [comment]
Thank you for your great efforts! You build looks like you replaced the language without building the project, how did this happen?

Also future updates may add new fields, should I use Google Translate to add them or something else?

**Comment by bropines** [comment]
> Also future updates may add new fields, should I use Google Translate to add them or something else?

I think I’ll put a checkmark to track changes, as soon as they appear, I’ll make the changes myself (Google, of course, can, but chatGPT or Yandex Translate is stupidly better because it understands more context when translating from CN to RU)

> Thank you for your great efforts! It looks like you replaced the language without building the project, how did this happen?

Thanks to GPT I just created new language strings, and as I realized when compiling c# it took Russian into account since it is the latest language. Stupid crutch, but it was necessary to check the language somehow, and I think gpt will not be able to write code for a full-fledged language change). Here I just changed the paths here for a while, in the pull request I didn't take them into account
`<PRIResource Include="Strings\ru-ru\CommentsPage.resjson" />`

**Comment by Poker-sang** [comment]
I am sorry. I should have figured out where the language settings entry is.

**Comment by bropines** [comment]
![Pixeval_Ml7iQKhpJU](https://github.com/Pixeval/Pixeval/assets/57861007/6af6d8d7-7ee9-433e-8fab-9e14f0e54863)
![k0pPJ7ElRf](https://github.com/Pixeval/Pixeval/assets/57861007/be6703a8-64a8-42a6-bafa-34ef27767c01)

I also noticed that when you change the theme, the main window changes, but to change the additional windows that open (for example, viewing a picture), then for him the theme will change only after restarting the application

**Comment by bropines** [comment]
> I am sorry. I should have figured out where the language settings entry is.

I tried prescribing it like this: 
```csharp
        AvailableCultures = new List<CultureInfo>
    {
        CultureInfo.GetCultureInfo("zh-cn"),
        CultureInfo.GetCultureInfo("ru-ru") // Добавляем русскую культуру
    };
```

and so

```csharp
{
    LanguageModel.DefaultLanguage,
    new LanguageModel("简体中文", "zh-cn"),
    new LanguageModel("Русский", "ru-ru") // Добавляем русский язык
};
```

But something didn't really work)

**Comment by Poker-sang** [comment]
Thanks for reporting. I will fix this soon.

**Comment by Poker-sang** [comment]
The language setting needs
 restart the app to apply. Did you restart it?

**Comment by bropines** [comment]
> The language setting needs
> restart the app to apply. Did you restart it?

Yes, I restarted (I commented out the Russian part in the video).

https://github.com/Pixeval/Pixeval/assets/57861007/41b7b331-12b4-464b-9791-a6ac5b7d6dc0

https://github.com/Pixeval/Pixeval/assets/57861007/43a5bd03-0607-4b44-abac-f063370c72da

**Comment by bropines** [comment]
What I have done is a terrible crutch, and perhaps better a person who knows C# would do it than me who knows... Python)
