### ISSUE TITLE
显示搜索结果但加载不完全时，改变窗体大小会导致图片重叠

### ISSUE THREAD

**Issue by xyzWesker** [Pixeval/Pixeval#355]
### Pixeval's version

WinUI3

### Description of the problem

如标题所示。慢网速下加载不完全，在加载期间还切换成按收藏数排序，重启后网络质量改善就没复现

### Screenshot

![QQ截图20240306171339](https://github.com/Pixeval/Pixeval/assets/81094092/5073e207-8396-4c2a-bc20-0079693f0fcf)

### Windows major version

Windows 10

**Comment by Poker-sang** [comment]
这个是LinedFlowLayout的bug，已经提了[issue](https://github.com/microsoft/microsoft-ui-xaml/issues/9142)了还没修复。

不是很清楚什么时候可以修复，但这个是新出的功能，也许修复比较快。

这个bug有时候可以通过调整窗口宽度临时解决。

**Comment by Poker-sang** [comment]
对了，设置里另一种网格布局还没有这个bug，如果觉得不好用可以暂时先使用那个布局

**Comment by xyzWesker** [comment]
非常好老的版本布局，使我奔周向上

**Comment by Poker-sang** [comment]
坏
