### ISSUE TITLE
增加返回上一个页面的按钮

### ISSUE THREAD

**Issue by xyzWesker** [Pixeval/Pixeval#356]
### 建议类型

新功能

### Pixeval的版本

WinUI3

### 描述

搜索图片显示结果后再点击设置后，找不到能回去搜索结果的按钮就只能重新搜索，排序方式也变成默认了。先搜索再点击每日推荐等同理。

**Comment by Poker-sang** [comment]
因为框架的bug，本来内存就占用很高，所以现在所有的页面离开就会被释放了，不会保存之前的状态。

如果你是win11，可以打开任务管理器看内存使用。可以打开文件资源管理器的图库，反复点击图库和别的页面，你就会发现内存上去就下不来了x

**Comment by xyzWesker** [comment]
悲（）

**Comment by Poker-sang** [comment]
如果以后这个bug修了说不定能加回这个功能，但这个bug已经提出五年没修复了【之前他们试图修过但没成功2333
