### ISSUE TITLE
点击设置中“禁用域前置直连”开关的右侧箭头闪退

### ISSUE THREAD

**Issue by youlan2333** [Pixeval/Pixeval#359]
### Pixeval的版本

WinUI3

### 问题描述

点击设置中“禁用域前置直连”开关的右侧箭头闪退，百分百复现

### 屏幕截图

![image](https://github.com/Pixeval/Pixeval/assets/64688148/102dfcde-748a-4bc9-aa91-cba86024c963)

### 错误代码

Logs为空

### Windows主要版本

Windows 11

### 具体Windows版本

Insider Build

### 其他信息

Windows 11 专业工作站版23H2 22631.3235

**Comment by Poker-sang** [comment]
惊了，这个问题只有在vs外部才会出现，用vs就不会出现

**Comment by youlan2333** [comment]
> 惊了，这个问题只有在vs外部才会出现，用vs就不会出现

雾草，我把设置里面的启用缓存（具体啥名忘了）勾上了结果打开加载界面转圈然后闪退
![image](https://github.com/Pixeval/Pixeval/assets/64688148/f0f8a953-5674-43f2-82b3-721912e23762)

**Comment by youlan2333** [comment]
怎么办是不是得重置应用 〒▽〒

**Comment by Poker-sang** [comment]
在加载出来之前去设置里改回来就行了

**Comment by youlan2333** [comment]
> 在加载出来之前去设置里改回来就行了

就是点不出来设置，我想看看有没有外部手段关了这个设置什么的（除了重置）

**Comment by Poker-sang** [comment]
emmm，你试试一进入应用就关闭网络，这样他也加载不出来了

**Comment by youlan2333** [comment]
> emmm，你试试一进入应用就关闭网络，这样他也加载不出来了

悲，登不上了

**Comment by youlan2333** [comment]
我服了，以后我再也不手贱了
![image](https://github.com/Pixeval/Pixeval/assets/64688148/cd221c84-208d-4a53-a1a0-1339e63fcb2b)
![image](https://github.com/Pixeval/Pixeval/assets/64688148/a815b8e8-4cad-426e-b917-98a4758a762f)

**Comment by Poker-sang** [comment]
> 悲，登不上了

说错了，是登录上了，加载完成前，再关闭网络

**Comment by Poker-sang** [comment]
抱歉啦，我会赶快出下一个版本修复的x

**Comment by youlan2333** [comment]
> 抱歉啦，我会赶快出下一个版本修复的x

qwq

**Comment by bropines** [comment]
For some reason it won’t let me in without a VPN either. I compile the version from sources
