### ISSUE TITLE
Problem with HttpClient when using proxy server

### ISSUE THREAD

**Issue by bropines** [Pixeval/Pixeval#363]
### Pixeval's version

WinUI3

### Description of the problem

For some reason, the version I collected from the latest commits does not see the Internet. When I turn on the VPN everything is fine. I use [goodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI) to connect to sites blocked in my country, and it seems that it does not work in Pixeval, or I broke something

https://github.com/Pixeval/Pixeval/assets/57861007/fbe3166d-ce26-4b0e-9d87-e1739e69af6b

### Windows major version

Windows 11

### Specific Windows version

Insider Build

**Comment by Poker-sang** [comment]
When the windows proxy settings changed, you need restart the app to apply the changes. This is a feature of HttpClient, and it's also a tricky bug we want to fix.

**Comment by bropines** [comment]
> When the Windows proxy settings changed, you need restart the app to apply the changes. This is a feature of `HttpClient`, and it's also a tricky bug we want to fix.

Well, for now I solved it by turning on the “automatic proxy” (thank you). Should I close the Issue or let it hang as an error because of `HttpClient`?

**Comment by bropines** [comment]
And another question, how to compile the program? To directly into an exe file?

**Comment by Poker-sang** [comment]
> And another question, how to compile the program? To directly into an exe file?

WinUI3 is packaged app, if you want to build into package and publish, you can right click the *Pixeval* and click "打包和发布"(Pack and Publish), and click "创建应用程序包"(Create app package). You can pack it by sideload(not via MsStore).

![image](https://github.com/Pixeval/Pixeval/assets/62325494/05fedee1-07f8-4da9-83dc-e3ef3bec880d)

**Comment by Poker-sang** [comment]
> let it hang as an error because of `HttpClient`?

You can edit the title of the issue and keep it open.

**Comment by dylech30th** [comment]
As I recall compiling the program requires some prerequisites other standard procedure for compiling c# programs, they are listed in the readme
