### ISSUE TITLE
添加“查看中等图片尺寸”的选项

### ISSUE THREAD

**Issue by yeezylife** [Pixeval/Pixeval#364]
### 建议类型

新功能

### Pixeval的版本

WinUI3

### 描述

目前点击“我的收藏”或者“每日推荐”里的缩略图时，只能默认加载尺寸最大的图片，这样有些比较大的图片；或者网络不好的时间段，会加载的比较慢。

我有时候想要回顾一下收藏的图片，但是做不到比较快速的一张一张的观看（经常碰到要加载一会儿）

所以希望能够添加“查看中等图片尺寸”选项，这样可以比较快速的像看幻灯片一样一张一张往下翻着看。。

又或者，允许加大缩略图的显示尺寸，这样我直接在“我的收藏”里滚动看看中等大小的缩略图。。。也能实现对已收藏图片的浏览。否则很多图片收藏之后就再也没看过一次了。。

**Comment by Poker-sang** [comment]
这些缩略图本来就是中等大小的，我之前把大图选项砍了，因为网络和内存问题

**Comment by Poker-sang** [comment]
emmm可能会实现这个issue，但下一次更新不一定能做到

**Comment by Poker-sang** [comment]
(￣﹃￣)

**Comment by Poker-sang** [comment]
关于中等图片的界面设计你有什么想法嘛

**Comment by Poker-sang** [comment]
大概要多大比较好

**Comment by Poker-sang** [comment]
如果不是很大的话，也许原来的列表就能显示，要是更大一些就需要弹出一个对话框或者窗口了

**Comment by Poker-sang** [comment]
加了一个默认关闭的选项

![image](https://github.com/Pixeval/Pixeval/assets/62325494/34420ecc-edce-4465-bbf4-cdffef0cff5f)

**Comment by Poker-sang** [comment]
你有好多表情包【居然还是mp4的

**Comment by Poker-sang** [comment]
摸鱼了，pr等以后想起来再合
