### ISSUE TITLE
应用安装程序无法安装应用包相关项。请向开发人员索要应用包。

### ISSUE THREAD

**Issue by lhj5426** [Pixeval/Pixeval#370]
### Pixeval's version

WinUI3

### Description of the problem

![image](https://github.com/Pixeval/Pixeval/assets/30548000/d9853ea9-3f36-4aa4-b9a3-60ad1e6d2aed)
![image](https://github.com/Pixeval/Pixeval/assets/30548000/01c47b28-4cd0-4d6b-ac18-85775bc20684)

如图所示  为什么呢？

### Windows major version

Windows 10

### Additional Information

2种方法都无法安装 
![image](https://github.com/Pixeval/Pixeval/assets/30548000/1b63aece-821b-4541-987c-575000bddc25)
这个8. 也装了

**Comment by Poker-sang** [comment]
你好，第二张图片里提到的错误日志文件可以提供一下吗

**Comment by lhj5426** [comment]
> 你好，第二张图片里提到的错误日志文件可以提供一下吗

您说的是这个东西吗


D:\Ddown\Pixeval_4.0.0.0_x64>powershell -NoProfile -ExecutionPolicy Bypass -NoExit -Command "& {Start-Process PowerShell -ArgumentList '-ExecutionPolicy Unrestricted reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"" /t REG_DWORD /f /v ""AllowDevelopmentWithoutDevLicense"" /d 1' -Verb RunAs}"; "&'.\Install.ps1'"                                                                                                                            找到包: D:\Ddown\Pixeval_4.0.0.0_x64\Pixeval_4.0.0.0_x64.msix                                                                                                                                                                                                                                                                                                                                                                                                                             正在安装应用程序...                                                                                                                                                                                                                          找到依赖项包:                                                                                                                                                                                                                                D:\Ddown\Pixeval_4.0.0.0_x64\Dependencies\x86\Microsoft.WindowsAppRuntime.1.5.msix
D:\Ddown\Pixeval_4.0.0.0_x64\Dependencies\x64\Microsoft.WindowsAppRuntime.1.5.msix
Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073CF6, 无法注册包。

错误 0x80070003: Windows 无法为 Microsoft.WindowsAppRuntime.1.5_5001.58.448.0_x64__8wekyb3d8bbwe 程序包创建 AppContainer 配置文件。

注意: 有关其他信息，请在事件日志中查找 [ActivityId] 502a34a5-70b7-0000-d064-3650b770da01，或使用命令行 Get-AppPackageLog -ActivityID 502a34a5-70b7-0000-d064-3650b770da01

所在位置 D:\Ddown\Pixeval_4.0.0.0_x64\Add-AppDevPackage.ps1:487 字符: 13
+             Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\Ddown\Pixeva....0.0.0_x64.msix:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

错误: 未能安装应用程序。
按 Enter 键继续...:
PS D:\Ddown\Pixeval_4.0.0.0_x64>
PS D:\Ddown\Pixeval_4.0.0.0_x64>

运行完 好像并没有在  目录下生成 疑似 错误日志的东西？

**Comment by lhj5426** [comment]
[剪贴板文本.txt](https://github.com/Pixeval/Pixeval/files/14545724/default.txt)
复制 粘贴好像不全  放个TXT里了

**Comment by Poker-sang** [comment]
你电脑上有微软商店吗，你是不是卸载了

**Comment by lhj5426** [comment]
> 你电脑上有微软商店吗，你是不是卸载了

![image](https://github.com/Pixeval/Pixeval/assets/30548000/b97875c4-ba24-4b2c-99b2-a01f9edfc701)
没 虽然不用 也很讨厌商店应用 但是 我没有卸载 话说系统级的的东西能卸载？

**Comment by Poker-sang** [comment]
可以，但是系统功能会缺失，还是留着比较好。

微软商店安装卸载软件都比较干净我还挺喜欢，以后pixeval也可能会上。

你看看现在windows版本是多少，按win+pause可以看到？有没有可用的更新，如果有更新一下可能可以解决

**Comment by lhj5426** [comment]
> 可以，但是系统功能会缺失，还是留着比较好。
> 
> 微软商店安装卸载软件都比较干净我还挺喜欢，以后pixeval也可能会上。
> 
> 你看看现在_windows_版本是多少，按win+pause可以看到？有没有可用的更新，如果有更新一下可能可以解决
按win+pause 没反映 我是win+R winver 命令看的这个
![image](https://github.com/Pixeval/Pixeval/assets/30548000/faf98ff3-cbec-45cc-bd96-d701a1bc2af3)

**Comment by lhj5426** [comment]
> 可以，但是系统功能会缺失，还是留着比较好。
> 
> 微软商店安装卸载软件都比较干净我还挺喜欢，以后pixeval也可能会上。
> 
> 你看看现在_windows_版本是多少，按win+pause可以看到？有没有可用的更新，如果有更新一下可能可以解决

其实我听害怕win 系统更新的 WIN这破系统不像安卓和IOS 这种手机系统 就是更新了顶多可以能就卡顿慢一点
这windows更新 整不好系统就崩溃 所以我都是
装完系统的第一件事装火绒 让WD闭嘴然后运行
![image](https://github.com/Pixeval/Pixeval/assets/30548000/a7056154-667e-40e4-ac81-848366805906)
禁止 更新 如果不让wd 闭嘴运行不了这东西  所以 使用您的软件必须要更新系统吗？

**Comment by Poker-sang** [comment]
也不是一定要更新，但我更新的时候没有遇到你说的情况，所以我一直保持最新版的

你可以去设置里查看操作系统版本的最后一项，如果它低于19041那就肯定运行不了的

![image](https://github.com/Pixeval/Pixeval/assets/62325494/7cba8c52-c31a-4d1c-abe4-bf8a37ef727a)

**Comment by Poker-sang** [comment]
你可以参考一下这个方法 https://www.zhihu.com/question/411518183

**Comment by lhj5426** [comment]
![image](https://github.com/Pixeval/Pixeval/assets/30548000/1d394ddd-b709-4196-877a-296b161d8911)
![image](https://github.com/Pixeval/Pixeval/assets/30548000/952a6d4e-5dcf-4c05-85a2-bbbe99f49536)
![image](https://github.com/Pixeval/Pixeval/assets/30548000/66684c40-655c-4de0-b2a6-d0d0aac63082)
![WGestures_2024年03月10日14点12分50秒948](https://github.com/Pixeval/Pixeval/assets/30548000/3827e985-c10e-4061-8c39-d3a238b16eaa)
哈哈 对非EXE的应用没有好感 就是这个原因 各种安装不上 贼闹心 和麻烦

**Comment by lhj5426** [comment]
大佬有没有考虑过用 真EXE来开发呀

**Comment by n0099** [comment]
> ![image](https://private-user-images.githubusercontent.com/30548000/311488883-1d394ddd-b709-4196-877a-296b161d8911.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNTI2NDcsIm5iZiI6MTcxMDA1MjM0NywicGF0aCI6Ii8zMDU0ODAwMC8zMTE0ODg4ODMtMWQzOTRkZGQtYjcwOS00MTk2LTg3N2EtMjk2YjE2MWQ4OTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDA2MzIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NzVmNzFmNmE1YzFmMTA2MDlhMTU3MDIwNjBhMTBmNGNjYTIwYWY3OTQzMmUzOGJkMTBhYmIzNWJlMWFmZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7hDHAX49CdwgP1w3WnsTir4Bhkzw-aJaB0hu4i9wwHA)

https://www.pingwest.com/a/55138
> 不要怪我们没有警告过你，
> 我们都有不顺利的时候，
> Something happened，
> 这真是让人尴尬。
> 请坐和放宽，
> 滚回以前的版本，
> 这就是你的人生，
> 是的，你的人生。

https://www.zhihu.com/question/29093152
https://zh.moegirl.org.cn/微软式中文

**Comment by Poker-sang** [comment]
安装不了是因为用的windows版本太旧了，导致新软件在旧电脑上跑不了。

就像很多网页要求你用chrome打开，而不支持ie一样。现在大部分网页都不能在旧的ie上跑了

旧版3.1.5是用所谓exe开发的，但不会有更新了

**Comment by lhj5426** [comment]
算了不用了 麻烦你了这两天 继续用网页慢慢加载图片吧

**Comment by n0099** [comment]
> 就像很多网页要求你用chrome打开，而不支持ie一样。现在大部分网页都不能在旧的ie上跑了

建议继续死守10年前的已于23年1月被计划淘汰的win81 https://github.com/win32ss/supermium https://github.com/Alex313031/thorium-win7

https://z.n0099.net/#narrow/stream/40-retro/topic/chrome109/near/81953
> https://github.com/InterLinked1/chromefill)
> https://blog.interlinked.us/66/when-the-world-wide-web-goes-on-strike-how-do-you-fight-back
>
> > 抛开安全问题不谈，如果它没有损坏，为什么要升级（或降级），对吧？令人惊讶的是，Iron 70 或多或少地运行了三年，没有出现任何问题。直到 2021 年第四季度，这些问题才开始出现。第一个提示是当专有的 PDF 阅读器停止工作时。接下来，Panopto 视频播放器停止工作。然后，一个又一个地点，事情开始破裂，而且越来越严重。几周后，StackOverflow.com 的大部分内容都停止工作了——我无法再对任何事情发表评论或投票；该网站与互联网档案馆的 Wayback Machine 中的存档刮擦一样有用 - 内容在那里，但它被冻结了，无法动态使用。我几乎不敢相信发生了什么。万维网正在逐个站点地崩溃。我并不是唯一一个有这种令人不快的认识的人。 MSFN 论坛上的复古计算机和计算机爱好者都发现他们的浏览器（其中许多是基于 UXP 的、从旧的 Mozilla 代码中分叉出来的）遇到了全新的问题。看起来这似乎是“自上而下”协调一致的努力，目的是淘汰任何不是最新的 Chrome 或 Firefox 的东西。当然，这很荒谬，但这几乎就是实际效果。在过去的五到十年中，科技格局发生了根本性的变化。正如多萝西所说，我们不再在堪萨斯了。网络最初的开创性开放性质已经消失，取而代之的是臃肿的网站，充满了没人想要的无用 JavaScript 的网站，一个缓慢而臃肿的网络，今天比二十年前更加难以访问，并且与有希望的2000 年代趋势相反，一种趋势是从开放标准和浏览器兼容性转向 Google Chrome 和 Mozilla Firefox 的双头垄断。

**Comment by Poker-sang** [comment]
好的，没关系

**Comment by lhj5426** [comment]
> 安装不了是因为用的_windows_版本太旧了，导致新软件在旧电脑上跑不了。
> 
> 就像很多网页要求你用chrome打开，而不支持ie一样。现在大部分网页都不能在旧的ie上跑了
> 
> 旧版3.1.5是用所谓exe开发的，但不会有更新了

关键22H2 相对于win10 来说 版本不低
![image](https://github.com/Pixeval/Pixeval/assets/30548000/a5d40d2c-9b6f-4615-b739-32b0a2654aed)
相对于11 来说确实过时

**Comment by n0099** [comment]
https://z.n0099.net/#narrow/stream/24-tbm/topic/github.2Ecom.2FPoker-sang/near/98621

> [...]
> > 然而事实核查win10也早已成为又一个m$ft弃子 [near#98374](https://z.n0099.net/#narrow/streams/public/near/98374) 永远地留在了22H2 https://learn.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro
> [...]

https://en.wikipedia.org/wiki/Windows_10_22H2

**Comment by lhj5426** [comment]
> https://z.n0099.net/#narrow/stream/24-tbm/topic/github.2Ecom.2FPoker-sang/near/98621*
> 
> > [...]
> > > 然而事实核查win10也早已成为又一个m$ft弃子 [near#98374](https://z.n0099.net/#narrow/streams/public/near/98374)*  永远地留在了22H2 [https://learn.microsoft.com/en-us/lifecycle/products/_windows_-10-home-and-pro](https://learn.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro)* 
> > > [...]
> 
> https://en.wikipedia.org/wiki/Windows_10_22H2*
> 
> 与此同时
> 
> https://github.com/Pixeval/Pixeval/blob/804cf0cac6bfb2b8a60e13b2f0d402f9c529959e/src/Pixeval/Pixeval.csproj#L119-L122
> 
> 
> https://github.com/Pixeval/Pixeval/blob/804cf0cac6bfb2b8a60e13b2f0d402f9c529959e/README.md?plain=1#L22
> 
> 
> 上网搜 https://github.com/search?q=repo%3APixeval%2FPixeval+19041&type=code 有真相

我是每次系统崩溃之后 会下载往前一点的版本 版本安装
但是安装完之后 不会直接更新 是等下一次系统崩溃之后 重新装的时候 往前更新一点版本
下次应该就是23H2了 如果有的话？
11几年之后吧

**Comment by n0099** [comment]
不会有22H2之后的win10大版本 https://en.wikipedia.org/wiki/Windows_10_22H2 https://techcommunity.microsoft.com/t5/windows-it-pro-blog/windows-client-roadmap-update-april-2023/ba-p/3805227
正如同16年某时任win10带PM曾声称`win10是最后的windows` https://answers.microsoft.com/en-us/windows/forum/all/what-happened-to-the-last-version-of-windows/e969d870-5013-484f-8476-6ea5d0446182 https://www.reddit.com/r/technology/comments/oae464/wasnt_windows_10_supposed_to_be_the_last_version/ https://www.quora.com/Didnt-Microsoft-say-Windows-10-was-going-to-be-the-last-Windows-release-Why-did-they-decide-to-release-another

**Comment by lhj5426** [comment]
> 不会再有22H2之后的win10大版本 https://en.wikipedia.org/wiki/Windows_10_22H2* [https://techcommunity.microsoft.com/t5/_windows_-it-pro-blog/_windows_-client-roadmap-update-april-2023/ba-p/3805227](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/windows-client-roadmap-update-april-2023/ba-p/3805227)* 正如同15年某时任`m$ft精神mvp`步道师`Jerry Nixon`曾声称`win10是最后的_windows_` [https://www.theverge.com/2015/5/7/8568473/_windows_-10-last-version-of-_windows_](https://www.theverge.com/2015/5/7/8568473/windows-10-last-version-of-windows)* https://web.archive.org/web/20150509091959/https://channel9.msdn.com/Events/Ignite/2015/BRK2352* https://old.reddit.com/r/Windows10/comments/ob0jvi/why_did_microsoft_lie_about_windows_10_being/* 业已应验 [https://answers.microsoft.com/en-us/_windows_/forum/all/what-happened-to-the-last-version-of-_windows_/e969d870-5013-484f-8476-6ea5d0446182](https://answers.microsoft.com/en-us/windows/forum/all/what-happened-to-the-last-version-of-windows/e969d870-5013-484f-8476-6ea5d0446182)* https://old.reddit.com/r/technology/comments/oae464/wasnt_windows_10_supposed_to_be_the_last_version/* 正如同臭名昭著的`m$ft改名部` [https://z.n0099.net/#narrow/search/m$ft改名部](https://z.n0099.net/#narrow/search/m$ft%E6%94%B9%E5%90%8D%E9%83%A8)*

你好像不发链接就不会好好说话呢 像个机器人一样 哈哈 真好玩 
没有的 话下次等电脑崩溃就 上11 等崩溃的时候再说了 主要 反正在崩溃之前我还用傲梅做了一键还原
这个系统估计可以用1到2年 大概 如果启动引导不崩溃的情况下

我做一次系统老麻烦了 装python 运行环境 CUDA 运行环境 就够我喝一壶的 为了离线跑 一些东西

**Comment by acgurl** [comment]
如果是不完整的精简版系统，可以尝试去[最新 Windows 应用 SDK 下载](https://learn.microsoft.com/zh-cn/windows/apps/windows-app-sdk/downloads)下载`WindowsAppRuntimeInstall-x64`并安装
如果安装正常再去服务确保`Windows installer`已启动
都完成后再次安装`Pixeval`应该就不会报错了
