### ISSUE TITLE
设置内更改默认排序方式不起作用

### ISSUE THREAD

**Issue by xyzWesker** [Pixeval/Pixeval#373]
### Pixeval's version

WinUI3

### Description of the problem

在设置里更改默认排序方式为收藏数降序后，无论每日推荐还是点击图片标签查图片等等功能，首次显示图片的排序方式还是按照不进行排序来显示，只有手动切换到其他方式再切回来才能生效（显示是收藏数降序，但切换到不进行排序时图片没变化）

### Screenshot

切换前
![QQ截图20240310173929](https://github.com/Pixeval/Pixeval/assets/81094092/cf6dab72-f7c6-413c-a3fe-897fe3ece539)

切换后
![QQ截图20240310174009](https://github.com/Pixeval/Pixeval/assets/81094092/0335a768-58f7-41c1-83c8-f02e64fd18b5)

### Windows major version

Windows 10

**Comment by Poker-sang** [comment]
这个的原因是保存设置和导航同时进行，导致导航之后读了旧的设置，现在再考虑能不能修复，不过这个还不算很恶性的bug】

**Comment by xyzWesker** [comment]
测试老本行是这样的😋bug总是要提的

**Comment by Poker-sang** [comment]
好好 多提】

**Comment by xyzWesker** [comment]
还是有些恶性的。排序方式是根据  已接收的  不进行排序的  图片进行排序，而不是p站的排序，需要多次下拉加载新图才可能完整看到真正按照p站排序好的图片（每次下拉都有新感觉）

**Comment by Poker-sang** [comment]
就是这样的，因为p站没有那种api
