### ISSUE TITLE
默认的图片格式？

### ISSUE THREAD

**Issue by gbwhisper** [Pixeval/Pixeval#375]
### The type of your suggestion

Feature optimization

### Pixeval's version

WinUI3

### Description

注意到4.0版本中有“下载静态图的格式”选项，似乎是要强制勾选的。但我想保留图片本身的格式，希望能增加保持图片原格式的默认选项。（如果png原图以jpg的格式被保存下来，是怎样一个压缩率？）

**Comment by Poker-sang** [comment]
png是无损的，不会压缩图片，你可以看注释，只有有损格式才会压缩图片。

gif理论上不会压缩，但他不支持更多颜色，所以和压缩了是一样的。

如果想要最好的图片画质，选择无损的选项即可。

加入这个选项的原因本来是为了提高动图的画质（因为p站下载的动图是一堆静态图，直接压成gif会损失画质），而静态图是顺便一起实现的。

**Comment by gbwhisper** [comment]
> png是无损的，不会压缩图片，你可以看选项旁边的注释，只有有损格式才会压缩图片。
> 
> gif理论上不会压缩，但他不支持更多颜色，所以和压缩了是一样的。
> 
> 如果想要最好的图片画质，选择无损的选项即可。
> 
> 加入这个选项的原因本来是为了提高动图的画质（因为p站下载的动图是一堆静态图，直接压成gif会损失画质），而静态图是顺便一起实现的。

但有些作者原图格式就是jpg的，选中了png是不是会强制存一个png的图，反而比原图更大了？

**Comment by Poker-sang** [comment]
会大一些，但是图片一般不会很明显，如果比较在意图片的空间的话也可以使用webp，webp可以兼顾大小和效果

**Comment by n0099** [comment]
大脑升级avif/jpegxl，请 https://z.n0099.net/#narrow/search/avif

**Comment by gbwhisper** [comment]
> 会大一些，但是图片一般不会很明显，如果比较在意图片的空间的话也可以使用webp，webp可以兼顾大小和效果

如果原图是png，那么用pixeval以jpg保存下来时是以怎样的压缩率呢？80%？10%？
不好意思我问得比较细哈。。因为很多png原图都几十mb所以我尽可能还是想用jpg的，但又怕压缩率太高图糊掉了。

**Comment by gbwhisper** [comment]
当然我的建议是下次更新能带有旧版中保持图片原格式的选项：）

**Comment by Poker-sang** [comment]
压缩率不好说，质量都是75/100

**Comment by Poker-sang** [comment]
等文件缓存修复好后会考虑这个议题

**Comment by gbwhisper** [comment]
> 压缩率不好说，质量都是75/100（有损格式的）

谢谢，知道这个数字我心里就有底了。一般我png转jpg会选择95/100，个人认为是兼顾质量和尺寸的比例。75感觉是低了点？当然这个图片质量未来能调就更好了。

**Comment by Poker-sang** [comment]
这个是有损的比例，无损当然是100/100，调整压缩率的选项比这个issue简单多了，其实现在就可以做出来

**Comment by kkjj116** [comment]
复议，png格式下了几张图，数据大小跟浏览器下载的不一样，而且有大有小

**Comment by Poker-sang** [comment]
肯定不一样的，因为pixeval有新功能是为图片添加标签，会写入图片的exif块内。势必要重新编码图片，所以图片大小会不一样

**Comment by n0099** [comment]
> 为图片添加标签，会写入图片的exif块内

大概，是跨国集团监控。 https://z.n0099.net/#narrow/near/68202

**Comment by ICI-CNI** [comment]
> 会大一些，但是图片一般不会很明显，如果比较在意图片的空间的话也可以使用webp，webp可以兼顾大小和效果

复议。现在软件的运行逻辑是必定对接收到的原图（jpg/png）重新编码，再输出吗？我现在只是想下载原文件，不太在乎空间占用，目前只能用第三方软件/官网才能看到原始文件的后缀名。麻烦大佬加一个“保持原本格式”的选项

**Comment by Poker-sang** [comment]
好吧我会加一个保存为原图按钮，而非一个选项。不过如果你真的对空间无所谓的话，那无损格式（png，webp）应该可以满足你了啊
