### ISSUE TITLE
存图卡死时被删除下载文件夹

### ISSUE THREAD

**Issue by gbwhisper** [Pixeval/Pixeval#378]
### Pixeval的版本

WinUI3

### 问题描述

存图时随机会出现卡死/闪退的情况。闪退前在下载列表曾瞄到一行红字写着memory什么的，但不确定和问题是否存在关联。
下载图片卡死时，目标下载文件夹经常会被移动到回收站。
若保持pixeval开启，该下载文件夹可能还会持续被删到回收站。。

### Windows主要版本

Windows 11

**Comment by gbwhisper** [comment]
问题补充：电脑重启后，insufficient memory的问题也没有得到很好改善。
若闪退则不会发生删除文件夹的状况。问题只发生在卡死的情况。

**Comment by gbwhisper** [comment]
> 还好当时没直接写死彻底删除【不然数据就会丢了
> 
> 你在出现问题的时候电脑内存或者cpu占满了吗，电脑总内存是多少？

我电脑16G的RAM。出现问题时只开着Pixeval，电脑并没有出现任何卡顿的情况。而且存图时也是一张张存的，同时下载数也很低，1也不行。

**Comment by gbwhisper** [comment]
贴一段今天闪退的日志。我对比了一下每次闪退的error都是一样的内容。里面的id=0感觉有点奇怪。
另外还有一个不知道算不算问题的巧合，就是每次出问题的都是一横排的第一张图。一行放10张图，差不多存完70张或80张时，第71或81张差不多就会出问题。有一次甚至没有点保存，就光选中第一张图，就闪退了。

16:50:57 Error

at RunWithLoggerAsync at C:\WorkSpace\Pixeval\src\Pixeval.CoreApi\MakoClient.Logging.cs: 66
	Source: Refit
	Message: Network error while requesting URL: http://app-api.pixiv.net:443/v1/illust/detail?illust_id=0(Bypassing: True, Status code: 404) {"error":{"user_message":"\u5c1a\u65e0\u6b64\u9875","message":"","reason":"","user_message_details":{}}}
	StackTrace: 
		   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 288
		--- End of stack trace from previous location ---
		   at Pixeval.CoreApi.MakoClient.<>c__DisplayClass34_0.<<GetIllustrationFromIdAsync>b__0>d.MoveNext()
		--- End of stack trace from previous location ---
		   at Pixeval.CoreApi.MakoClient.RunWithLoggerAsync[T](Func`2 task)

**Comment by Poker-sang** [comment]
如果在页面还没加载出来的时候倒是有可能出现这种状况，如果已经看到图片的话确实比较奇怪了

**Comment by Poker-sang** [comment]
你可以试一下在那个硬盘上直接删除一个文件，看看默认的行为是永久删除还是移动到回收站？
