### ISSUE TITLE
无法覆盖安装

### ISSUE THREAD

**Issue by Rosmontis-III** [Pixeval/Pixeval#379]
### Pixeval的版本

WinUI3

### 问题描述

使用zip版本进行安装后，原本想寻找.exe文件，但是发现找不到，每次用.msic文件启动都很麻烦，也没有办法固定到开始屏幕，但是在B站看到别人用exe的安装有exe文件，于是再次使用exe文件进行安装时发现安装程序报错。使用.bat安装的时候cmd也没提示安装路径是安装到哪里了

### 屏幕截图

![屏幕截图 2024-03-12 224341](https://github.com/Pixeval/Pixeval/assets/47094188/d615aa4b-0537-4c13-a393-a1f361b9f5b9)

### 错误代码

应用安装失败，错误消息: Windows 无法安装程序包 9a360099-e513-45d0-b3f1-3e599691ea06_4.0.0.0_x86__j6rb4ezk9hfnr，因为已安装具有相同名称的不同程序包 9a360099-e513-45d0-b3f1-3e599691ea06_4.0.0.0_x64__j6rb4ezk9hfnr。在安装之前，请删除程序包 9a360099-e513-45d0-b3f1-3e599691ea06_4.0.0.0_x64__j6rb4ezk9hfnr。 (0x80073cf3)

### Windows主要版本

Windows 10

**Comment by Rosmontis-III** [comment]
2024/3/12 补充：使用任务管理器也无法打开运行程序的路径

**Comment by Rosmontis-III** [comment]
2024/3/12 补充：使用任务管理器也无法打开运行程序的路径，但是在客户端内找到了本地文件的文件夹，手动删除appdata/package内的程序包后，报错依旧

**Comment by Poker-sang** [comment]
在开始菜单可以找到图标

**Comment by Poker-sang** [comment]
ps:卸载时候也是在开始菜单邮件点击图标卸载

**Comment by Poker-sang** [comment]
如果你的问题解决了可以关闭这个issue【
