### ISSUE TITLE
设置-默认下载位置，@{manga_index}的输出值是{0}，可以去掉输出中的大括号吗？

### ISSUE THREAD

**Issue by ICI-CNI** [Pixeval/Pixeval#386]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

pixiv的很多第三方下载器如pixivel.moe，pixez在输出文件名的分p序号时都不包含花括号😂可以改一下吗，目前我只能自己写一个程序把图片重命名。需要花括号的人可以给输出宏里手动加入花括号

### 图片

![image](https://github.com/Pixeval/Pixeval/assets/102293568/58fe989d-9019-484a-ae54-80dd1ae77eb7)
![image](https://github.com/Pixeval/Pixeval/assets/102293568/e515feff-8967-4033-99fb-3cf6ddb6e663)

### 其他信息

谢谢！

**Comment by Poker-sang** [comment]
等等这个是图集有几张图片？理论上不会出现{0}二是被替换掉的，应该是一个bug，可以提供一下图片id吗

**Comment by ICI-CNI** [comment]
图集只有一张图片，我想让他输出0。（假如有两张，第一张图输出0，第二张输出1），谢谢👍

**Comment by Poker-sang** [comment]
噢你这不是默认的路径啊，那不是bug了是写错了宏，如果要让他不显示漫画页数，需要加`@{if_manga=xxxx}`的宏

比如这个是默认的路径
```
C:\Users\XXX\Pictures\@{if_spot=@{spot_title}}\@{if_manga=[@{artist_name}] @{illust_title}}\[@{artist_name}] @{illust_id}@{if_manga=p@{manga_index}}@{illust_ext}
```

**Comment by ICI-CNI** [comment]
我好像发现问题出在哪里了。假如不是图集（或者只有一张图片），@{manga_index}的输出值是{0}（而非0），带有花括号；假如图片数量≥2（图集），@{manga_index}的输出值是0，1，2，没有花括号


设置为
`D:\download\@{illust_title}-@{illust_id}-@{manga_index}@{illust_ext}`
假如不是图集（或者只有一张图片），输出是
![image](https://github.com/Pixeval/Pixeval/assets/102293568/79ab1d88-b48e-4305-a3ef-460b98efda37)
（错误）
这种情况下@{manga_index}的输出值能否改成0而非{0}？如下所示
![image](https://github.com/Pixeval/Pixeval/assets/102293568/39c482be-fce0-4640-a68e-ccbb8ec136fa)


假如图片数量≥2（图集），输出是
![image](https://github.com/Pixeval/Pixeval/assets/102293568/932817e2-da94-4186-9f0e-65589cd80351)
（正确）

**Comment by Poker-sang** [comment]
呃，那为什么不用if manga那个宏，那个能直接去掉{0}

**Comment by ICI-CNI** [comment]
因为在不是图集（或者只有一张图片）的情况下，我还想让它输出序号0，而非不输出😂谢谢！
