### ISSUE TITLE
每日推荐建议加入手动刷新选项

### ISSUE THREAD

**Issue by Ponezun** [Pixeval/Pixeval#388]
### 建议类型

新功能

### Pixeval的版本

WinUI3

### 描述

刷图刷着刷着图去看一下载回来都会因为切换页面从而自动刷新每日推荐，可能会导致想看的图片刷没
同时还有个小问题在右键菜单选择下载图片是会导致有几秒不能上下滚动页面

**Comment by Poker-sang** [comment]
第一个问题，由于内存问题离开页面后会清理缓存，所以只要离开了页面就一定会刷新的，还没办法解决

第二个问题是被下方的消息框夺取了焦点所以暂时不能滚动，你可以手动点击一下窗口的任意地方，那样会立即关闭消息框，然后就可以滚动了。我考虑下次可以换成不会夺取焦点的提示方法

**Comment by Ponezun** [comment]
感谢解答，希望可以考虑一下我另外的建议就是收藏图片后会自动下载图片，因为我喜欢下载图片到本地同时这也是手机端app上的一个功能https://github.com/Notsfsssf/pixez-flutter
