### ISSUE TITLE
设置-默认下载位置，输入的任何内容都是透明的

### ISSUE THREAD

**Issue by ICI-CNI** [Pixeval/Pixeval#392]
### Pixeval's version

WinUI3

### Description of the problem

有一个很奇怪的bug，在这个输入框内输入的任何东西都是透明的。使用微软输入法，无论输入中文/英文，全都是透明的。往里面粘贴的任何内容也变成透明的。
必须点击其他页面，再点击设置，才能恢复正常

100%稳定触发，重启程序还是这样

### Screenshot

![image](https://github.com/Pixeval/Pixeval/assets/102293568/e2ab5e0e-cd46-4997-83d0-1ddb0f46d86b)
使用该分支，用visual studio2022构建应用程序

![image](https://github.com/Pixeval/Pixeval/assets/102293568/5289f384-bed8-483c-81b2-6f3ea44e73d1)
手动输入文字后，输入的文字是透明的↑

![image](https://github.com/Pixeval/Pixeval/assets/102293568/33ca5452-f4a0-472e-b9c6-58fdb5ba97b3)
粘贴的任何内容都是透明的，但是被框选后不再透明↑

### Error code

莫名其妙的bug😂

### Windows major version

Windows 11

### Specific Windows version

Insider Build

### Additional Information

😵‍💫😵‍💫😵‍💫

**Comment by ICI-CNI** [comment]
暗黑模式下部分正常

**Comment by ICI-CNI** [comment]
还有一个bug：暗黑模式下重启应用，输入框是这个样子
![image](https://github.com/Pixeval/Pixeval/assets/102293568/18c91bb7-8323-44c4-92a8-e33800c1b14c)
在输入框上一直按ctrl+z撤销快捷键，会变成这个样子
![image](https://github.com/Pixeval/Pixeval/assets/102293568/572436fb-40e6-4913-8d70-5149721e0d71)
继续按，会变成这样
![image](https://github.com/Pixeval/Pixeval/assets/102293568/b582ed4a-c214-4038-a0bb-09e39a897d33)
直到变成这样
![image](https://github.com/Pixeval/Pixeval/assets/102293568/d9e7867e-0d25-43e1-8719-2825a6c0d611)


重启应用后只按了撤销快捷键，没有输入任何文本。这个也是100%触发

**Comment by Poker-sang** [comment]
这个我也遇到过，感觉不好整

**Comment by Poker-sang** [comment]
尽量修了一下，把设置文本框颜色的操作合并为一个了，就不会出现撤销时颜色一个一个消失的bug，但重新染色后第一次撤销时，会删除所有内容（第二次后回到正常，都怪这个破控件）

另外根据不同主题设置了不同文字颜色，“透明”的情况不会出现了

**Comment by ICI-CNI** [comment]
谢谢！
