### ISSUE TITLE
v4.1.0 Releases里面的exe有问题

### ISSUE THREAD

**Issue by YRSB** [Pixeval/Pixeval#396]
### Pixeval的版本

WinUI3

### 问题描述

我尝试下载x64架构的exe进行安装，然后报架构不匹配的错误。我由下载了arm架构的exe，检验发现他们俩的md5是一样的。

### Windows主要版本

Windows 11

**Comment by Poker-sang** [comment]
草【我明明按照它的版本发的，难道是因为没有重新生成吗

已经替换了源了，你再试试看吧

**Comment by lilyblessing** [comment]
x86的也是同arm64

**Comment by YRSB** [comment]
x64已正常。

**Comment by Poker-sang** [comment]
谢谢 @YRSB

**Comment by Poker-sang** [comment]
> x86的也是同arm64

太逆天了，我过会换一下
