### ISSUE TITLE
多选出现问题

### ISSUE THREAD

**Issue by gbwhisper** [Pixeval/Pixeval#397]
### Pixeval的版本

WinUI3

### 问题描述

多选后无法点击取消选择，也无法进行全部保存等操作。

### Windows主要版本

Windows 11

**Comment by Poker-sang** [comment]
这个问题会反复出现吗，有没有复现的方法

**Comment by gbwhisper** [comment]
软件一打开就有，一直会有。

发自我的 iPhone

在 2024年3月21日，00:02，Poker ***@***.***> 写道：

﻿

这个问题会反复出现吗，有没有复现的方法

**Comment by Poker-sang** [comment]
草，原来是加入小说之后没有为多选操作更新状态，导致选了也以为没选，已经修复了
