### ISSUE TITLE
登录时频繁卡死并报错【获取对话失败，请重新启动应用程序】

### ISSUE THREAD

**Issue by ICI-CNI** [Pixeval/Pixeval#398]
### Pixeval's version

WinUI3

### Description of the problem

该问题已经持续很长时间，这次实在忍不了了，提一个issue😂
不禁用前域直连，或者禁用前域直连&旧版steam++，全都会触发这个bug。bug触发时，会在如下所示的页面↓卡死很长很长时间，至少3分钟。随后软件大概率报错【获取对话失败】，小概率登录成功。登录成功后该bug不会再次出现。以前花费10分钟，可以碰运气成功登录，但这次用了半个小时仍然无法登录

经检查，webview2正常安装

v4.0.0.0，v4.1.0.0和他们中间的所有版本（使用visual studio 2022克隆仓库，构造应用）全部有这个bug。用visual studio 2022调试程序，在如下所示↓的页面卡死后，visual studio 2022会报非常多的错误，目测有上百条

### Screenshot

![image](https://github.com/Pixeval/Pixeval/assets/102293568/fb155602-7b1f-416b-80b8-6bf7300708fc)
只会在该页面卡死，从来没有弹出过“请进行reCAPTCHA认证”的红字

### Error code

![image](https://github.com/Pixeval/Pixeval/assets/102293568/94e3d5e7-0088-48bb-bd05-f8d27d44d182)

### Windows major version

Windows 11

### Specific Windows version

Insider Build

### Additional Information

😵‍💫😵‍💫😵‍💫

**Comment by ICI-CNI** [comment]
![image](https://github.com/Pixeval/Pixeval/assets/102293568/dd2b5d7f-61ec-45f3-b271-5897c45bd8df)
就是卡在这个空白页面，右下角有reCAPTCHA的logo，没有报错弹框。我费了九牛二虎之力才登陆成功，不想再退出账号截屏了😂

输入账号密码，确认登录，会有两种情况，1该账号已登录，是否继续使用该账号？2点击登录账号。点击确认后，无论哪种情况都会卡死

不禁用前域直连，也会弹出获取对话失败，只是耗费的时间短一些，大概30秒-90秒。最后禁用前域直连，用steam++卡了很久很久才登录

**Comment by Poker-sang** [comment]
空白页面右下角recaptcha就已经跳转成功了，但是正在获取session【我以后可以在跳转成功之后关闭webview这样就不会认为他卡住了】。

如果长时间不弹窗也不进入，其实一般就是坏了，此时可以想其他办法进入，如挂梯子，用goodbyedpi等

既然你已经进入软件了那就没关系了

**Comment by ICI-CNI** [comment]
“获取对话失败”错误弹窗是没有梯子/代理的缘故吗？

**Comment by Poker-sang** [comment]
并不是只是获取session那个请求失败了，只是说有梯子可能成功【不要好奇去尝试x】你既然编译过这软件应该也能看到那块的逻辑x

**Comment by Poker-sang** [comment]
我发现我不小心把直不直连都用了同一个选项，结果相当于都没有直连x

**Comment by ICI-CNI** [comment]
> 我发现我不小心把直不直连都用了同一个选项，结果相当于都没有直连x

😦
