### ISSUE TITLE
failed to fetch session

### ISSUE THREAD

**Issue by RI-ss** [Pixeval/Pixeval#400]
### Pixeval's version

WinUI3

### Description of the problem

![图片](https://github.com/Pixeval/Pixeval/assets/71321125/c1d34fdf-5557-4528-9763-a209a59b9c9e)
打开内置网页登录后出现如下图片，

### Screenshot

![图片](https://github.com/Pixeval/Pixeval/assets/71321125/3b38697c-b38e-427a-8ea6-8ca4fd30085c)

### Error code

failed to fetch session

### Windows major version

Windows 11

**Comment by RI-ss** [comment]
重复打开都是这个错误

**Comment by Poker-sang** [comment]
正在想办法修复

**Comment by bropines** [comment]
Is that error again?

**Comment by bropines** [comment]
> 重复打开都是这个错误

Can you access the pixiv itself through your browser?
