### ISSUE TITLE
可能出现了内存泄漏

### ISSUE THREAD

**Issue by BlameTwo** [Pixeval/Pixeval#404]
### Pixeval的版本

WinUI3

### 内存泄漏

在使用了五分钟后，我点击了大部分的页面，他的内存在任务管理器中达到了惊人的900MB，当然是连续的，如果静止状态下，大概在780MB左右，我想不明白为什么会这么大，因为我也是一个WinUI3的开发人员。

### 屏幕截图

![image](https://github.com/Pixeval/Pixeval/assets/65759143/aca51de5-57b8-4fee-93f9-ed9608254637)

### Windows主要版本

Windows 11

### 具体Windows版本

Windows 11 22H2 (22621)

**Comment by Poker-sang** [comment]
你可以在windows文件资源管理器多次切换大内存页面【如图库】，你可以发现文件资源管理器内存也下不来

**Comment by BlameTwo** [comment]
这个问题我不确定是不是新的布局容器的问题，因为我实际上没有大规模使用他，我在我的bilistart中依然使用着传统的方格，并没有采用新组件

**Comment by Poker-sang** [comment]
听说是frame和page的原因，但我发现即使不用那两个也会漏内存，没办法

**Comment by Poker-sang** [comment]
你也写winui的话不如加个qq来教我【

**Comment by BlameTwo** [comment]
好好好，我的QQ是3014085426

**Comment by BlameTwo** [comment]
你的是多少，我加你吧
