### ISSUE TITLE
下载不到 

### ISSUE THREAD

**Issue by skyisthela** [Pixeval/Pixeval#405]
### Pixeval的版本

WinUI3

### 问题描述

下载中我开不到msix

### 屏幕截图

![image](https://github.com/Pixeval/Pixeval/assets/150245867/4328a3aa-1c2f-4e38-882b-1fce18ffe08d)

### Windows主要版本

Windows 10

### 具体Windows版本

October 2020 Update/20H2 (19042)

**Comment by Poker-sang** [comment]
下载的不是exe吗，双击运行就好了呀

**Comment by skyisthela** [comment]
> 下载的不是exe吗，双击运行就好了呀

是exe。我按了两下我发的那个照片就跳出来

**Comment by Poker-sang** [comment]
选择第一个，msixmgr

**Comment by skyisthela** [comment]
> 选择第一个，msixmgr

没有用，按那个他开terminal然后什么都没有

**Comment by Poker-sang** [comment]
试试看微软商店里有没有这个应用

![image](https://github.com/Pixeval/Pixeval/assets/62325494/4b47d9bb-62fc-4eb6-b986-ef46db8567f8)

**Comment by Mingri159** [comment]
https://zhuanlan.zhihu.com/p/632626404
按照这个可以解决安装不上的问题；

**Comment by skyisthela** [comment]
> 试试看微软商店里有没有这个应用
> 
> ![image](https://private-user-images.githubusercontent.com/62325494/317236652-4b47d9bb-62fc-4eb6-b986-ef46db8567f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTc1MjEsIm5iZiI6MTcxMTU5NzIyMSwicGF0aCI6Ii82MjMyNTQ5NC8zMTcyMzY2NTItNGI0N2Q5YmItNjJmYy00ZWI2LWI5ODYtZWY0NmRiODU2N2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAzNDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YzNiZWVhYWJhYWU2Y2Q0ZmE3M2UyMDIxM2VjMWZkNGViNjRkMTcxOGE2ZDI0NzkwNWUyNTk0ZjNhMDU1ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h-0aUPPAVsuSvqowNVTvz1GphBxlDMAuJHNVJhtjrs0)

![image](https://github.com/Pixeval/Pixeval/assets/150245867/9fdc783e-bd3e-44e0-b4d1-3a5a3ee8d7e1)

**Comment by skyisthela** [comment]
> https://zhuanlan.zhihu.com/p/632626404 按照这个可以解决安装不上的问题；

winget install pixeval powershell 的时候讲 "找不到符合输入条件的包"

**Comment by Poker-sang** [comment]
这个错误是你安装pixeval出现的，还是安装应用安装程序出现的

**Comment by Mingri159** [comment]
> > https://zhuanlan.zhihu.com/p/632626404 按照这个可以解决安装不上的问题；
> 
> winget install pixeval 的时候讲 "找不到符合输入条件的包"

下载下来的那个文件的文件名和后缀那里有个空格，仔细对照一下，命令不要输错，一下就成了

**Comment by Poker-sang** [comment]
现在可以通过微软商店下载

**Comment by skyisthela** [comment]
> 现在可以通过微软商店下载

ya，那样很方便。谢谢
