### ISSUE TITLE
获取对话失败

### ISSUE THREAD

**Issue by wgasv** [Pixeval/Pixeval#407]
### Pixeval's version

WinUI3

### Description of the problem

登录的时候没有禁用直连，前面都正常，就到最后第一张图片的时候就会直接获取对话失败，有的时候会过一会儿再出现这个问题

### Screenshot

![image](https://github.com/Pixeval/Pixeval/assets/165364659/76513bd4-f639-48fa-bcb4-f2bab30ab6a4)
![image](https://github.com/Pixeval/Pixeval/assets/165364659/4beda197-72a5-444c-a127-ea65cab8a44f)

### Windows major version

Windows 11

**Comment by Poker-sang** [comment]
这个是之前不小心写错了导致的】本来打算在微软商店发布修复版但是到现在没通过，过两天要是还没有我就直接发了。

现在的解决方法是可以禁用直连，然后挂梯子登录，进入应用后再取消禁用直连，这样就可以正常使用了

**Comment by wgasv** [comment]
谢谢

**Comment by n0099** [comment]
https://github.com/Pixeval/Pixeval/issues/398#issuecomment-2016682302

**Comment by wgasv** [comment]
> 这个是之前不小心写错了导致的】本来打算在微软商店发布修复版但是到现在没通过，过两天要是还没有我就直接发了。
> 
> 现在的解决方法是可以禁用直连，然后挂梯子登录，进入应用后再取消禁用直连，这样就可以正常使用了

![image](https://github.com/Pixeval/Pixeval/assets/165364659/c1d5ede2-fe62-4cc9-bacb-e9d491804645)
![image](https://github.com/Pixeval/Pixeval/assets/165364659/df49a184-a4c0-422a-81e4-65b40a952fd8)
后台是挂着梯子的，但是呢打勾了之后又会出现跟不禁用直连时候同样的情况。

**Comment by Poker-sang** [comment]
有没有重启软件软件不能立即动态更换代理

**Comment by wgasv** [comment]
> 理

重启过了，后面我就直接卸掉重下还是一样的，我现在卸了再试一下。

**Comment by wgasv** [comment]
> 有没有重启软件软件不能立即动态更换代理

刚刚删掉重下，突然可以用了。

**Comment by Akarinnnnn** [comment]
![image](https://github.com/Pixeval/Pixeval/assets/43724908/7324b496-829c-4ffa-b3f4-1f1623c60a18)
喜加一，登录过了，reCAPTCHA白屏

**Comment by Poker-sang** [comment]
> 这个是之前不小心写错了导致的】本来打算在微软商店发布修复版但是到现在没通过，过两天要是还没有我就直接发了。

> 现在的解决方法是可以禁用直连，然后挂梯子登录，进入应用后再取消禁用直连，这样就可以正常使用了

这个白屏不是recaptcha，登录已经通过了，如果有recaptcha会出现在登录按钮的上方

**Comment by Akarinnnnn** [comment]
懂了，不过这个版本是从github release下的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月2日(周二) 下午4:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Pixeval/Pixeval] 获取对话失败 (Issue #407)




  
这个是之前不小心写错了导致的】本来打算在微软商店发布修复版但是到现在没通过，过两天要是还没有我就直接发了。
   
现在的解决方法是可以禁用直连，然后挂梯子登录，进入应用后再取消禁用直连，这样就可以正常使用了
  
这个白屏不是recaptcha，登录已经通过了，如果有recaptcha会出现在登录按钮的上方

**Comment by ChSF001** [comment]
目前这个4.1.0还打开频繁闪退捏

**Comment by Poker-sang** [comment]
闪退？是弹出对话框报错吗？按理说不弹框直接崩溃应该很少了才是

**Comment by Poker-sang** [comment]
噗不至于吧，1g左右额外内存，其他应该都没有什么特殊要求吧。另外目前4.1版本会漏内存，可能确实会有内存占用过大的问题，新版本打算在msstore上发布

**Comment by ChSF001** [comment]
我21年的笔记本，Win10 EnterpriseS 2021最新版，配置就算再低也没那么离谱。不过我也想不出其他原因了，毕竟别的应用再怎么卡也只是无响应，也不会闪退，可能真的是内存占用过大应用紫砂了吧。

**Comment by gbwhisper** [comment]
现在也是卡在白屏无法登录了，希望能尽快更新

**Comment by Poker-sang** [comment]
可以试试挂梯子登录登上再关了
