### ISSUE TITLE
程序无法运行

### ISSUE THREAD

**Issue by GanGan1** [Pixeval/Pixeval#410]
### Pixeval的版本

WinUI3

### 问题描述

操作系统版本：Win10 19045.4239 (22H2) 
.NET 8 Runtime 和 Webview 2 均已安装
软件版本 4.1
双击程序后无法运行，没有任何窗口弹出
事件查看器显示缺失ucrtbase.dll

### 错误代码

无错误代码，显示缺失ucrtbase.dll

### Windows主要版本

Windows 10

### 具体Windows版本

19045.4239 (22H2)

**Comment by GanGan1** [comment]
错了，是打开，打字打错了:(

**Comment by Poker-sang** [comment]
双击？你点的是exe吗

**Comment by GanGan1** [comment]
> 双击？你点的是exe吗

是的

**Comment by Poker-sang** [comment]
你关闭issue了，问题解决了吗

exe按理说不会出现打不开的问题啊，你可以试试用管理员模式运行

**Comment by GanGan1** [comment]
> 你关闭issue了，问题解决了吗
> 
> exe按理说不会出现打不开的问题啊，你可以试试用管理员模式运行

额，手抖，是缺失dll文件ucrtbase.dll，没法修:(

**Comment by Poker-sang** [comment]
那这个可能要你自己去找dll下载了，我们这里靠代码无法做到

**Comment by GanGan1** [comment]
> 那这个可能要你自己去找dll下载了，我们这里靠代码无法做到

那能不能麻烦把您电脑上的dll拷一份传一下，网上的我怕不安全，谢谢

**Comment by GanGan1** [comment]
> [ucrtbase.zip](https://github.com/Pixeval/Pixeval/files/14823623/ucrtbase.zip)
> 

嗯嗯，谢谢，晚点去试一下，万分感谢

**Comment by GanGan1** [comment]
> [ucrtbase.zip](https://github.com/Pixeval/Pixeval/files/14823623/ucrtbase.zip)
> 

解决了，系统问题，要Win11，Win10dll文件有问题
