### ISSUE TITLE
暗色 应用程序主题 显示异常 

### ISSUE THREAD

**Issue by xyzWesker** [Pixeval/Pixeval#412]
### Pixeval's version

WinUI3

### Description of the problem

若单纯设置 应用程序主题为暗色，侧边菜单背景色不会改变，导致字体颜色和背景颜色相同看不见。只有同时设置 应用的背景材质 为亚克力材质才能正常显示（4.1.0和4.0.0都存在）

### Screenshot

![QQ截图20240403024135](https://github.com/Pixeval/Pixeval/assets/81094092/3065b5a4-f12e-4949-9233-9bbd565fc0cd)
![QQ截图20240403024158](https://github.com/Pixeval/Pixeval/assets/81094092/b86b4417-12b3-4b63-aa65-39c8cf89b2a9)

### Windows major version

Windows 10

**Comment by Poker-sang** [comment]
这好像是win10独占的bug

**Comment by Poker-sang** [comment]
这个pr修复之后窗口背景、侧边栏之类的可以正常显示，但飞出控件（如tip、菜单等）还是没办法，需要重启才能解决
