### ISSUE TITLE
优化加载缓冲动画

### ISSUE THREAD

**Issue by ICI-CNI** [Pixeval/Pixeval#415]
### The type of your suggestion

Feature optimization

### Pixeval's version

WinUI3

### Description

加载图片时，”正在加载“字样和动画会从图片的缝隙之间露出来，看起来有些违和
可以换一个更好的加载缓冲动画吗？

### Pictures

![屏幕截图 2024-04-06 023715](https://github.com/Pixeval/Pixeval/assets/102293568/6a27db52-fe9f-4503-bb55-87a6c1efc1ef)
”正在加载“的动画本体

![屏幕截图 2024-04-06 023625](https://github.com/Pixeval/Pixeval/assets/102293568/ee4a6aba-4529-4a33-a3ac-1e029aee1a8b)
已有一些图片时，”正在加载“的动画会从图片的缝隙之间露出来

### Additional Information

谢谢！

**Comment by Poker-sang** [comment]
本来想修，后来想想反而可以告诉人正在加载也不错x删了就不知道怎么样表示正在加载了

**Comment by ICI-CNI** [comment]
别急，一定有更好的办法😂

我有一些想法，比如这样：
`-----------------------------------------------`
`|        图片          图片           图片     |`
`|              图片                   图片     |`
`|       图片           加载中的图片（白色方框）|`
`|                  ⭕正在加载                 |`
`-----------------------------------------------`
（加载动画）

`-----------------------------------------------`
`|        图片          图片           图片     |`
`|              图片                   图片     |`
`|   图片   图片    图片          图片          |`
`-----------------------------------------------`
（加载完成）

**Comment by Poker-sang** [comment]
emmm原来打算这样搞的，但滚动条是内置在列表视图里的，列表里只有图片。要做成这种效果，应该要把滚动条作为一张图片放到最底下感觉有点难

**Comment by Poker-sang** [comment]
没想到真的能解决
