### ISSUE TITLE
功能的简要叙述

### ISSUE THREAD

**Issue by Gezhe14** [Pixeval/Pixeval#417]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

我平常都拿pixiv看小说，但是每次点进去作品榜单都得手动切换成小说还有更改榜单，可以出一个保留上一次选择吗？如果有这个功能但是我没看见麻烦说一下，谢谢！

**Comment by Poker-sang** [comment]
暂时没有，可以加

**Comment by Poker-sang** [comment]
现在pixeval的小说功能是新出的，你对小说阅读页有什么建议吗

**Comment by Gezhe14** [comment]
> 现在pixeval的小说功能是新出的，你对小说阅读页有什么建议吗
保留每本书的阅读进度，增加书签（好像没找到），还有收藏似乎只能在封面的左上角点？（而且不太灵敏），如果可以加上这些的话就最好了！我也刚开始用这个软件|∀ﾟ

**Comment by Poker-sang** [comment]
鼠标移动到下半部分出现的小工具栏也可以收藏

**Comment by Gezhe14** [comment]
> 鼠标移动到下半部分出现的小工具栏也可以收藏

哦哦，谢谢，没注意（

**Comment by Gezhe14** [comment]
> 可以拉，可能太细了，你多点几次找找感觉

拉了半天都没拉动，可能是因为屏有点大，最好也优化下吧|д` )

**Comment by Poker-sang** [comment]
喔原来是被下一页的键挡住了，确实拉不了x

**Comment by Gezhe14** [comment]
> 喔原来是被下一页的键挡住了，确实拉不了x

草，速速优化口牙！（
