### ISSUE TITLE
预览图上限1000张？

### ISSUE THREAD

**Issue by gbwhisper** [Pixeval/Pixeval#420]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

超过1000张的图像就不显示了。图像上限似乎是“特辑搜索页数限制”决定的？但这个页数限制最多填100。
我知道这听起来挺离谱的但现在AI作者很多作品超级多。
不知如何解决？加入分页功能会不会比现在的底部不断累加更好？

**Comment by Poker-sang** [comment]
图片加载没有上限，可能纯粹是出bug了，你可以看看日志文件夹有没有新报错

**Comment by gbwhisper** [comment]
> 图片加载没有上限，可能纯粹是出bug了，你可以看看日志文件夹有没有新报错

我能稳定再现这个问题。比如这个作者えにない(88456973)，我正好赶上作者发新图。
这个是第1000张后的状态：
![1](https://github.com/Pixeval/Pixeval/assets/138815633/981822f8-4d53-4a5f-b80c-bdf97b83b7d1)

然后作者正好更新了一张图，于是马上最后一张的状态就变了：
![2](https://github.com/Pixeval/Pixeval/assets/138815633/bb29d3d9-93db-4d48-bfbc-dd2f22dce80c)

**Comment by Poker-sang** [comment]
噢还真有限制，是每日推荐数决定的

**Comment by Poker-sang** [comment]
目前每日推荐数上限是2500，下次我把这个限制取消了

**Comment by Poker-sang** [comment]
![image](https://github.com/Pixeval/Pixeval/assets/62325494/1aaa3f23-09a0-4a9a-9121-3331dca99a1b)

翻到底占了我3g内存，吓人

**Comment by gbwhisper** [comment]
所以说不知道设计成翻页的会不会减少内存占用，比如每页100张啥的

发自我的 iPhone

在 2024年4月11日，13:35，Poker ***@***.***> 写道：

﻿

image.png (view on web)<https://github.com/Pixeval/Pixeval/assets/62325494/1aaa3f23-09a0-4a9a-9121-3331dca99a1b>

翻到底占了我3g内存，吓人

**Comment by BTMuli** [comment]
> ![image](https://github.com/Pixeval/Pixeval/assets/62325494/1aaa3f23-09a0-4a9a-9121-3331dca99a1b)
> 
> 翻到底占了我3g内存，吓人

我一起来就看到扑克在发色图😡🙈👀😋🥰🥰🥰

**Comment by bropines** [comment]
> > ![image](https://private-user-images.githubusercontent.com/62325494/321513799-1aaa3f23-09a0-4a9a-9121-3331dca99a1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NjE5MzQsIm5iZiI6MTcxMjg2MTYzNCwicGF0aCI6Ii82MjMyNTQ5NC8zMjE1MTM3OTktMWFhYTNmMjMtMDlhMC00YTlhLTkxMjEtMzMzMWRjYTk5YTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE4NTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MjYxYWFhYTQxZmM4ODUyZWNjMmU3MWFjZWViMjc4OTc0MGQxNmE3ZGFkY2E0NDhjZWUzMzAwYzcyMjdkZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ELL-0UPABzqwPSs1UNgDgLgSGEj8jJ59FNocGcCkTTY)
> > 翻到底占了我3g内存，吓人
> 
> 我一起来就看到扑克在发色图😡🙈👀😋🥰🥰🥰

Guys, blur out the screenshots, Github can hit you in the ass for doing this -_-

**Comment by Poker-sang** [comment]
Ok I will remove it
