### ISSUE TITLE
主题切换错误

### ISSUE THREAD

**Issue by TwinkleStarDust** [Pixeval/Pixeval#427]
### Pixeval的版本

WinUI3

### 问题描述

切换暗色和亮色主题时是反着的..?如以下动图所示

### 屏幕截图

![动画](https://github.com/Pixeval/Pixeval/assets/108475509/23af0c47-22fe-4f4b-8ffd-9707417bdd0d)

### Windows主要版本

Windows 11

### 具体Windows版本

Windows 11 22H2 (22621)

**Comment by n0099** [comment]
#412 fixed by #413
