### ISSUE TITLE
[Bug Report] GitHub link in settings isn't correct

### ISSUE THREAD

**Issue by FrzMtrsprt** [Pixeval/Pixeval#434]
### Pixeval's version

WinUI3

### Description of the problem

The GitHub link in settings points to an invalid repo address https://github.com/misc2/Pixeval.
It should be updated to https://github.com/Pixeval/Pixeval.

### Screenshot

N/A

### Error code

N/A

### Windows major version

Windows 11

### Additional Information

None

**Comment by Poker-sang** [comment]
噗好丢人的bug，大概是一键替换的时候换错了
