### ISSUE TITLE
可以给收藏和关注列表添加翻页功能吗

### ISSUE THREAD

**Issue by Blacktea213** [Pixeval/Pixeval#435]
### 建议类型

新功能

### Pixeval的版本

WinUI3

### 描述

想找以前收藏的图片或关注的作者需要下滑很长时间，添加翻页功能，比如把收藏夹改成每50张图算一页，再弄一个搜索页数功能。

**Comment by Poker-sang** [comment]
可以加一个从第x个开始浏览的功能

**Comment by Poker-sang** [comment]
现在可以在过滤栏输入 `i:12-` 来跳转，这表示从第12张图开始浏览
