### ISSUE TITLE
深色模式查看图片窗口顶部部分按钮不可见

### ISSUE THREAD

**Issue by xungeshrimp** [Pixeval/Pixeval#436]
### Pixeval的版本

WinUI3

### 问题描述

如题

### 屏幕截图

![image](https://github.com/Pixeval/Pixeval/assets/108598747/8f89717d-816b-4d37-a82d-584ad106a56a)

### Windows主要版本

Windows 11

### 具体Windows版本

Windows 11 22H2 (22621)

**Comment by xungeshrimp** [comment]
怪，重启应用后又可见了

**Comment by Poker-sang** [comment]
是的，主题色更换需要重启解决
