### ISSUE TITLE
下载失败，找不到路径

### ISSUE THREAD

**Issue by Hoogur** [Pixeval/Pixeval#440]
### Pixeval的版本

WinUI3

### 问题描述

当以作品名创建文件夹时，作品名以'...'结尾，创建的文件夹名字尾没有'...'，下载的路径仍按照原作品名下载

### 屏幕截图

![image](https://github.com/Pixeval/Pixeval/assets/93419549/b08a5f80-ab9e-4180-9f19-58c7816e7560)
![image](https://github.com/Pixeval/Pixeval/assets/93419549/8058fbb6-f5fb-4aa6-9588-2db3d0d1f5f6)
![image](https://github.com/Pixeval/Pixeval/assets/93419549/97f0a98a-9b77-4a24-8dfc-02ee23998072)

### 错误代码

![image](https://github.com/Pixeval/Pixeval/assets/93419549/33f63fc5-5892-42e0-9a22-d01d09628721)
![image](https://github.com/Pixeval/Pixeval/assets/93419549/bbb92426-0d0c-4f7d-ae4e-f3b576e864c5)

### Windows主要版本

Windows 10

### 其他信息

![image](https://github.com/Pixeval/Pixeval/assets/93419549/cd81c8a9-d4b8-46a3-8576-d1cc60177c28)

**Comment by Poker-sang** [comment]
大意了x，创建父文件夹时候可能忽略了末尾的...，但在路径中间的时候就没有忽略导致出现问题

**Comment by Hoogur** [comment]
在下载路径中加了别的字符，临时解决了
![image](https://github.com/Pixeval/Pixeval/assets/93419549/84bcd225-b10f-4292-a297-a51099880fdd)

**Comment by Poker-sang** [comment]
啊这里？现在没有spot light功能，理论上这块宏是用不到的啊，为什么能解决问题

**Comment by Hoogur** [comment]
这样生成的文件夹就是以#结尾，也就是'...'在路径中间
![image](https://github.com/Pixeval/Pixeval/assets/93419549/95155dad-d159-448c-9a5a-7e007f5537f6)
![image](https://github.com/Pixeval/Pixeval/assets/93419549/ef6ccd61-6aba-4f08-bc0a-f40911d6a5fc)

**Comment by n0099** [comment]
经典 https://en.wikipedia.org/wiki/Magic_string 及其背后的 https://en.wikipedia.org/wiki/Semipredicate_problem
