### ISSUE TITLE
pixeval 把我怎个文件删掉了？

### ISSUE THREAD

**Issue by skyisthela** [Pixeval/Pixeval#443]
### Pixeval的版本

WinUI3

### 问题描述

我在settings 改下载的地方，因为我不要他弄多一个文件，下载时突然间讲找不到位子在哪里，退回去看到我的文件直接不见掉了。。。 往到粗处找都找不到。他妈的40gb 的文件飞去天堂了。我现在很confused。

### Windows主要版本

Windows 10

### 具体Windows版本

October 2020 Update/20H2 (19042)

**Comment by Poker-sang** [comment]
是因为下载路径和原文件路径重名了吗？请问下载路径和丢失文件路径分别是什么？

**Comment by n0099** [comment]
疑似经典 https://z.n0099.net/#narrow/near/86894

**Comment by skyisthela** [comment]
> 是因为下载路径和原文件路径重名了吗？请问下载路径和丢失文件路径分别是什么？

我本来下载的路是我的 ssd 里面的一个地方，如果下载的时候他不懂怎么有时会弄出来新的一个文件，我不要所以我把那个default location 的东西改一改，改了他下载讲有一些讲早不到那个路，但是在本来下载文件里他会弄出来一个新的文件跟普通的一样但是里面回事没有照片，我也不懂怎么。我把default location 改到那些 @{illust} 的东西删掉，然后我文件直接不见了。没在recycle bin 里面直接真40gb 不见。

**Comment by skyisthela** [comment]
> 疑似经典 https://z.n0099.net/#narrow/near/86894

我华语很烂，读到有点辛苦 T-T

**Comment by n0099** [comment]
> 我华语很烂，读到有点辛苦 T-T

https://github.com/skyisthela/skyisthela.github.io 结合 https://twitter.com/skyisthela/status/1780538144515064251
您大可直接发en

**Comment by Poker-sang** [comment]
你可以试一下在那个硬盘上直接删除一个文件，看看默认的行为是永久删除还是移动到回收站？

**Comment by skyisthela** [comment]
> > 我华语很烂，读到有点辛苦 T-T
> 
> https://osu.ppy.sh/users/17737521 疑似`模吧老人马来壬` https://z.n0099.net/#narrow/near/92736 https://github.com/skyisthela/skyisthela.github.io 结合 https://twitter.com/skyisthela/status/1780538144515064251 https://twitter.com/skyisthela/status/1765319560172044664 ![](https://camo.githubusercontent.com/7aa1803b2c103d6484d7ff06aa594edbab7e62cb76ec7a5e5fb21a30ff0fe6d2/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f47482d7378336d624141413351634b3f666f726d61743d706e67266e616d653d6f726967) 您大可直接发en

oi，你也不用直接dox 我，我是华人只是住在马来西亚。不用麻烦他们。

**Comment by skyisthela** [comment]
> 你可以试一下在那个硬盘上直接删除一个文件，看看默认的行为是永久删除还是移动到回收站？

我也不想理了，那么大的文件她会不给放在recyclebin 里面，会问下我要不要直接删掉。

**Comment by Poker-sang** [comment]
抱歉，软件只能调用系统的默认删除方式，文件被直接删除可能是因为你的那个磁盘没有回收站。

我下次会检查文件夹是否为空后再搜索。

**Comment by n0099** [comment]
> oi，你也不用直接dox 我

https://github.com/sherlock-project/sherlock is just a *click* away

> 我是华人只是住在马来西亚。不用麻烦他们用英文

问题是您在这的zh比推上的en还难理解正如同臭名昭著的`430-四叶话语体系` https://z.n0099.net/#narrow/near/88153

> 那么大的文件她会不给放在recyclebin 里面，会问下我要不要直接删掉。

https://superuser.com/questions/759074/why-does-the-recycle-bin-have-a-size-limit
没找到oldnewthing https://z.n0099.net/#narrow/near/74907 对此的retro
