### ISSUE TITLE
收藏爱心会和白色背景融为一体

### ISSUE THREAD

**Issue by Ponezun** [Pixeval/Pixeval#449]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

佬 我又来反馈问题了收藏爱心建议加一点黑色描边因为很多图背景是白的没有描边的话就啥都看不见了

### 图片

![image](https://github.com/Pixeval/Pixeval/assets/116728910/9317e1e3-22b2-4bb2-8613-f88772ca1009)

**Comment by Poker-sang** [comment]
这个我后来也发现了，已经在下一个版本修复了（浅色主题用黑色描边浅灰色底纹，深色主题用白色描边深灰色底纹）

![image](https://github.com/Pixeval/Pixeval/assets/62325494/1fd994d3-b2f2-46e1-a0e1-76bd3fd0cfaf)
![image](https://github.com/Pixeval/Pixeval/assets/62325494/7c11e63c-27bf-4061-9f2a-4a3961fb5a2c)
