### ISSUE TITLE
”帮助“内存在文本错误

### ISSUE THREAD

**Issue by ICI-CNI** [Pixeval/Pixeval#465]
### Pixeval's version

WinUI3

### Description of the problem

错误太明显了😂有两个下载宏帮助

### Screenshot

![屏幕截图 2024-05-15 214051](https://github.com/Pixeval/Pixeval/assets/102293568/646643d6-c24e-4bee-a026-012a7dd5f4c0)

### Windows major version

Windows 11

### Specific Windows version

Insider Build

**Comment by Poker-sang** [comment]
噢噢还真是
