### ISSUE TITLE
代理类型设置中的代理服务器的内容无效/不保存

### ISSUE THREAD

**Issue by zweie** [Pixeval/Pixeval#474]
### Pixeval's version

WinUI3

### Description of the problem

1. 关闭域前置功能，代理类型设置为任何类型都无效；
2. 代理类型设置为非“系统代理”和“无代理”的另外四种代理类型之一时，输入代理服务器栏中的内容无效/不保存。

- 是通过应用商店安装的版本
- 已确认通过工具关闭了应用的环回限制。

### Windows major version

Windows 11

### Specific Windows version

Windows 11 22H2 (22621)

**Comment by Poker-sang** [comment]
可能需要重启pixeval才能生效，你尝试过重启吗

**Comment by Poker-sang** [comment]
你是用的http代理吗？另外如果代理需要用户名密码现在也暂不支持。你还可以到日志文件夹看看他报的是什么错

**Comment by zweie** [comment]
> 可能需要重启pixeval才能生效，你尝试过重启吗

设置后重启这个确实没试过，尝试过后发现可以使用代理了。

**Comment by Poker-sang** [comment]
还真是，之前空值判断写反了
