### ISSUE TITLE
关于下载功能以及作品浏览的一些功能请求

### ISSUE THREAD

**Issue by zweie** [Pixeval/Pixeval#475]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

- [x] 对下载功能中的路径宏功能的提议：“作品发布日期”选项，并且可以像查询语句语法中的`[date]`那样可以定义。

- [x] 对下载记录的永久保存，以及添加个显示图片是否已下载的标记。因为碰到过画师清除旧作品，清除的作品在收藏中也不会看到了，所以喜欢下载到本地收藏，但经常会重复下载已经下载过的图片。所以希望能够永久保存下载记录，并且显示一个标记提示图片是否已经下载过。

- [x] 对作品浏览的提议：点开作品时自动适应屏幕进行缩放并居中显示。目前打开作品的自动缩放行为会使得图片无法完全显示在屏幕中，如果可以在打开图片时自动将长或宽缩放到适合屏幕，并且居中显示，我想会方便不少。

**Comment by Poker-sang** [comment]
你说的第一个功能就是通过s和e两个一起定义的，发布日期可以指定一个范围，s是最早的日期，e是最晚的日期

**Comment by Poker-sang** [comment]
第三个功能我没理解，现在不是默认适应屏幕吗，你能打开之后截个图看看吗

**Comment by zweie** [comment]
> 第三个功能我没理解，现在不是默认适应屏幕吗，你能打开之后截个图看看吗

目前我这边打开是这样，作品会显示不完全
![屏幕截图 2024-05-23 025905](https://github.com/Pixeval/Pixeval/assets/65338761/47a5c587-f340-4bbe-85ae-50b2915d5d9b)

完整的作品是这样
![屏幕截图 2024-05-23 025925](https://github.com/Pixeval/Pixeval/assets/65338761/6c879edc-7402-4772-8137-5f068cd28262)

而且每次打开的位置似乎经常会不一样
![屏幕截图 2024-05-23 025956](https://github.com/Pixeval/Pixeval/assets/65338761/7dc6b530-c766-47e3-a4ff-5ff9e9f596a9)

**Comment by Poker-sang** [comment]
你这窗口下边缘都超出屏幕了，肯定显示不全啊(。ŏ_ŏ)

**Comment by Poker-sang** [comment]
你这窗口下边缘都超出屏幕了，肯定显示不全啊(。ŏ_ŏ)

**Comment by zweie** [comment]
> 你这窗口下边缘都超出屏幕了，肯定显示不全啊(。ŏ_ŏ)

嗯呐，所以想着希望可以自动缩放长或宽以适应窗口。
![图片](https://github.com/Pixeval/Pixeval/assets/65338761/b69c77b0-13f2-462e-94c7-2967cbf8038b)

就像是截图里这个图片查看器 imageglas (https://github.com/d2phap/ImageGlass)

**Comment by Poker-sang** [comment]
不是很懂，是要缩放图片适应窗口，还是缩放窗口适应图片，还是缩放窗口适应屏幕？

**Comment by zweie** [comment]
> 不是很懂，是要缩放图片适应窗口，还是缩放窗口适应图片，还是缩放窗口适应屏幕？

啊，不好意思，我前后用词用错了。

我是想着，希望能够缩放窗口以适应屏幕。

**Comment by Poker-sang** [comment]
那我统一放在屏幕中心好了

**Comment by ICI-CNI** [comment]
> 那我统一放在屏幕中心好了

点击图片后新弹出来的图片窗口可以默认最大化吗？每次打开窗口后我都得手动把他拖到最上面/按最大化按钮，不然图片下半截显示不出来

**Comment by ICI-CNI** [comment]
第二个功能，目前移动端pixez就可以永久保存下载记录

另外我发现貌似没有删除全部历史记录的按钮？可以加一个吗？非常感谢👍

**Comment by Poker-sang** [comment]
> 第二个功能，目前移动端pixez就可以永久保存下载记录
> 
> 另外我发现貌似没有删除全部历史记录的按钮？可以加一个吗？非常感谢👍

在设置里**重置默认设置**的展开菜单里有

**Comment by ICI-CNI** [comment]
> > 第二个功能，目前移动端pixez就可以永久保存下载记录
> > 另外我发现貌似没有删除全部历史记录的按钮？可以加一个吗？非常感谢👍
> 
> 在设置里 **重置默认设置** 的展开菜单里有

我建议改到外面，下载/浏览/搜索记录放在设置的二级菜单里面真的很反直觉，而且一级菜单的名字叫重置默认设置，和清空记录没有任何关系

**Comment by zweie** [comment]
> 第二个功能，目前移动端pixez就可以永久保存下载记录
> 
> 另外我发现貌似没有删除全部历史记录的按钮？可以加一个吗？非常感谢👍

下载记录这个确实是个人需求的问题，主用电脑的话，那肯定是倾向于在电脑端上有这个功能。

虽然pixez可以永久保存下载记录，但它无法更改下载保存路径及命名方式，而pixeval可以。还有就是，电脑端通常拥有比移动端更大的储存空间，对于下载保存的收藏方案我想会更适合。嗯，储存空间是仓鼠党躲不开的问题。

**Comment by zweie** [comment]
> > 那我统一放在屏幕中心好了
> 
> 点击图片后新弹出来的图片窗口可以默认最大化吗？每次打开窗口后我都得手动把他拖到最上面/按最大化按钮，不然图片下半截显示不出来

默认窗口最大化，可以显示更多的信息，但也会使得一些屏幕空间被浪费，因为不可能每一张图片都几乎或正好填满屏幕。

采用自动缩放窗口以适应屏幕，并且居中显示，可以解决图片显示不全的问题，而且这样更适合电脑上多窗口的操作方式。

所以，如果是默认行为的话，我觉得还是自动缩放窗口以适应屏幕比较好。

**Comment by Poker-sang** [comment]
换了一种实现，不是放在中心，而是如果窗口超出屏幕，就将超出的长度移回。

这个操作本来是windows系统自动完成的，但winui框架把这个操作隐藏了

**Comment by Poker-sang** [comment]
话说下载和浏览记录本来就是永久保存的吧，只是他有上限，在超过50还是100之后会覆盖之前的

**Comment by zweie** [comment]
> 话说下载和浏览记录本来就是永久保存的吧，只是他有上限，在超过50还是100之后会覆盖之前的

目前能设置的上限是200

**Comment by Poker-sang** [comment]
没有上限很危险，如果觉得少可以把上限提到10000

**Comment by zweie** [comment]
> 没有上限很危险，如果觉得少可以把上限提到10000

目前我是通过浏览器油猴脚本来下载记录，去把下载记录导出来看了下，发现有两万多条了🤣

嘛，不过这个我自己也觉得是个蛮小众的需求，而且无限增长的记录当记录过大的时候也确实会给性能带来影响。

**Comment by zweie** [comment]
> 没有上限很危险，如果觉得少可以把上限提到10000

不过主要的还是希望能有一个标识来显示作品下载过。

**Comment by ICI-CNI** [comment]
> > 第二个功能，目前移动端pixez就可以永久保存下载记录
> > 另外我发现貌似没有删除全部历史记录的按钮？可以加一个吗？非常感谢👍
> 
> 下载记录这个确实是个倾向于个人需求的问题，主用电脑的话，那肯定是倾向于在电脑端上有这个功能。
> 
> 虽然pixez可以永久保存下载记录，但它无法更改下载保存路径及命名方式，而pixeval可以。还有就是，电脑端通常拥有比移动端更大的储存空间，对于下载保存的收藏方案我想会更适合。嗯，储存空间是仓鼠党躲不开的问题。

pixez可以改命名方式，你可能没找到

**Comment by ICI-CNI** [comment]
> 考虑到都放在中心就会导致新窗口完全覆盖旧窗口，不好看。所以换了一种实现，不是放在中心，而是如果窗口超出屏幕，就将超出的长度移回。
> 
> 这个操作本来是windows系统自动完成的，但winui框架把这个操作隐藏了。
> 
> 另外如果主窗口最大化，则子窗口也会最大化

我几个月前就觉得是bug（主窗口最大化，但子窗口全都不会最大化）😂但是怕刷屏就没反馈，毕竟当时连着发了两三个issue。4.2.1.0更新后正常了
