### ISSUE TITLE
同时启用多个下载任务时卡顿崩溃

### ISSUE THREAD

**Issue by TGBUG** [Pixeval/Pixeval#479]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

在同时启用多个下载任务时，pixeval会出现很严重的卡顿，量达到一定时，pixeval会无响应（或崩溃）

**Comment by Poker-sang** [comment]
崩溃后日志文件有相关内容吗，请提供一下。
另外发送issue时请选择正确的分类（应选择bug汇报）并撰写题目，以便我们进行归类处理
