### ISSUE TITLE
将@{manga_index}替换为0的代码疑似没有生效

### ISSUE THREAD

**Issue by ICI-CNI** [Pixeval/Pixeval#483]
### The type of your suggestion

Feature optimization

### Pixeval's version

WinUI3

### Description

https://github.com/Pixeval/Pixeval/issues/386 修复问题后一切正常，直到4.2.0.0更新宏的语法

### Pictures

![image](https://github.com/Pixeval/Pixeval/assets/102293568/0cb1c5a5-d91a-47af-b09c-cd47b2c6370b)

下载宏的格式：
![image](https://github.com/Pixeval/Pixeval/assets/102293568/8f110dbd-9913-4c5e-a265-60cf0b4e67cc)

当图集中有>=2张图片时，@{manga_index}输出的序号是正确的（从0开始编号）：
![image](https://github.com/Pixeval/Pixeval/assets/102293568/75fd1113-1495-49bd-86b6-f8654dd20660)

但是如果只有1张图片，@{manga_index}的输出并没有被替换为0，而是直接消失了：
![image](https://github.com/Pixeval/Pixeval/assets/102293568/3ae31a92-ccfc-464f-8807-573e49ac88dc)

将下载宏恢复默认：
D:\Administrator\@{if_illust=Pictures}@{if_novel=Documents}\@{if_manga=[@{artist_name}] @{title}}\[@{artist_name}] @{id}@{if_manga=p@{manga_index}}@{ext}
只把@{if_manga=p@{manga_index}}改成@{manga_index}，上面的问题依旧存在

### Additional Information

非常感谢！👍

**Comment by Poker-sang** [comment]
噢因为添加小说下载之后，宏的逻辑必须去兼容小说所以改变了，因为小说没有MangaIndex原来的写法会崩溃

下次我尝试添加反向宏（比如`@{!if_manga}`）来满足你的需求吧，把MangaIndex悬空使用很容易出问题，也比较难维护

**Comment by ICI-CNI** [comment]
> 噢因为添加小说下载之后，宏的逻辑必须去兼容小说所以改变了，因为小说没有MangaIndex原来的写法会崩溃
> 
> 下次我尝试添加反向宏（比如`@{!if_manga}`）来满足你的需求吧，把MangaIndex悬空使用很容易出问题，也比较难维护

谢谢！

**Comment by Poker-sang** [comment]
4.2.2 版本你可以用 `@{!if_manga=0}` 的语法了

**Comment by ICI-CNI** [comment]
好像还是有点问题😂
![image](https://github.com/Pixeval/Pixeval/assets/102293568/7de11ae9-f982-4fdd-a5c7-e1568d9501a0)
从含有6张图的图集下载图片
![image](https://github.com/Pixeval/Pixeval/assets/102293568/5148a305-90eb-49fa-b09c-e0bcfd09c871)
结果是这样：
![image](https://github.com/Pixeval/Pixeval/assets/102293568/196773f7-9f2c-45b2-9904-7423ba698ea2)

@{!if_manga=0}和@{if_manga=@{manga_index}}同时生效了，但是他们理论上是互斥的

**Comment by Poker-sang** [comment]
坏了还真是】忘了反转反模式的效果了呜呜

**Comment by Poker-sang** [comment]
尽量这个星期把修复的发了吧

**Comment by ICI-CNI** [comment]
😂

**Comment by Poker-sang** [comment]
@ICI-CNI 
更新了4.2.3，因为这次更新很少，几乎只更新了反模式的bug，所以就不release了

本来打算周一发的，结果这次不知道为啥审核了这么久

**Comment by ICI-CNI** [comment]
> @ICI-CNI 更新了4.2.3，因为这次更新很少，几乎只更新了反模式的bug，所以就不release了
> 
> 本来打算周一发的，结果这次不知道为啥审核了这么久

![image](https://github.com/Pixeval/Pixeval/assets/102293568/a67382a3-5ac2-493b-a00a-503d02dad462)
经确认，该宏的功能已经完全恢复正常，非常感谢！另外这个版本的加载图片/加载大图/下载图片速度有明显提升，体感上快了大概一倍👍
