### ISSUE TITLE
用id搜索图片达到一定次数后，无法继续搜索任何图片

### ISSUE THREAD

**Issue by ICI-CNI** [Pixeval/Pixeval#485]
### Pixeval's version

WinUI3

### Description of the problem

如下所述

### Screenshot

4.2.1.0更新后100%触发

触发条件：用不同的图片id（如图片id：112686360）搜索大概几十次图片
![image](https://github.com/Pixeval/Pixeval/assets/102293568/c55bdbe4-db15-410b-ae1c-075d724be0e5)

正常情况下应该是这样：
![image](https://github.com/Pixeval/Pixeval/assets/102293568/e735fc3d-006b-45ff-8313-f6349ca6dcfc)

bug触发后，会变成这样：
![image](https://github.com/Pixeval/Pixeval/assets/102293568/c732819e-f624-4279-ab0d-fa303cd65e1f)
无法加载任何信息，重试很多次都无法加载出来。用别的图片id测试，仍然无法加载任何信息

bug还有以下特征：
1.“下载”中所有图片的缩略图全部消失
![image](https://github.com/Pixeval/Pixeval/assets/102293568/a99dbc52-f934-4045-a74b-ab970fb9808d)

2."下载与历史“上面所有的栏目全都无法加载，会变成这样
![image](https://github.com/Pixeval/Pixeval/assets/102293568/441a35b4-9407-437b-8de3-57d44204bb3a)

3.点击历史记录中任意一个还能加载缩略图的图片，比如这张：
![image](https://github.com/Pixeval/Pixeval/assets/102293568/515fe781-3185-483c-983d-fb72d1c9d080)
图片仍然可以加载出来，但是点击作者头像：
![image](https://github.com/Pixeval/Pixeval/assets/102293568/96d46fcd-c694-4044-ace1-49c4bd41e8c2)
无法加载出作者的任何信息：
![image](https://github.com/Pixeval/Pixeval/assets/102293568/9e475c08-a96a-4ec1-90d0-39e17cc9e26e)

只有重启软件才能恢复正常。bug出现时，没有发现内存泄漏等其他异常

重启软件后，出bug的图片还留在历史记录里面：
![image](https://github.com/Pixeval/Pixeval/assets/102293568/1dca1218-12b8-43cb-91ac-534107e8410e)
画红圈的两张图其实是同一张图片

### Windows major version

Windows 11

### Specific Windows version

Insider Build

### Additional Information

谢谢！👍

**Comment by Poker-sang** [comment]
我试了二三十次也没有发现这个问题？你可以看看你的日志文件吗？我怀疑可能是短时间请求太多导致撞速率上限了。

另外你可以试试能不能复现

**Comment by Poker-sang** [comment]
大概知道了，可能是偶尔网络波动或者确实作品被删了，然后点开就获取到id0，并且被历史记录下来。

历史记录中这个就是0了，而不是原来的id
