### ISSUE TITLE
下载图片时位置出错

### ISSUE THREAD

**Issue by wellgpt** [Pixeval/Pixeval#490]
### Pixeval的版本

WinUI3

### 问题描述

我希望将图片保存到D盘,然而它提示目录名不正确,它试图保存到C盘并出现了C:\D:\xxx的情况

### 屏幕截图

![捕获](https://github.com/Pixeval/Pixeval/assets/171525738/7fc830aa-7b59-4682-9dd9-a94c10d4513e)
![捕获1](https://github.com/Pixeval/Pixeval/assets/171525738/0da11b1d-b92e-49ef-9015-ae5b1e8a29ac)

### Windows主要版本

Windows 10

**Comment by Poker-sang** [comment]
你d盘的d前面多了一个冒号

**Comment by wellgpt** [comment]
谢谢，删除斜杠后问题解决了

**Comment by wellgpt** [comment]
谢谢，删除斜杠后问题解决了
