### ISSUE TITLE
保存图集时只存一张图

### ISSUE THREAD

**Issue by MystFeng** [Pixeval/Pixeval#492]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

保存一个图集，或点击喜欢来保存时，只会保存我看到的那一张，而不保存其它图片。
希望能把保存功能做成一次保存图集里的所有图！

**Comment by Poker-sang** [comment]
现在可以用外面缩略图列表的保存，那个是保存图集的

![image](https://github.com/Pixeval/Pixeval/assets/62325494/8be9dedf-91a1-4f9f-afe7-0a6234290132)

以后可以在浏览页加一个保存图集的按钮
