### ISSUE TITLE
下载路径问题

### ISSUE THREAD

**Issue by Prixii** [Pixeval/Pixeval#496]
### Pixeval's version

WinUI3

### Description of the problem

版本：`4.2.2.0` 

系统：Win 11 22h2 22621.3593

提示“下载失败：文件名、目录名或卷标语法不正确。”

不知道为啥在路径前面固定会出现 C 盘符

而且重启软件之后就默认变成了下载完成的状态

### Screenshot

![image](https://github.com/Pixeval/Pixeval/assets/87805157/53cc4bc4-b767-42d7-9906-612952d90698)

下载位置正则：`\@{if_illust=D:\Pixiv}@{if_novel=D:\Documents}\@{if_manga=[@{artist_name}] @{title}}\[@{artist_name}] @{id}@{if_manga=p@{manga_index}}@{ext}`

重启之后变成了下载完成的状态，但是实际上并没有：
![image](https://github.com/Pixeval/Pixeval/assets/87805157/cf455f03-6702-4266-a3ac-5218e1d974e3)

### Windows major version

Windows 11

**Comment by Poker-sang** [comment]
因为最前面写了一个斜杠，他就会解析为：\D:\然后自动补上一个盘符

好像是初始化路径时候的问题，下个版本会修一下
