### ISSUE TITLE
Fuzzy picture even when opened in full screen 

### ISSUE THREAD

**Issue by bropines** [Pixeval/Pixeval#505]
### Pixeval's version

WinUI3

### Description of the problem

On the last commit (main branch), images are not loaded when opened

### Screenshot

https://github.com/Pixeval/Pixeval/assets/57861007/cd3214f1-d7f8-4f44-9a2c-9578f9811e50

### Windows major version

Windows 11

### Specific Windows version

Windows 11 22H2 (22621)

**Comment by Poker-sang** [comment]
Do you mean original image? There is a settings item that specify weather pixeval will load original image

**Comment by bropines** [comment]
> Do you mean original image? There is a settings item that specify weather pixeval will load original image

I'll check as best I can, if I fix it, I'll close the issue. Sorry
