### ISSUE TITLE
窗口无法调整大小+无响应

### ISSUE THREAD

**Issue by BeaconP** [Pixeval/Pixeval#509]
### Pixeval的版本

WinUI3

### 问题描述

1. 无法通过标题栏最大化窗口，只能手动拖拽调整窗口大小
    - 且拖动了后有概率只渲染原窗口区域，并且程序整体无响应
 2. 打开图片预览后预览窗口无法关闭
[2024-06-26 18.log](https://github.com/user-attachments/files/15986277/2024-06-26.18.log)

### Windows主要版本

Windows 11

### 具体Windows版本

Windows 11 22H2 (22621)

**Comment by Poker-sang** [comment]
有可能是标题栏还没刷新，这个也许下个版本能修

你现在可以先调整一下窗口大小手动触发刷新，然后就可以最大化之类的操作了
