### ISSUE TITLE
“过滤作品”增加对横/竖图片的支持

### ISSUE THREAD

**Issue by Waximell** [Pixeval/Pixeval#511]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

给现在筛选的语句增加类似“x≥y”和“x≤y”的筛选支持，以供仅显示横图/竖图

### 其他信息

现在的过滤作品可以通过语句和正则完成绝大多数筛选已经很方便了，不过在给电脑挑选壁纸时突然想到：能否只看横向的图片，遂来提出此功能建议。
然后，目前可以想到的可能导致bug的情况：
正方形图片，正方形的可以两种筛选都不被筛选掉
图组内的复数图片大小不一，直接按第一张图的尺寸过滤

**Comment by Poker-sang** [comment]
这个虽然加起来比较容易，但只能图片用不能小说用，可能还得考虑一下怎么设计用法比较好

**Comment by Waximell** [comment]
> 这个虽然加起来比较容易，但只能图片用不能小说用，可能还得考虑一下怎么设计用法比较好

emm，我从来没在pixiv上看过小说，没朝这个方向考虑过。
我想到这个的时候是挑壁纸的时候，而且需要筛选横竖应该也仅限图片吧，那就无论横竖都把小说筛掉？我觉得应该可以。然后在每个页面选择小说子项的时候此过滤不生效，这样应该就不会筛不出卡死了。
或者，每次筛横竖的时候都默认把所有小说留下？判定的时候写“x>y或x=y或xy不存在”这样的逻辑？

**Comment by Waximell** [comment]
> 这个虽然加起来比较容易，但只能图片用不能小说用，可能还得考虑一下怎么设计用法比较好

请问是否有计划添加这个功能呢？

**Comment by kokoro-aya** [comment]
目前的设想是增加一个语法来过滤特定比例的图片，语法暂定为r:前缀（也就是ratio），后面接的范围/集合使用现有的语法，不过除了整数外，范围也支持小数或者比例。

换句话说，1.0、2、4/3都是有效的范围的组成部分，比如说，r:2/3-筛选出横宽比大于2/3的图片，r:-1过滤横宽比不到1.0的图片，r:1-2把横宽比限定在1和2之间。

因为小说和图片不会出现在同一个页面上，所以预期的效果是添加r:过滤条件的时候，小说是会被排除出去的。
