### ISSUE TITLE
图片标题过长导致预览窗口功能按钮重叠

### ISSUE THREAD

**Issue by xyzWesker** [Pixeval/Pixeval#516]
### Pixeval's version

WinUI3

### Description of the problem

如标题

### Screenshot

![QQ截图20240723160239](https://github.com/user-attachments/assets/fa4ad35f-a2e1-44e1-b203-e82ff8f73cdc)

### Windows major version

Windows 10

**Comment by Poker-sang** [comment]
咦我之前加了限制长度的，可能哪次更新不小心删了
