### ISSUE TITLE
内存占用过高以及程序崩溃

### ISSUE THREAD

**Issue by TheresaQWQ** [Pixeval/Pixeval#518]
### Pixeval's version

WinUI3

### Description of the problem

内存占用过高，以及同时下载大量图片时会卡顿并崩溃

### Screenshot

![image](https://github.com/user-attachments/assets/78fa5d2b-1fda-434f-b59e-d718b8ba4bec)
![image](https://github.com/user-attachments/assets/0e257e8e-8d16-4c38-97e9-3e43452cb614)
![image](https://github.com/user-attachments/assets/86d2b117-3773-44f3-b6f1-133e4b1bc807)

### Windows major version

Windows 11

### Specific Windows version

Windows 11 22H2 (22621)

**Comment by Poker-sang** [comment]
下载时候大量占用内存的问题已经在最新的commit里大体解决了，卡顿问题目前是框架固有问题，可以等winui3的下一个版本看看效果

**Comment by Poker-sang** [comment]
这个版本应该解决了相当一般分内存问题
