### ISSUE TITLE
下载路径优化

### ISSUE THREAD

**Issue by RuiDSaaCC** [Pixeval/Pixeval#528]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

下载图集（多图片插画）时，选择保存为漫画，下载路径会同时判断下载目标为图片和漫画，导致 @{if_manga=} 和 @{if_illust=} 冲突（表现为两个条件均为真）。如果直接仅使用 @{if_illust=} 设置下载路径，即使使用保存为漫画也只会下载图集的第一张图片（文件名无法使用 @{manga_index} ）。
由于我插画和漫画并没有保存在同一目录下，所以无法使用 @{if_manga=} 嵌套到 @{if_illust=} 的方法。
希望能在设置中将小说、插画和图集分别设置路径，或者引入能解决冲突的方法、
补充：突然想起来可以拿 @{!if_manga=} 嵌套到 @{if_illust=} 解决问题，不过这样多级嵌套可读性太差了（下面还有层R18路径拆分），还是分别设置路径比较好。

**Comment by Poker-sang** [comment]
本来也确实打算做 单图，多图，图片 三种条件的，但没想到单图用什么英文比较好，你有什么想法吗

**Comment by RuiDSaaCC** [comment]
> 本来也确实打算做 单图，多图，图片 三种条件的，但没想到单图用什么英文比较好，你有什么想法吗

这种东西就不要纠结了吧，哪怕叫 single_image 也行，反正鼠标指上去也有说明。
或者写成 pic_all（所有图片）、pic_one（单张图片）pic_set（多张图片）

**Comment by dylech30th** [comment]
> > 本来也确实打算做 单图，多图，图片 三种条件的，但没想到单图用什么英文比较好，你有什么想法吗
> 
> 这种东西就不要纠结了吧，哪怕叫 single_image 也行，反正鼠标指上去也有说明。 或者写成 pic_all（所有图片）、pic_one（单张图片）、pic_set（多张图片）

支持，本来想用singleton/multiple/all的，想了想还是你这种更直白学习成本更低

**Comment by RuiDSaaCC** [comment]
> 本来也确实打算做 单图，多图，图片 三种条件的，但没想到单图用什么英文比较好，你有什么想法吗

如果可以的话，建议加个小说的系列判定，这样单独把系列小说放到一个文件夹，非系列小说集中放单独文件夹了。

@{if_novel_series=}：如果是系列小说
@{novel_series_id}：系列小说的ID
@{novel_series_title}：系列小说的标题
小说在系列的序号不知道能不能获取到

**Comment by Poker-sang** [comment]
小说系列的api还没做】

**Comment by cicadaidae** [comment]
为啥我用@{if_illust=@{if_manga=@{id}_p@{manga_index}@{ext}}@{!if_manga=@{id}_p0@{ext}}}也还是不行，漫画文件名变两层，单图则找不到下载路径，是我漏了啥吗
