### ISSUE TITLE
下载小说时，无法自动创建路径文件夹

### ISSUE THREAD

**Issue by RuiDSaaCC** [Pixeval/Pixeval#529]
### Pixeval's version

WinUI3

### Description of the problem

@{if_novel=D:\小说保存路径\［Pixiv＃@{artist_id}］@{artist_name}\［@{id}］@{title}}

小说保存在作者文件夹下，但如果不预先创建作者文件夹就下载则会报错 “”下载失败: Could not find a part of the path“” ，在使用类似的路径下载图片时会自动创建文件夹。

### Windows major version

Windows 11

**Comment by Poker-sang** [comment]
虽然没有复现你说的问题，但确实发现没有图的小说下载时会出现问题。

另外你的例子中的路径缺少文件扩展名，可能导致问题
