### ISSUE TITLE
A brief description of the bug

### ISSUE THREAD

**Issue by SchwarzShadow** [Pixeval/Pixeval#532]
### Pixeval's version

WinUI3

### Description of the problem

Не работает вход без впн в России, вхожу через webview, после перезахода в приложение снова сбрасывает на страницу входа

### Windows major version

Windows 11

**Comment by bropines** [comment]
Не ну братан, ну вообще-то он заблокирован в рф. В приложении предусмотрено прокси. Чисто теоретически ты можешь включить/отключить доменное фронтирование(это я переводил). У тебя сейчас из вариантов
VPN, DPI, прокси. Я могу помочь но вар ков у тебя мало.

**Comment by SchwarzShadow** [comment]
Сам лично пользуюсь NekoRay, но способ с прокси был бы удобнее. Подскажешь как сделать?

**Comment by bropines** [comment]
> Сам лично пользуюсь NekoRay, но способ с прокси был бы удобнее. Подскажешь как сделать?

Все пользуются некореем. По хорошему чтобы без проблем, мог бы юзать 
https://github.com/ValdikSS/GoodbyeDPI
https://github.com/Flowseal/zapret-discord-youtube

и он будет обходить 90 процентов бана без лишних прокси но в случае GoodBye будет проблема с подбором параметров.

В случае с впн от некорея, он умеет в сокс прокси сервер, но для начала чтобы настроить его в PIXEVAL надо войти в приложение под TUN режимом(на всю систему). Затем настройки и добавляешь как SOCKS5 прокси. Увы я в отьезде, пока только так могу подсказать

**Comment by SchwarzShadow** [comment]
а в чем юмор собственно, в приложении в настройках в шапке написано работает без прокси в китае и россии

**Comment by bropines** [comment]
> а в чем юмор собственно, в приложении в настройках в шапке написано работает без прокси в китае и россии

Ну тестили весной. Увы ркн все больше начинает насиловать трафик, изза чего он теперь нормально не работает. Ну и летом мы учитывали DPI в некоторых местах, и без него. Увы там у каждого региона разный результат. Поставь goodbyedpi  и по факту починит. Если нет, мы добавим прокси и что-нибудь для обхода. В китае он не забанен, а просто не проходит FIREWALL, а вот у нас он заблочен, включая постоянно дополняющиеся списки IP.

**Comment by SchwarzShadow** [comment]
и ещё: при регистрации через браузер (в моём случае edge) вроде как действует таблетка, только вот после входа в акк в браузере, в приложении он не входит

**Comment by SchwarzShadow** [comment]
можете сделать что то типа обхода SNI как в pixez на андроид?

**Comment by Poker-sang** [comment]
pixeval uses the exact same bypass logic as pixez, even the ip is the same.

If pixez works and pixeval that's weird.

**Comment by bropines** [comment]
> можете сделать что то типа обхода SNI как в pixez на андроид?

Оно и так так работает. Ладно, давай вечером в дисе я тебе все починю, так же соберу логи для Poker-sang.

**Comment by bropines** [comment]
Тут такой прикол что трафик с пк имеет иной TTL, нежели чем андроид. И пиксез работает, но вот на Винде такой обход sni крайне багованный. У меня на основном пк он тоже перестал работать, причем везде, так что я найду способ обхода и мы добавим его на будущее в readme.

**Comment by bropines** [comment]
> и ещё: при регистрации через браузер (в моём случае edge) вроде как действует таблетка, только вот после входа в акк в браузере, в приложении он не входит

Тебе все ещё нужна помощь с настройкой?
И да походу пиксив изменил способ входа приложений и почему то у меня тоже не получается токен при использовании браузера. Я проверю позже что не так.

**Comment by SchwarzShadow** [comment]
Пока всё на nekoray сижу, буду рад если поможете с иным способом входа, чтобы не открывать сторонние приложения, а всё действие происходило в pixeval

**Comment by bropines** [comment]
> Пока всё на nekoray сижу, буду рад если поможете с иным способом входа, чтобы не открывать сторонние приложения, а всё действие происходило в pixeval

Мой TG @bropines и дискорд такой же. Напишите, созвонимся, или спишемся, чтобы быстро все настроить.
