### ISSUE TITLE
推荐作品屏蔽标签后，出现排序错位问题。

### ISSUE THREAD

**Issue by fartouch** [Pixeval/Pixeval#538]
### Pixeval的版本

WinUI3

### 问题描述

在每日推荐中，屏蔽了部分标签，但是依然展示带有被屏蔽的标签的插画，点击插画A的小图，试图预览A的图，这时显示的不是插画A，而是另一幅插画，排序错乱。
同时，伴随着卡顿问题。界面响应慢，加载慢。

### 错误代码

日志
[2024-11-05 07.log](https://github.com/user-attachments/files/17624910/2024-11-05.07.log)

### Windows主要版本

Windows 11

**Comment by dylech30th** [comment]
这个好像是用了 Community 的控件导致的问题，那个控件排序的问题很多，我之前也注意到了，最近看看

**Comment by Poker-sang** [comment]
你用的是全局屏蔽标签还是筛选语法标签？我两个都试了都没有出现这些问题，可以提供复现的方法吗

**Comment by fartouch** [comment]
应该是全局屏蔽标签，复现此bug的方法：
在【每日推荐】里，假设图片的顺序是1234567，随便选择一张图片3，点击并进去查看这个图片3，再点击左下角的【感叹号图标】查看图片详情，然后在作品标签中选择一个，鼠标右键点击并且屏蔽，再回到【每日推荐】，鼠标左键点击图片4进去，看到的却是图片6.
此邮件附件中提供实际使用中出现此bug的视频。
         原始邮件
         
       
发件人：                  Poker         ***@***.***                 
发件时间：         2024年12月31日 17:21 
收件人：                  Pixeval/Pixeval         ***@***.***                 
抄送：                  Zhu Yanfei         ***@***.***         ,                Author         ***@***.***                 
主题：         Re: [Pixeval/Pixeval] 推荐作品屏蔽标签后，出现排序错位问题。 (Issue #538) 




你用的是全局屏蔽标签还是筛选语法标签？我两个都试了都没有出现这些问题，可以提供复现的方法吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.


 	
 	 		 			从QQ邮箱发来的超大附件 	
 	 		 				 					 						 							 						 					
 					 						 							Pixeval&nbsp;sort&nbsp;Bug.mp4 							 (81.2MB, 2025年1月30日 18:37) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=cfca1461692ad5aefdb94a6132356565d5d3766430356565181a09071f00525407565c04541803065453495554025448080356571d035357000201520257555204216431594d0013515944125f4711457240034f5d455171ba16fd4ab1151077fd3218f6f3ebf025de078e1a3135656530356461&key=cfca1461692ad5aefdb94a6132356565d5d3766430356565181a09071f00525407565c04541803065453495554025448080356571d035357000201520257555204216431594d0013515944125f4711457240034f5d455171ba16fd4ab1151077fd3218f6f3ebf025de078e1a3135656530356461&code=05da05ee&from=

**Comment by Poker-sang** [comment]
谢谢，等我回去看看

**Comment by Poker-sang** [comment]
屎山改不动了，只能临时把设置项读出来做个备份
