### ISSUE TITLE
无法登录，叫什么421错误。

### ISSUE THREAD

**Issue by ndyzjsndy** [Pixeval/Pixeval#542]
昨天好好的，今天就没法子了

重新登录显示这种，我没有开任何vpn，禁用域名都是不行
![屏幕截图 2024-12-04 133854](https://github.com/user-attachments/assets/a7e1d6cb-c10c-4a60-af0c-e2d87feff268)

**Comment by ndyzjsndy** [comment]
是要重新安装，还是要调网络，另外总是有点卡

**Comment by Poker-sang** [comment]
如果昨天能登录的话，那可以用令牌登录，软件应该还储存了昨天的令牌

**Comment by ndyzjsndy** [comment]
> 如果昨天能登录的话，那可以用令牌登录，软件应该还储存了昨天的令牌

我就是令牌登不上才考虑重登

**Comment by ndyzjsndy** [comment]
![屏幕截图 2024-12-04 135446](https://github.com/user-attachments/assets/5c75e1fd-bbeb-4fa2-8270-89bfafb23d36)

**Comment by Poker-sang** [comment]
好像是pixiv问题，我试了一下确实出现问题了，看vpn之后可以正常使用

**Comment by Poker-sang** [comment]
令牌登不上也是同样问题导致的

**Comment by Poker-sang** [comment]
可以跟踪一下pixez的issue：https://github.com/Notsfsssf/pixez-flutter/issues

pixeval和pixez用了同样的技术，回头修复时应该会参考pixez

**Comment by Poker-sang** [comment]
临时解决方案：使用VPN登录之后将域前置的名字解析器都设为`210.140.139.155`

![image](https://github.com/user-attachments/assets/be8598b2-31f6-4d95-a70e-12b1bc2656a8)

**Comment by youmu1** [comment]
请问421问题是已经fix了然后重新打包吗？
我下载最新的应用依旧存在

**Comment by Poker-sang** [comment]
修复版还没推呢

**Comment by youmu1** [comment]
哦哦，我看到已经close了，就以为已经修复了

**Comment by ndyzjsndy** [comment]
请求下次能够无需登陆直接修改域前置

**Comment by Poker-sang** [comment]
确实打算这样做

**Comment by SuanOrange** [comment]
> 临时解决方案：
> 
> ### 方法1（推荐）
> 1. 打开全局代理（VPN）
> 2. 打开Pixeval
> 3. 选择WebView2登录、关闭域前置
> 4. 点登录
> 5. 进入软件后将域前置的名字解析器都设为`210.140.139.155`
>    ![image](https://private-user-images.githubusercontent.com/62325494/392262073-be8598b2-31f6-4d95-a70e-12b1bc2656a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTI3NzQsIm5iZiI6MTczNDYxMjQ3NCwicGF0aCI6Ii82MjMyNTQ5NC8zOTIyNjIwNzMtYmU4NTk4YjItMzFmNi00ZDk1LWE3MGUtMTJiMWJjMjY1NmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEyNDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNWI1YWRlNTlhMTVhMmFjYmM4OWE0ZWUxMjUwODdiOGQxMDY1YTMwZDhlMGY4NTc2ZmVlMTNiZWQ4Mzg1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M2IwK3tiyJFN30MoPyqhwxxUp3fLnXF45puyDpWG_rU)
> 
> ### 方法2（覆盖设置）
> 1. 打开路径 %LOCALAPPDATA%\Packages\PokerKo.4454907E5DDB5_0wpjzgvbyjvyr\Settings
> 2. 将以下文件解压并覆盖目录中的settings.dat，再次打开Pixeval即可
>    [settings.zip](https://github.com/user-attachments/files/18048022/settings.zip)

使用方法1会出现图片全部无法显示的问题
![Snipaste_2024-12-19_20-52-17](https://github.com/user-attachments/assets/f2d7728d-6c0d-4542-b513-55eee54c21e6)
使用方法2直接失败

**Comment by SuanOrange** [comment]
> 临时解决方案：
> 
> ### 方法1（推荐）
> 1. 打开全局代理（VPN）
> 2. 打开Pixeval
> 3. 选择WebView2登录、关闭域前置
> 4. 点登录
> 5. 进入软件后将域前置的名字解析器都设为`210.140.139.155`
>    ![image](https://private-user-images.githubusercontent.com/62325494/392262073-be8598b2-31f6-4d95-a70e-12b1bc2656a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTI3NzQsIm5iZiI6MTczNDYxMjQ3NCwicGF0aCI6Ii82MjMyNTQ5NC8zOTIyNjIwNzMtYmU4NTk4YjItMzFmNi00ZDk1LWE3MGUtMTJiMWJjMjY1NmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEyNDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNWI1YWRlNTlhMTVhMmFjYmM4OWE0ZWUxMjUwODdiOGQxMDY1YTMwZDhlMGY4NTc2ZmVlMTNiZWQ4Mzg1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M2IwK3tiyJFN30MoPyqhwxxUp3fLnXF45puyDpWG_rU)
> 
> ### 方法2（覆盖设置）
> 1. 打开路径 %LOCALAPPDATA%\Packages\PokerKo.4454907E5DDB5_0wpjzgvbyjvyr\Settings
> 2. 将以下文件解压并覆盖目录中的settings.dat，再次打开Pixeval即可
>    [settings.zip](https://github.com/user-attachments/files/18048022/settings.zip)

同时使用方法1会出现无法登陆的问题
![Snipaste_2024-12-19_20-55-19](https://github.com/user-attachments/assets/0b19df85-8e00-472b-b2b3-acebabaff6f1)

**Comment by yuopera** [comment]
> @SuanOrange 方法1里不要改pximg的ip，改了会有问题
这好像是新的问题，原本已经用方法2解决。今天出现了上述的image not availab。

**Comment by Poker-sang** [comment]
@yuopera 还真是，估计pximg的ip又换了，还是等别人提供新的ip吧

**Comment by Poker-sang** [comment]
@SuanOrange @yuopera 将i.pximg.net和s.pximg.net的IP都换为`210.140.139.133`

**Comment by yuopera** [comment]
请问有类似方法二不登陆就解决的办法吗

**Comment by Poker-sang** [comment]
pximg ip问题不影响登录，所以我没提供新的覆盖用的设置

**Comment by yuopera** [comment]
![屏幕截图 2024-12-19 230446](https://github.com/user-attachments/assets/cda05788-c34b-4688-b471-999236a0467d)
不会出现登录问题吗...可我和上面那个人都有登录问题，这又是另外的问题？

**Comment by yuopera** [comment]
我这次用法二登不上去

**Comment by SuanOrange** [comment]
> 我这次用法二登不上去

法二似乎失效了

**Comment by yuopera** [comment]
我这边是这样的，前些天通过法二登上去了。今天图片不显示，但自动登录可行。我鲁莽了直接删了软件再用一遍法二，结果如上图。同时，上面那个人提到法二直接失败，但没图，和我可能是一个问题。

**Comment by yuopera** [comment]
哦，人家也来了

**Comment by yuopera** [comment]
哦，那考试要紧，祝你顺利

**Comment by yuopera** [comment]
> > 我这次用法二登不上去
> 
> 法二似乎失效了

你法一现在能登上去吗?

**Comment by SuanOrange** [comment]
> > > 我这次用法二登不上去
> > 
> > 
> > 法二似乎失效了
> 
> 你法一现在能登上去吗?

现在可以登录

**Comment by SuanOrange** [comment]
> > > 我这次用法二登不上去
> > 
> > 
> > 法二似乎失效了
> 
> 你法一现在能登上去吗?

现在可以登录，不知道是不是我改了解析器的缘故

**Comment by ChSF001** [comment]
> > > 我这次用法二登不上去
> > 
> > 
> > 法二似乎失效了
> 
> 你法一现在能登上去吗?

贴个目前的法二配置
![397405402-ce652075-2a5c-45c1-8901-3eb4d73a9d10](https://github.com/user-attachments/assets/21fa235b-7bef-4751-95e7-4bebbeef2d16)

**Comment by zjz-562** [comment]
使用方法一修改域前置两个IP，但关注新作缩略图无法正常显示
![Uploading 屏幕截图 2024-12-22 213621.png…]()
![Uploading 屏幕截图 2024-12-22 214323.png…]()

**Comment by zjz-562** [comment]
> > > > 我这次用法二登不上去
> > > 
> > > 
> > > 法二似乎失效了
> > 
> > 
> > 你法一现在能登上去吗?
> 
> 贴个目前的法二配置 ![397405402-ce652075-2a5c-45c1-8901-3eb4d73a9d10](https://private-user-images.githubusercontent.com/75877757/397480253-21fa235b-7bef-4751-95e7-4bebbeef2d16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzU1NDAsIm5iZiI6MTczNDg3NTI0MCwicGF0aCI6Ii83NTg3Nzc1Ny8zOTc0ODAyNTMtMjFmYTIzNWItN2JlZi00NzUxLTk1ZTctNGJlYmJlZWYyZDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDEzNDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNjYxOGZkZjNhNzRhZDUxOTNiMWUxNGE3NDRkNmQ4YjI1YjMxMDJkYzJjY2JhYTk1ZjYyZjE4YzBmM2UwM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8T0cp2iBhH-LJ63Syf3FC7AY-aUIZjJpHuz4pEHSROs)

210.140.139.135这个IP可以使用，改完IP记得清空文件缓存或者把使用文件缓存关掉，不然关注新作缩略图会读缓存显示错误

**Comment by Poker-sang** [comment]
现在可以用改过ip的新版本了，但新版本会让你重新登陆，可以提前保存登录页的刷新令牌

**Comment by Poker-sang** [comment]
只是当时没想到这里ip也会变，所以没留这块的后门
