### ISSUE TITLE
无法登录 421错误

### ISSUE THREAD

**Issue by wockkkk** [Pixeval/Pixeval#545]
### Pixeval的版本

WinUI3

### 问题描述

![image](https://github.com/user-attachments/assets/c0c6b65b-1cc0-462f-a05f-a0744bc89769)

### Windows主要版本

Windows 10

### 其他信息

pixiv换IP了，改一下域前置IP到210.140.139.155即可

**Comment by Poker-sang** [comment]
参考#542修复
