### ISSUE TITLE
win10商店下载安装失败

### ISSUE THREAD

**Issue by jiecaoshixiao** [Pixeval/Pixeval#546]
### Pixeval's version

WinUI3

### Description of the problem

win10，系统更新已关闭，商店主页能打开，安装显示“应用安装程序无法安装应用包相关项。请向开发人员索要应用包”这个是什么原因，还有3.1.5的环境是什么，点击下载没反应了

### Screenshot

![image](https://github.com/user-attachments/assets/7369253a-4be1-4098-87ad-84f57bb0983d)
![image](https://github.com/user-attachments/assets/a2615c8a-0c5e-4b23-add9-15bd7976530d)

### Windows major version

Windows 10

**Comment by Poker-sang** [comment]
新版需要win10.0.19041以上版本
旧版需要net core 3.1的runtime

**Comment by jiecaoshixiao** [comment]
好的，谢谢
