### ISSUE TITLE
WPF版本一直更新个人资料

### ISSUE THREAD

**Issue by ljxlovelive** [Pixeval/Pixeval#547]
### Pixeval's version

WPF

### Description of the problem

挺喜欢用这个版本的

### Screenshot

![QQ截图20241205211721](https://github.com/user-attachments/assets/29a319dd-857d-4319-a973-0ccb9ff832a7)

### Windows major version

Windows 10

**Comment by Poker-sang** [comment]
可能是域前置ip不对导致。可以挂梯子，或者参考release上面写的方法（文件夹内新建cfg文件）

**Comment by ljxlovelive** [comment]
无论改cfg还是vpn都是214 新版本也有一样的问题

**Comment by Poker-sang** [comment]
参考这个修复 https://github.com/Pixeval/Pixeval/issues/542#issuecomment-2516363656

**Comment by ljxlovelive** [comment]
谢谢了,新版本用的不是很适应,老版本没有救了吗?
