### ISSUE TITLE
遇到了登入困难

### ISSUE THREAD

**Issue by icaruskgura** [Pixeval/Pixeval#548]
### 建议类型

功能优化

### Pixeval的版本

WinUI3

### 描述

小白提问，我是使用老版本的老家伙了，很久没更新过pixval，老版本突然无法登入，卡在用户个人资料更新，所以尝试使用新版本，但是依旧无法登入，请求帮助！（电脑苦手）
1.新版本的令牌登入是什么？没搞明白。2.webview显示错误。3.然后是网页登入，在正常登入p站后直接白屏卡住，没有任何反应。
三种登入方式都无法登入所以发帖请教

**Comment by Poker-sang** [comment]
1. 你第一次登录成功之后，P站会给你一个令牌以便以后不需要账号密码也能登录。也就是说你是无法自己获取令牌的，只能先通过账号密码方法登录，令牌方式写在第一页纯粹是为了混过微软商店的审核
2. 如果错误是421，则是最近p站ip更新导致的，临时解决方案可以查看https://github.com/Pixeval/Pixeval/issues/542#issuecomment-2516363656
3. 第三种方式很不稳定，不太建议用这种，要等summpot来修

**Comment by Poker-sang** [comment]
刷新令牌一般不会失效。

刷新令牌要在网页上登录后的响应中拿到，不太好找，建议用webview（支持域前置）或者浏览器方式（需要自己挂梯子），实现登录

**Comment by Poker-sang** [comment]
可以关闭

内部没有代理，只是直接对域前置指定的ip发送了请求，绕过了dns，以避免sni嗅探
