### ISSUE TITLE
登录闪退

### ISSUE THREAD

**Issue by qingmozimeng** [Pixeval/Pixeval#549]
### Pixeval's version

WinUI3

### Description of the problem

Webview登录就会出现提示并且闪退，使用edge登录会即时闪退，无法登陆使用，老版的前两天正常使用，现在也登陆不上去，一直转圈圈，挂上vpn也进不去，所以尝试新版

### Screenshot

![QQ20241206-003727](https://github.com/user-attachments/assets/5fec8d11-2742-47dc-8057-a88c393d93e4)

### Windows major version

Windows 10

### Specific Windows version

Windows 11 22H2 (22621)

**Comment by Poker-sang** [comment]
最好在打开软件之前先打开vpn。
老版可以通过新建cfg文件修复（https://github.com/Pixeval/Pixeval/releases/tag/3.1.5）

**Comment by qingmozimeng** [comment]
> 最好在打开软件之前先打开vpn。 老版本可以通过新建cfg文件修复（https://github.com/Pixeval/Pixeval/releases/tag/3.1.5）

在打开之前是已经打开了vpn的，就是这样无限闪退

**Comment by qingmozimeng** [comment]
Uploading 2024-12-06 20-10-53_20241206_20132326_20241206_20142948.mp4…

就是这样

**Comment by Poker-sang** [comment]
视频没传上

**Comment by zeroky112** [comment]
> 最好在打开软件之前先打开VPN。 老版可以通过新建cfg文件修复（https://github.com/Pixeval/Pixeval/releases/tag/3.1.5）老版本新建了也填了新的IP但是并没有什么用。。。可能是我填的这点IP不对吧

**Comment by Poker-sang** [comment]
想起来老版没提供登陆ip池，所以暂时修不了

**Comment by zeroky112** [comment]
好吧
