### ISSUE TITLE
软件无法正常使用

### ISSUE THREAD

**Issue by mmmmkmio** [Pixeval/Pixeval#551]
### Pixeval的版本 / Pixeval's version

WinUI 3

### 问题描述 / Description of the problem

关闭域前置时通过webview登陆会出现截图中的情况
开启域前置时通过webview登陆会错误代码421
上传了日志文件

### 屏幕截图 / Screenshot

![84821d83-e096-4dbe-b6dc-8361804475e2](https://github.com/user-attachments/assets/8096ef77-81df-49d4-ab27-d4f04ce2042d)

### 错误代码 / Error code

[2024-12-07 15.log](https://github.com/user-attachments/files/18047642/2024-12-07.15.log)

### Windows主要版本 / Windows major version

Windows 11

### 其他信息 / Additional Information

能确保我的网络代理是有效的

**Comment by Poker-sang** [comment]
我刚刚尝试用代理登录，可以进入，你可以再检查一下你的操作流程：
1. 打开全局代理
2. 打开Pixeval
3. 选择WebView2登录、关闭域前置
4. 点登录

**Comment by mmmmkmio** [comment]
好的我进行一次尝试


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月7日(周六) 下午5:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Pixeval/Pixeval] 软件无法正常使用 (Issue #551)




 
我刚刚尝试用代理登录，可以进入，你可以再检查一下你的操作流程：
  
打开全局代理
 
打开Pixeval
 
选择WebView2登录、关闭域前置
 
点登录
  
&mdash;

**Comment by mmmmkmio** [comment]
我这还是不行，
![Uploading image.png…]()
报错

**Comment by mmmmkmio** [comment]
内容是获取对话失败

**Comment by Poker-sang** [comment]
加我qq2639914082我给你单独解决一下好了
