### ISSUE TITLE
刷新失败，无法登录

### ISSUE THREAD

**Issue by RainyGrass** [Pixeval/Pixeval#552]
### Pixeval的版本 / Pixeval's version

WinUI 3

### 问题描述 / Description of the problem

打开软件出现刷新失败提示，且无法通过WebView登录我的账户

### 屏幕截图 / Screenshot

![image](https://github.com/user-attachments/assets/768648f2-498b-4070-ae9c-665b95976ba1)
![image](https://github.com/user-attachments/assets/e4614b62-2f90-4dc3-b263-93554d4ec11e)

### Windows主要版本 / Windows major version

Windows 11

### 其他信息 / Additional Information

还有一个问题就是“测试功能：通过浏览器登录”一直不出现网页。

**Comment by Poker-sang** [comment]
参考这个修复 https://github.com/Pixeval/Pixeval/issues/542#issuecomment-2516363656

**Comment by RainyGrass** [comment]
感谢，问题已解决，但以后每次登录都要点击取消域前置吗？如果取消域前置在本国是否就无法访问了？

**Comment by Poker-sang** [comment]
改过ip之后，就可以正常使用域前置登录看图了
