### ISSUE TITLE
域名前置疑似失效

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [Pixeval/Pixeval#554]
### Pixeval的版本 / Pixeval's version

WinUI 3

### 问题描述 / Description of the problem

域名前置疑似失效，无法登录和载图

### 屏幕截图 / Screenshot

![image](https://github.com/user-attachments/assets/c67ac410-8c1b-49ab-8de0-bd6dd348f8c8)

### Windows主要版本 / Windows major version

Windows 11

**Comment by Poker-sang** [comment]
参考 #542 修复

**Comment by S-t-e-v-e-e** [comment]
> 参考 #542 修复

![image](https://github.com/user-attachments/assets/59a13fb0-66d5-448d-8abf-bce8959a41d0)

![image](https://github.com/user-attachments/assets/81845a07-6232-4df2-b583-00fae7fae8ed)

好像没变化（

**Comment by Poker-sang** [comment]
难不成api的ip又变了，过两天我考完试看看

**Comment by icaruskgura** [comment]
> 难不成api的ip又变了，过两天我考完试看看

我的域前禁止了 结果出现获取对话失败 怎么办呢

**Comment by Poker-sang** [comment]
可能是网络问题，你可以用那个issue下面的方法2，不需要关闭域前置就能使用
