### ISSUE TITLE
v4.3.0 Cookies 问题

### ISSUE THREAD

**Issue by YRSB** [Pixeval/Pixeval#562]
### Pixeval的版本 / Pixeval's version

WinUI 3

### 问题描述 / Description of the problem

为了使用动态，需要填写Cookies，我从Web抓取并填入Pixeval后，无法加载动态。
顺便一提，请问填写的格式是什么？直接填写 和 "PHPSESSID=xxxxxx"这两种我都试过，结果都不行
参考的文章：https://sora.ink/archives/520
log都是重复的，我截取了一些片段

### 错误代码 / Error code

09:34:51 Error
MakoClient Exception
at LogException at C:\WorkSpace\Pixeval\src\Pixeval.CoreApi\MakoClient.Logging.cs: 151
	Type: Pixeval.CoreApi.Global.Exception.MakoNetworkException
	Source: 
	Message: Network error while requesting URL: /stacc?mode=unify(Domain fronting: False, Status code: 302) 
	StackTrace: 
		null

09:34:52 Error
MakoClient Exception
at LogException at C:\WorkSpace\Pixeval\src\Pixeval.CoreApi\MakoClient.Logging.cs: 151
	Type: Pixeval.CoreApi.Global.Exception.MakoNetworkException
	Source: 
	Message: Network error while requesting URL: /stacc?mode=unify(Domain fronting: False, Status code: 302) 
	StackTrace: 
		null

09:34:52 Error
MakoClient Exception
at LogException at C:\WorkSpace\Pixeval\src\Pixeval.CoreApi\MakoClient.Logging.cs: 151
	Type: Pixeval.CoreApi.Global.Exception.MakoNetworkException
	Source: 
	Message: Network error while requesting URL: /stacc?mode=unify(Domain fronting: False, Status code: 302) 
	StackTrace: 
		null

### Windows主要版本 / Windows major version

Windows 11

**Comment by Poker-sang** [comment]
cookie可以在pixiv网页版f12随便找个请求头复制一下，但不要用document.cookie

**Comment by YRSB** [comment]
已解决。
步骤：复制完整的 Cookies，而非单独的字段 PHPSESSID

**Comment by TokcDK** [comment]
I will remark what to be able to login there in Pixiv settings must be set location to Japanese. Maybe also enabled options to show R18 content and AI generated content. The info about location found in PixivFE. I was unable to login before I changed settings and I had other location set by default.
