### ISSUE TITLE
点击“保存”键保存图片时，显示“处理图片中”，无法下载

### ISSUE THREAD

**Issue by SuanOrange** [Pixeval/Pixeval#563]
### Pixeval的版本 / Pixeval's version

WinUI 3

### 问题描述 / Description of the problem

点击“保存”键保存图片时，显示“处理图片中”，无法下载

### 屏幕截图 / Screenshot

![3](https://github.com/user-attachments/assets/6cc790aa-c84d-47cb-b222-d9d10572afdb)

### Windows主要版本 / Windows major version

Windows 10

### 其他信息 / Additional Information

点击“保存”键无法保存，但是“另存为”就可以正常下载

**Comment by Poker-sang** [comment]
可以检查一下设置中的下载位置，pixeval更新了一些宏导致和之前不兼容
