### ISSUE TITLE
自定义保存路径时报错：未知的宏名称：if_illust

### ISSUE THREAD

**Issue by SuanOrange** [Pixeval/Pixeval#564]
### Pixeval的版本 / Pixeval's version

WinUI 3

### 问题描述 / Description of the problem

自定义保存路径时报错：未知的宏名称：if_illust

### 屏幕截图 / Screenshot

![1](https://github.com/user-attachments/assets/34996268-fadf-4ec2-a3ab-b4f6d250654b)
图片1中的路径为应用默认的保存路径
![2](https://github.com/user-attachments/assets/87b43ce0-78b5-4eab-a098-f2dcfa631c9a)
图片2中仅更改了宏前的路径，出现了报错

### Windows主要版本 / Windows major version

Windows 10

**Comment by Poker-sang** [comment]
if illust变成if pic all了以统一命名规范

**Comment by Poker-sang** [comment]
喔难不成忘了改默认路径了】

**Comment by Poker-sang** [comment]
直接推了个4.3.1了
