### ISSUE TITLE
打开图片后在关闭图片窗口，瀑布流会中断

### ISSUE THREAD

**Issue by Malus-risus** [Pixeval/Pixeval#581]
### Pixeval的版本 / Pixeval's version

WinUI 3

### 问题描述 / Description of the problem

打开图片后在关闭图片窗口，瀑布流会中断，必须重新刷新才能解决，这造成了很大的困扰（之前刷着的图刷新后消失）

### 屏幕截图 / Screenshot

![image](https://github.com/user-attachments/assets/1e9989b4-a081-46e5-acb6-bcd1143edec4)

### 错误代码 / Error code

[2024-12-29 01.log](https://github.com/user-attachments/files/18268917/2024-12-29.01.log)

### Windows主要版本 / Windows major version

Windows 11

**Comment by Malus-risus** [comment]
![image](https://github.com/user-attachments/assets/d601c0fa-962b-457f-8ce7-981f6c2fb7e5)
貌似出现了类似问题，这次是显示无法加载图片。

**Comment by Poker-sang** [comment]
你开启文件缓存功能了吗

**Comment by Malus-risus** [comment]
> 你开启文件缓存功能了吗

没，只开启了原图

**Comment by Poker-sang** [comment]
感觉有可能是撞rate limit了，或者是什么refresh token失效，可以看看日志

**Comment by Malus-risus** [comment]
> 感觉有可能是撞rate limit了，或者是什么refresh token失效，可以看看日志

没找到相关时间段的日志
