### ISSUE TITLE
搜索限制某些不起作用

### ISSUE THREAD

**Issue by player1026** [Pixeval/Pixeval#583]
### Pixeval的版本 / Pixeval's version

WinUI 3

### 问题描述 / Description of the problem

# 搜索范围限制
在上方搜索栏搜索：<ins>工藤新一</ins>作为测试，结果限制为**半年内**、**一年内**将不会搜索到任何图片（已排查网络问题并关闭精确搜索范围）
# 精确搜索范围限制
将精确搜索范围限制开关**打开**，调整限制时间为**约一个月内**后，直接在上方搜索栏搜索tag:<ins>工藤新一</ins>，结果只出现**一天内**（默认搜索限制）的图片
调整限制时间为**约一个月内**后按下enter键（跳出了[已失效的github.io页面](https://piexval.github.io/)），在上方搜索栏搜索：<ins>工藤新一</ins>，结果依然只出现一天内（默认搜索限制）的图片
调整限制时间为**约前一个月内**后按下enter键（未跳出已失效的github.io页面），在上方搜索栏搜索：<ins>工藤新一</ins>，结果依然只出现一天内（默认搜索限制）的图片
# 重新启动
重新启动程序后，按照上述流程再一次测试，bug依然存在（但是不会跳出已失效的github.io页面）

### Windows主要版本 / Windows major version

Windows 11

### 其他信息 / Additional Information

我的部分设置信息
> 搜索历史限制：50
> 搜索框历史数量限制：10
> 浏览历史限制：256
> Cookie：无
> API平台：Android

其他信息
> Pixiveal版本：4.3.1.0

**Comment by Poker-sang** [comment]
好像是因为 **搜索范围限制** 是老API，现在不用了

**Comment by Poker-sang** [comment]
谢谢，已修复，你的反馈很详细】
