### ISSUE TITLE
搜索框不能合并相同搜索项

### ISSUE THREAD

**Issue by player1026** [Pixeval/Pixeval#588]
### Pixeval的版本 / Pixeval's version

WinUI 3

### 问题描述 / Description of the problem

# 概述
在搜索框中记忆两条及以上不同的搜索记录时，再次搜索除第一条搜索记录以外的内容会重复搜索内容直到限制数量
# Bug复现
1.清空搜索记录，此时没有搜索记录
2.在搜索框搜索：<ins>女の子</ins>
3.清空搜索框，并搜索<ins>東方</ins>
4.随机点击一张图片，按下F12调出详细信息并点击<ins>東方</ins>标签（即再次搜索<ins>東方</ins>）
5.清空搜索框，搜索记录为1个<ins>女の子</ins>标签和 _2个_ <ins>東方</ins>标签([截图1](https://github.com/user-attachments/assets/2fa92c17-486f-4d01-84c0-ebb10165ce3a))
6.调整搜索历史数量限制为5个，重复搜索<ins>東方</ins>内容3次，此时搜索记录为1个<ins>女の子</ins>标签和 _4个_ <ins>東方</ins>标签([截图2](https://github.com/user-attachments/assets/85563fbb-bd50-4fd5-9793-9a07e6c3b049))
7.调整搜索历史数量限制为10个（不搜索任何内容），此时搜索记录为1个<ins>女の子</ins>标签和 _5个_ <ins>東方</ins>标签([截图3](https://github.com/user-attachments/assets/4e7c945a-a280-4354-ace3-ed2e6736904f))
8.使用<ins>バニーガール</ins>标签进行验证得到相似结果([截图4](https://github.com/user-attachments/assets/85af180e-fd6e-4a77-a24f-8dcbaf718809))

### 屏幕截图 / Screenshot

<img width="267" alt="1" src="https://github.com/user-attachments/assets/2fa92c17-486f-4d01-84c0-ebb10165ce3a" />
<img width="267" alt="2" src="https://github.com/user-attachments/assets/85563fbb-bd50-4fd5-9793-9a07e6c3b049" />
<img width="260" alt="3" src="https://github.com/user-attachments/assets/4e7c945a-a280-4354-ace3-ed2e6736904f" />
<img width="260" alt="4" src="https://github.com/user-attachments/assets/85af180e-fd6e-4a77-a24f-8dcbaf718809" />

### Windows主要版本 / Windows major version

Windows 11

### 其他信息 / Additional Information

仅**第一项搜索记录**不会重复
**第二项及以后的搜索记录**，不论是否重复，都会直接记忆直到数量限制
重启应用**不会**合并相同的历史记录，事实上重启应用不会对搜索记录发生改变

**Comment by Poker-sang** [comment]
之前把历史记录顺序倒过来，忘了也把查询顺序倒置了
