### ISSUE TITLE
Build a wiki site

### ISSUE THREAD

**Issue by lushuyu** [Pixeval/Pixeval#6]

**Comment by Rinacm** [comment]
I‘m planning to build a whole website about this project but now I need to implement those features in the to do list first, as you can see I'm working alone so I have no time to build the wiki for now, however I will try to finish other jobs as fast as I can and then start building wiki site

**Comment by lushuyu** [comment]
> I‘m planning to build a whole website about this project but now I need to implement those features in the to do list first, as you can see I'm working alone so I have no time to build the wiki for now, however I will try to finish other jobs as fast as I can and then start building wiki site

Hello Pixeval!
Sorry I just made a mistake and didn't add any discription to this issue.
I sincerely want to make some contribution to this wonderful project.
I am new in C#.But I can do someting with HTML and CSS.
So I am glad to help build a wiki site.
Don't mind my poor English /kk

**Comment by Rinacm** [comment]
> > I‘m planning to build a whole website about this project but now I need to implement those features in the to do list first, as you can see I'm working alone so I have no time to build the wiki for now, however I will try to finish other jobs as fast as I can and then start building wiki site
> 
> Hello Pixeval!
> Sorry I just made a mistake and didn't add any discription to this issue.
> I sincerely want to make some contribution to this wonderful project.
> I am new in C#.But I can do someting with HTML and CSS.
> So I am glad to help build a wiki site.
> Don't mind my poor English /kk

草所以我们用中文交流如何？

**Comment by lushuyu** [comment]
> > > I‘m planning to build a whole website about this project but now I need to implement those features in the to do list first, as you can see I'm working alone so I have no time to build the wiki for now, however I will try to finish other jobs as fast as I can and then start building wiki site
> > 
> > 
> > Hello Pixeval!
> > Sorry I just made a mistake and didn't add any discription to this issue.
> > I sincerely want to make some contribution to this wonderful project.
> > I am new in C#.But I can do someting with HTML and CSS.
> > So I am glad to help build a wiki site.
> > Don't mind my poor English /kk
> 
> 草所以我们用中文交流如何？

有道理啊 我英语作文每次都20分左右 其实是想来练习英语的

**Comment by Rinacm** [comment]
> > > > I‘m planning to build a whole website about this project but now I need to implement those features in the to do list first, as you can see I'm working alone so I have no time to build the wiki for now, however I will try to finish other jobs as fast as I can and then start building wiki site
> > > 
> > > 
> > > Hello Pixeval!
> > > Sorry I just made a mistake and didn't add any discription to this issue.
> > > I sincerely want to make some contribution to this wonderful project.
> > > I am new in C#.But I can do someting with HTML and CSS.
> > > So I am glad to help build a wiki site.
> > > Don't mind my poor English /kk
> > 
> > 
> > 草所以我们用中文交流如何？
> 
> 有道理啊 我英语作文每次都20分左右 其实是想来练习英语的

多读文档就好，我身边好多英语比较好的都没有特别去练(((

**Comment by lushuyu** [comment]
> > > > > I‘m planning to build a whole website about this project but now I need to implement those features in the to do list first, as you can see I'm working alone so I have no time to build the wiki for now, however I will try to finish other jobs as fast as I can and then start building wiki site
> > > > 
> > > > 
> > > > Hello Pixeval!
> > > > Sorry I just made a mistake and didn't add any discription to this issue.
> > > > I sincerely want to make some contribution to this wonderful project.
> > > > I am new in C#.But I can do someting with HTML and CSS.
> > > > So I am glad to help build a wiki site.
> > > > Don't mind my poor English /kk
> > > 
> > > 
> > > 草所以我们用中文交流如何？
> > 
> > 
> > 有道理啊 我英语作文每次都20分左右 其实是想来练习英语的
> 
> 多读文档就好，我身边好多英语比较好的都没有特别去练(((

所以这个issue应该改名成为如何英语作文拿高分（（（
另外安利一下我的[Chi-Wiki](https://github.com/lushuyu/Chi-Wiki)

**Comment by Rinacm** [comment]
> > > > > > I‘m planning to build a whole website about this project but now I need to implement those features in the to do list first, as you can see I'm working alone so I have no time to build the wiki for now, however I will try to finish other jobs as fast as I can and then start building wiki site
> > > > > 
> > > > > 
> > > > > Hello Pixeval!
> > > > > Sorry I just made a mistake and didn't add any discription to this issue.
> > > > > I sincerely want to make some contribution to this wonderful project.
> > > > > I am new in C#.But I can do someting with HTML and CSS.
> > > > > So I am glad to help build a wiki site.
> > > > > Don't mind my poor English /kk
> > > > 
> > > > 
> > > > 草所以我们用中文交流如何？
> > > 
> > > 
> > > 有道理啊 我英语作文每次都20分左右 其实是想来练习英语的
> > 
> > 
> > 多读文档就好，我身边好多英语比较好的都没有特别去练(((
> 
> 所以这个issue应该改名成为如何英语作文拿高分（（（
> 另外安利一下我的[Chi-Wiki](https://github.com/lushuyu/Chi-Wiki)

草这个东西还蛮有用的，反正我的文言文阅读一般会栽
顺便我最近wiki的文档写完发给你，不嫌麻烦的话可以加下我的qq 2653221698(

**Comment by lushuyu** [comment]
> > > > > > > I‘m planning to build a whole website about this project but now I need to implement those features in the to do list first, as you can see I'm working alone so I have no time to build the wiki for now, however I will try to finish other jobs as fast as I can and then start building wiki site
> > > > > > 
> > > > > > 
> > > > > > Hello Pixeval!
> > > > > > Sorry I just made a mistake and didn't add any discription to this issue.
> > > > > > I sincerely want to make some contribution to this wonderful project.
> > > > > > I am new in C#.But I can do someting with HTML and CSS.
> > > > > > So I am glad to help build a wiki site.
> > > > > > Don't mind my poor English /kk
> > > > > 
> > > > > 
> > > > > 草所以我们用中文交流如何？
> > > > 
> > > > 
> > > > 有道理啊 我英语作文每次都20分左右 其实是想来练习英语的
> > > 
> > > 
> > > 多读文档就好，我身边好多英语比较好的都没有特别去练(((
> > 
> > 
> > 所以这个issue应该改名成为如何英语作文拿高分（（（
> > 另外安利一下我的[Chi-Wiki](https://github.com/lushuyu/Chi-Wiki)
> 
> 草这个东西还蛮有用的，反正我的文言文阅读一般会栽
> 顺便我最近wiki的文档写完发给你，不嫌麻烦的话可以加下我的qq 2653221698(

用telegram如何？QQ不怎么方便

**Comment by lushuyu** [comment]
> > > > > > > I‘m planning to build a whole website about this project but now I need to implement those features in the to do list first, as you can see I'm working alone so I have no time to build the wiki for now, however I will try to finish other jobs as fast as I can and then start building wiki site
> > > > > > 
> > > > > > 
> > > > > > Hello Pixeval!
> > > > > > Sorry I just made a mistake and didn't add any discription to this issue.
> > > > > > I sincerely want to make some contribution to this wonderful project.
> > > > > > I am new in C#.But I can do someting with HTML and CSS.
> > > > > > So I am glad to help build a wiki site.
> > > > > > Don't mind my poor English /kk
> > > > > 
> > > > > 
> > > > > 草所以我们用中文交流如何？
> > > > 
> > > > 
> > > > 有道理啊 我英语作文每次都20分左右 其实是想来练习英语的
> > > 
> > > 
> > > 多读文档就好，我身边好多英语比较好的都没有特别去练(((
> > 
> > 
> > 所以这个issue应该改名成为如何英语作文拿高分（（（
> > 另外安利一下我的[Chi-Wiki](https://github.com/lushuyu/Chi-Wiki)
> 
> 草这个东西还蛮有用的，反正我的文言文阅读一般会栽
> 顺便我最近wiki的文档写完发给你，不嫌麻烦的话可以加下我的qq 2653221698(

https://t.me/lovely_xianshen

**Comment by Rinacm** [comment]
> > > > > > > > I‘m planning to build a whole website about this project but now I need to implement those features in the to do list first, as you can see I'm working alone so I have no time to build the wiki for now, however I will try to finish other jobs as fast as I can and then start building wiki site
> > > > > > > 
> > > > > > > 
> > > > > > > Hello Pixeval!
> > > > > > > Sorry I just made a mistake and didn't add any discription to this issue.
> > > > > > > I sincerely want to make some contribution to this wonderful project.
> > > > > > > I am new in C#.But I can do someting with HTML and CSS.
> > > > > > > So I am glad to help build a wiki site.
> > > > > > > Don't mind my poor English /kk
> > > > > > 
> > > > > > 
> > > > > > 草所以我们用中文交流如何？
> > > > > 
> > > > > 
> > > > > 有道理啊 我英语作文每次都20分左右 其实是想来练习英语的
> > > > 
> > > > 
> > > > 多读文档就好，我身边好多英语比较好的都没有特别去练(((
> > > 
> > > 
> > > 所以这个issue应该改名成为如何英语作文拿高分（（（
> > > 另外安利一下我的[Chi-Wiki](https://github.com/lushuyu/Chi-Wiki)
> > 
> > 
> > 草这个东西还蛮有用的，反正我的文言文阅读一般会栽
> > 顺便我最近wiki的文档写完发给你，不嫌麻烦的话可以加下我的qq 2653221698(
> 
> 用telegram如何？QQ不怎么方便

tg也行，不过我没怎么用过tg，等到我先把手头这点事情忙完

**Comment by Takakura-Anri** [comment]
用 GitHub 的 Wiki 功能不就好了

**Comment by 233mc44** [comment]
Don't github have Wiki feature?I advise everybody who likes to edit this project takes part in the work of editing the wiki.

And please,don't mind my poor English too.

**Comment by TheRealKamisama** [comment]
> 
> 
> 用 GitHub 的 Wiki 功能不就好了

写了也没人看
