### ISSUE TITLE
关于代理设置

### ISSUE THREAD

**Issue by anosu** [Pixeval/Pixeval#77]
能不能加入像telegram一样的内置socks5代理，还是感觉直连速度有点慢

**Comment by Rinacm** [comment]
你可以在设置选择不使用直连，然后就会默认使用系统代理了

**Comment by Chirinama** [comment]
为什么我使用系统代理图片加载不出来，浏览器可以正常访问

**Comment by Chirinama** [comment]
> 你可以在设置选择不使用直连，然后就会默认使用系统代理了

如果我只想让Pixval一个软件使用代理该如何做呢

**Comment by Rinacm** [comment]
图片加载不出来？你确定你是关闭了直连启动了系统代理？
如果只想要pixeval一个软件是用代理的话，我可以添加到todo列表里加上这个功能，不过要过一段时间
我这段时间还没放假，在备考

**Comment by Chirinama** [comment]
> 图片加载不出来？你确定你是关闭了直连启动了系统代理？
> 如果只想要pixeval一个软件是用代理的话，我可以添加到todo列表里加上这个功能，不过要过一段时间
> 我这段时间还没放假，在备考

嗯，好的
