### ISSUE TITLE
图片能全屏欣赏就好了。不关闭看图窗口就能跳转下组图片浏览就更好了

### ISSUE THREAD

**Issue by diyifirst** [Pixeval/Pixeval#86]
个人观点，提点建议：
1.看图窗口太小，不能全屏看图。
2.浏览完当前图片不能跳转到下一组图片，需要重复开关看图窗口，在线浏览不方便。

**Comment by Rinacm** [comment]
其实这两点最开始的版本都有，但是经过用户反馈改成了现在这个样子、
这个issue挂在这里，如果没有更多用户反馈的话这点大概不会变

**Comment by zmyspc** [comment]
附议，窗口太小了，哪怕是4K显示屏，显示面积也占不到1/4，1080P都不到，加上缩放后很模糊，体验很糟糕。
看图也是核心功能，应该有更多选择吧，这样不能取代网站就有种鸡肋的感觉。

**Comment by wbygit** [comment]
嗯，我之前也提出过类似issue，所以再反馈一下

**Comment by rockwallll** [comment]
这边提一下surface体验，因为我用的大缩放比，所以我的大图体验还不错。但是我认为小图体验不够好，空白区域太多了，不够紧凑。
另外，触控体验较为糟糕（不顺滑），不过这可能是exe的通病？？？

**Comment by dylech30th** [comment]
触控体验这个要么是WPF框架的问题，要么就是通病，本来win32对于触屏的适配大概也不如UWP

**Comment by banafish** [comment]
我也觉得加个全屏显示图片好一点，今天点了很久图片发现不能全屏显示，或者可以点击图片显示小窗口，然后再点击图片就全屏显示？

**Comment by Poker-sang** [comment]
最新版本已实现
