### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by chijiansama** [Pixeval/Pixeval#97]
- [x] 1、收藏的时候没办法选择添加收藏标签（希望能像p站那样长按编辑，收藏编辑和关注编辑，或者收藏的时候自动添加收藏标签，收藏页面能批量编辑标签就更好了）
- [x] 2、首页的作者推荐（希望可以加一个手动刷新，以便遇见更多优质画师）
- [x] 3、图片查看的时候希望可以用鼠标滚轮放大缩小图片，以便加载完可以直接看到细节，不用特意下载出来
- [x] 4、查看收藏的时候希望可以按收藏的标签查找收藏的特定图片

**Comment by Rinacm** [comment]
手动刷新是有的，作者推荐鼠标往右移就可以看到刷新按钮，默认是隐藏的= =
其他的功能会慢慢实现

**Comment by KIITTID** [comment]
建议加一个动态磁贴功能

**Comment by Poker-sang** [comment]
什么是动态磁贴

**Comment by n0099** [comment]
建议梦回win81
